### ISSUE TITLE
[PSA] ASUS AI Suite 3 hurts performance

### ISSUE THREAD

**Issue by chendo** [yamashi/CyberEngineTweaks#105]
It appears ASUS AI Suite 3 causes Cyberpunk to perform poorly. In my case, it was causing my 5800X/3080 machine to only achieve ~75fps at Low settings, and customised Ultra+RT runs at ~75fps.

If these patches do not fix your performance issue and you have AI Suite 3 installed, you should purge it from your system and perform an in-place upgrade of Windows, as this worked for me and my FPS doubled to 144fps (monitor max) at Low, and Ultra+RT runs ~10fps faster and feels smoother.

See https://forums.cdprojektred.com/index.php?threads/cant-get-over-60-65-fps-no-matter-what-resolution-or-settings-on-pc.11043734/page-10#post-12392714

@yamashi I'd like to add this to the wiki but am unable to

**Comment by lextra2** [comment]
Asus Bloatware®™ messes with your system. Who would have guessed...

**Comment by Squall-Leonhart** [comment]
You don't need to inplace upgrade, you can use autoruns to delete the AsIO driver that aisuite installs.

**Comment by NielsGx** [comment]
No issue with Asus gpu tweak
