### ISSUE TITLE
[Feature Request] Dynamic resolution combat/hostile area profile

### ISSUE THREAD

**Issue by dissociativity** [yamashi/CyberEngineTweaks#107]
Allow enabling 50% min dynamic res and 60fps targer only in combat
Go back to whatever out of combat.

Many of us love the scenery and want to maintain as nice an image as possible, as the game still looks incredible on low with textures on high/ultra, 

but combat becomes a nightmare even when I've got my target at 40, at a comfortable 80% minimum res scale, which looks lovely on my machine and it lovely for sightseeing/non combat settings

**Comment by NielsGx** [comment]
Would be great.

Personally Iw ould leave texture wuality at high bc I don't see any fps imrpovment, but I would disable SSR and make the game runs at 75% res when in combat, and re-enable the great SSR that kill my framerate for gorgeous graphics while wandering in Night City
