### ISSUE TITLE
Post your crashes

### ISSUE THREAD

**Issue by yamashi** [yamashi/CyberEngineTweaks#12]
Hey guys,

It would be great if you could post the crashes you are getting in game here. I am not talking about crashes related to the mod (I don't see any reason that would happen) but game crashes.

### What constitutes a good crash report?

1. **It HAS to be reproducible**, meaning every time you play the game and do a specific action or go to a specific place the game crashes. Saying "it crashes while I was driving" is not useful.
2. It should contain a detailed description of how to reproduce the bug (sending the save associated with the crash is probably always required).
3. It would be best if it contained a crash dump. You can find them in `C:\Users{user}\AppData\Local\REDEngine\ReportQueue`, go in the most recent directory and send the Cyberpunk2077.dmp file.

### How to send

Create an issue on github prefixed with `[crash]`, (for example: "[crash] Equipping a specific weapon 100% repro rate"

- Post a detailed description of how to reproduce the bug.  
- Upload any file you think is relevant to the bug (save file for example).

Thanks!

**Comment by KubaJastrz** [comment]
I've noticed that the game almost always (like 90%) shows a CDPR crash report after exiting after the v1.04 official patch. Should I also report it here? Not sure if that counts as "in game" 😄

**Comment by jeroenwalter** [comment]
Had a peek in de CrashReporter.exe.
Crashes are sent to https://drop.crashes.cyberpunk.net, so if you add that url to your firewall's outgoing blacklist, reports can't be sent any longer. The crash reporter then shouldn't delete the crash reports. Instead it keeps trying to send old reports for a number of days.
The reports should be saved in C:\Users\{user}\AppData\Local\REDEngine\ReportQueue
I haven't tested this, as CP2077 fortunately runs rock steady on my system.

**Comment by yamashi** [comment]
> 
> 
> Had a peek in de CrashReporter.exe.
> Crashes are sent to https://drop.crashes.cyberpunk.net, so if you add that url to your firewall's outgoing blacklist, reports can't be sent any longer. The crash reporter then shouldn't delete the crash reports. Instead it keeps trying to send old reports for a number of days.
> The reports should be saved in C:\Users{user}\AppData\Local\REDEngine\ReportQueue
> I haven't tested this, as CP2077 fortunately runs rock steady on my system.

Thanks for your research! I will add it.

**Comment by Minashiro-Soushi** [comment]
> I've noticed that the game almost always (like 90%) shows a CDPR crash report after exiting after the v1.04 official patch. Should I also report it here? Not sure if that counts as "in game"

Unrelated to this project, I'm having exactly the same issue after v1.04 and haven't used PerformanceOverhaul yet.

**Comment by CorruptComputer** [comment]
Here are a few crashes I have experienced so far, I'm not entirely sure what the cause of most of them are, however I know at least 2 were caused by trying to stream the game on Discord.
[ReportQueue.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691316/ReportQueue.zip)

**Comment by tw1cee** [comment]
Hi guys i just downloaded performance mod from here and in debug menu i accidentaly unlocked all vehicles. How can i lock it back? Is it possible? Sorry for my english...

**Comment by jeroenwalter** [comment]
> Hi guys i just downloaded performance mod from here and in debug menu i accidentaly unlocked all vehicles. How can i lock it back? Is it possible? Sorry for my english...

Please don't pollute this thread with non-related questions.
If you have a crash, you can post it here. 
If not, create a new issue with your question, although in my opinion your question is not applicable to this project. 
This project allows you to enable the debug menu; it should not try to fix the actions caused by actually using the debug menu, as the debug menu is not written by the author of this project. Contact CDPR for that :)

That said, you may try to load a previous save game where you haven't unlocked all vehicles.

@yamashi if this comment is too harsh or if I'm mistaken, please delete it.

**Comment by DarthJahus** [comment]
Here are some game crashes. Happened after changing some graphics settings (that same action can be usually done without problem, but sometimes, after changing settings, the game crashes).

[Cyberpunk2077-logs.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5702337/Cyberpunk2077-logs.zip)

**Comment by hallowf** [comment]
Here are some more crashes, some might be repeated.

More info:
 * First time installed the game was able to play at relatively low FPS but also relatively stable
 * Tried to mess around with my system, then an update came trough steam and the game stopped working
   - `Message: Failed to load archive D:\SteamLibrary\steamapps\common\Cyberpunk 2077\archive\pc\content\basegame_1_engine.archive, error 1, try regenerating archives!`
 * Ended up fixing it again but the fps where much lower than 20
 * Finally it broke again with the following error
   - `Expression: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
Message: The thread attempted to read inaccessible data at 0x0.`

How did i manage to fix it and break it again you might ask?
well here are the steps to fix:
- Uninstall all Microsoft Visual c++ redistributables
- Reinstall GPU drivers(this might not be required i just happened to need to do it)
- Install latest visual studio c++ redistributables from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)
- And to break the game just modify config files i don't know what value i messed with triggered the crash or if it's even related but [here](https://github.com/hallowf/CyberP_confs/commits/master) are the changes i made, PS: ignore the many reverts I'm not great with git

#### Note: This was all done before i even knew this tool existed haven't managed to fix the game yet and use this tool

[ReportQueue.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5705855/ReportQueue.zip)

**Comment by kohyzsc123** [comment]
Game would  crashed  when i press 'end' call console.  I'm using  release v1.0.2 version. Game version is v1.04.
Here is the report file
[REDEngine.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5718926/REDEngine.zip)

**Comment by Mavrag** [comment]
Can't use the new console feature with Reshade. It also uses END key for the menu. The game just crashes whenever END key is pressed.

**Comment by FelesNoctis** [comment]
> 
> 
> Can't use the new console feature with Reshade. It also uses END key for the menu. The game just crashes whenever END key is pressed.

Echoing this one with v1.3.0/https://github.com/yamashi/PerformanceOverhaulCyberpunk/commit/4a911033f183f70be031b6e4abd5330368a45361. Fullscreen, borderless window, and floating window all resulted in a crash to desktop when trying to open the console with Reshade installed. This was with the tilde (~) key, not END like the others, and Reshade had been rebound to Shift+F2.

The official stacktrace.txt in this situation contains this:
> Error reason: Unhandled exception
Expression: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
Message: The thread attempted to read inaccessible data at 0x0.
File: <Unknown>(0)

**Comment by ddylard** [comment]
After updating to latest AMD driver all versions of the program (even the old ones stopped working). At that moment if i took out the files from the mod the game would run normally...
Now i have a much worse problem... As i wanted the mod on win 7 i followed the steps recommended on the "windows7 support" issue and put d312to7 files on plugins folder , along with the dxinput_3.dll renamed to dxinput_4.dll.

Now my game is completely broken an refuses to startup everytime even if i took out every mod file. Pleas yamashi could you help me somehow?

**Comment by N7ZebraCakes** [comment]
Consistent crash opening console. 

Running in 2560×1440 in Borderless Windowed. 
Game version is 1.05
Did not have old version of the mod, only using what is on the site as of 8.45pm CST on 12/22/20
CPU:Ryzen 5 / GPU: GTX 2060 / OS: Win 10.0.19041
config json has spectre and virtual set as False. Heard reports of crashes at launch with SMT, so I tried with it enabled and disabled, crashes both ways
Config json and Log attached in zip file, config below as well: 
```
{
    "avx": true,
    "console": true,
    "console_key": 192,
    "cpu_memory_pool_fraction": 0.699999988079071,
    "disable_antialiasing": false,
    "disable_async_compute": false,
    "disable_boundary_teleport": false,
    "disable_intro_movies": true,
    "disable_vignette": false,
    "dump_game_options": false,
    "enable_debug": true,
    "gpu_memory_pool_fraction": 1.0,
    "memory_pool": true,
    "remove_pedestrians": false,
    "skip_start_menu": true,
    "smt": true,
    "spectre": false,
    "virtual_input": false
}
```
[cyber_engine_tweaks.zip](https://github.com/yamashi/CyberEngineTweaks/files/5733030/cyber_engine_tweaks.zip)

**Comment by antoninkriz** [comment]
Most of the time game's video freezes (audio still plays) and the game crashes crashes very soon after when opening the console. After the crash Cyberpunk's error reporting tool opens together with AMD Bug Report Tool with a following message:

![image](https://user-images.githubusercontent.com/15214494/103053565-04a2f280-459a-11eb-8bd9-0d8e4028526a.png)

Game: 1.06
Mod: 1.7.0 "1.06 patch support"
Mod settings: default
Video: borderless, no overlays (e.g. Steam, Radeon, ...) are enabled

[Cyberpunk2077-dump.zip](https://github.com/yamashi/CyberEngineTweaks/files/5737855/Cyberpunk2077-dump.zip)
