### ISSUE TITLE
Amend README to include SMT core warning/caveat. 

### ISSUE THREAD

**Issue by pm5k** [yamashi/CyberEngineTweaks#121]
Right now there’s claims that the SMT fix only affects up to 6-core processors, while 8-core ones reportedly either don’t benefit from this entirely or suffer worse performance. I suggest the readme should have a small section inside to reflect this. 

To reproduce one should do an end-to-end run in any reasonably populated area of NC like corpo plaza for instance on both a 6 core with identical graphics card and RAM and an 8 or more core processor. This should be reasonably enough to verify the claim.

**Comment by albin-engstrom** [comment]
I can on my end confirm that on a 3900X (12-cores) performance seems about the same after some quick testing.
But disabling the SMT fix does notably improve frametime evenness. I sometimes have notable spikes with the fix, and some general unevenness. But when I disable it the spikes are gone, and the general evenness is much better. 

So for me the fix does indeed do more harm than good.

Worth noting is that I am GPU-bound, at 98%+ usage most of the time with a 2080 Super. It's possible that if I was more CPU-bound the SMT fix might have performance benefits.

**Comment by skeevy420** [comment]
It also only effects Zen and up AMD CPUs due to using[ old GPUOpen code](https://hothardware.com/news/cyberpunk-2077-low-amd-performance-fix).

**Comment by RealTabman** [comment]
Just to make sure, this is about cores not threads, right?

**Comment by KsaRedFx** [comment]
I have a 3900X and I've pushed it to overclock, and the SMT fix is what actually caused my game to run significantly better. 
It's very dependent on if you are GPU or CPU bottlenecked, but with my 3080 I'm only ever at 30% utilization without the SMT fix.

**Comment by spitfire** [comment]
> I have a 3900X and I've pushed it to overclock, and the SMT fix is what actually caused my game to run significantly better.
> It's very dependent on if you are GPU or CPU bottlenecked, but with my 3080 I'm only ever at 30% utilization without the SMT fix.

Same here, but without overclock. It helped me with some noticeable drops, usage went from 30-40% to 40-70%

**Comment by markuznw** [comment]
> [AMD SMT] Optimized default core/thread utilization for 4-core and 6-core AMD Ryzen(tm) processors. 8-core, 12-core and 16-core processors remain unchanged and behaving as intended. This change was implemented in cooperation with AMD and based on tests on both sides indicating that performance improvement occurs only on CPUs with 6 cores and less.

From incoming 1.05 patch

**Comment by KsaRedFx** [comment]
I'm curious if it will actually help, because they've staged that it doesn't help with 8 or 12 core processors but the patch from this project helped me significantly, despite using a 12 core processor.

**Comment by PixelShake** [comment]
I believe that there's some confusion. From my own testing on a 8 core Ryzen 5800x, using the HEX editor version of the SMT fix, it is indeed correct that performance is negatively impacted much of the time (by about 10-20%), though it's worth noting that performance stability is generally still improved.

However, when instead using the SMT fix provided in this Performance Overhaul, I never experienced the degradation in performance whilst still reaping the benefits of more balanced core usage (better frame time consistency and CPU temps)
