### ISSUE TITLE
[Console] Tab button for autocomplete?

### ISSUE THREAD

**Issue by DartPower** [yamashi/CyberEngineTweaks#136]
Can you add the tab button for auto complete?

**Comment by yamashi** [comment]
It's probably doable I would need to dig a bit into the engine though, doubt I will find time soon.
Keeping this issue open to track and maybe get external contributions.

**Comment by DartPower** [comment]
Taken from CyberConsole mod.
[concmd.txt](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5718623/concmd.txt)
IDK how he get this. Maybe disasm or resources researched...

**Comment by JulianVolodia** [comment]
[kind of offtop]
hi @DartPower afaik for acknowledge of internal cmds you need to (for any game, app) static analysis of the libs.

Btw. this commands reffers to CyberConsole using intenfively original debug commands (correct me if I messed things completely :) ).
I.e. you cand run engine.forceHang, you need Lua CET API for that call. Docs are here.
https://wiki.cybermods.net/cyber-engine-tweaks/functions/
[/kind of offtop]

Going back to question - you mention tab on that commands yup?

If it helps you - if you select and paste commands (one under each) from text file to CET (with shift+Ins combo) then You press enter and `gotowe` (voila but PL)

**Comment by yamashi** [comment]
Won't support
