### ISSUE TITLE
[Overlay?] Game rendering works only in borderless & window

### ISSUE THREAD

**Issue by DartPower** [yamashi/CyberEngineTweaks#137]
Game rendering works only in borderless & window
In Fullscreen 0 fps on render (alt-tabbed last 1 frame), but another like engine, input & audio is works

**Comment by ipoopedmypantsuups** [comment]
I am getting the exact same issue here. I'll try that, thanks. In the meantime, try disabling console =)

**Comment by BCleverly** [comment]
I had this issue when i had auto_skip_start enabled, disabling that feature allowed fullscreen play

**Comment by hypoflex** [comment]
could be a corrupt driver as well.
For example I've seen a few instances of running GPU benchmarks after swapping card too many times driver is corrupt and can only run the benchmark in windowed

If above solutions do not resolve your issue try cleaning out the current driver with:
[https://www.guru3d.com/files-details/display-driver-uninstaller-download.html](url) 
and then freshly install the nvidia or amd driver from the website

**Comment by NielsGx** [comment]
Disable all overlays.
You could try to disable full screen optimization in the exe settings
