### ISSUE TITLE
Readme / wiki update

### ISSUE THREAD

**Issue by LittleZen** [yamashi/CyberEngineTweaks#172]
Can someone update the readme/wiki for correctly understand what the new features offer and what are they deafult values?

**Comment by extract** [comment]
All are false by default. The current fixes has a short description on each setting as well. What do you want from it?

**Comment by LittleZen** [comment]
i didn't found any description, can you pass me it ? I just wanna know what "disable_boundary_teleport" do 😅😅

**Comment by hulovexu1314** [comment]
> i didn't found any description, can you pass me it ? I just wanna know what "disable_boundary_teleport" do 😅😅

Delete the teleport caused by going beyond the boundary in the game

**Comment by Jeddunk** [comment]
`disable_intro_movies` ... Skips the logo/warning movie (it still plays in the background while the game is loading, but will be skipped to the intro cinematic when it's ready)
`disable_vignette` ... Removes vignette overlay (aka no "darkened border")

**Comment by emoose** [comment]
`enable_debug`/`unlock_menu` will also let you use debug teleport on map screen, but you need to edit `inputUserMappings.xml` file to bind the teleport button first, as explained at #145
To use it just open map screen, hover over a map icon and hold the teleport button (you can also set a waypoint and then teleport to waypoint icon too)

**Comment by LittleZen** [comment]
> `enable_debug`/`unlock_menu` will also let you use debug teleport on map screen, but you need to edit `inputUserMappings.xml` file to bind the teleport button first, as explained at #145
> To use it just open map screen, hover over a map icon and hold the teleport button (you can also set a waypoint and then teleport to waypoint icon too)

Hem ... i didn't really understad this features ... can you explain to me ?

**Comment by emoose** [comment]
Hm, not really sure how else to explain it...

With `enable_debug`/`unlock_menu` (and the inputUserMappings.xml file edited like #145 says), you can open map screen -> hover on icon -> hold down 'O' key on keyboard -> character will be teleported to the map icon.
Changes inside #145 are needed to set up the O key to work, unfortunately.

**Comment by yamashi** [comment]
I am going to need help documenting and updating the wiki, I think people should be able to make pull requests to it? I am not sure

**Comment by emoose** [comment]
Had a quick look on the wiki pages earlier but didn't see anything about editing/forking/etc, I guess there must be some way though, but only thing I've found so far is that wiki itself has a git repo at https://github.com/yamashi/PerformanceOverhaulCyberpunk.wiki.git :/

**Comment by ArturVRSampaio** [comment]
> I am going to need help documenting and updating the wiki, I think people should be able to make pull requests to it? I am not sure

yup, i already made one pull request, i`m kinda shy to do so because of my bad eng... but i will try to help today =D
