### ISSUE TITLE
Game "Freezes" when starting

### ISSUE THREAD

**Issue by CaptainJack710** [yamashi/CyberEngineTweaks#186]
After installing the mod on 1.05 my game just sorta freezes.
It alt+tabs and when i go into the game i see the first frame and nothing else. Also the inputs dont work or are very delayed.

I had none of these issues while playing on 1.04  

[2020-12-21 00:00:35.980] [info] Game version 1.5
[2020-12-21 00:00:36.030] [info] 	AMD SMT Patch: success
[2020-12-21 00:00:36.030] [warning] 	Spectre patch: failed, unknown version
[2020-12-21 00:00:36.044] [warning] 	Virtual Input Patch: failed
[2020-12-21 00:00:36.089] [info] 	Unlock menu patch: success
[2020-12-21 00:00:36.089] [info] 	Unlock debug functions: success
[2020-12-21 00:00:36.136] [info] 	Start screen patch: success
[2020-12-21 00:00:36.138] [info] 	Disable intro movies patch: success
[2020-12-21 00:00:36.178] [info] 	Hook mouse clip function!
[2020-12-21 00:00:36.210] [info] 	Log function hook complete!
[2020-12-21 00:00:36.523] [info] 	D3D12 hook complete

this is my most recent game log

Edit: I am playing on GOG

2nd edit: found the fix: just put "smt": false, into the options.json than it runs fine

**Comment by SaintTurtle** [comment]
How exactly do I find and open options.json (I have no idea what I'm doing :( sorry)

**Comment by NielsGx** [comment]
..\Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\config.json

btw it could be caused by "Start screen patch" or "Disable intro movies patch".
It's weird that disabling smt make it work.

btw it's version 1.05 not 1.5, but I have the same error.

**Comment by CaptainJack710** [comment]
I pulled this 1:1 from the temp cyber_engine_tweaks text doc and didnt change anything on Purpos. 

Start screen patch & intro movies patch both work fine for me 

SMT might cause problems bcs they changed the HEX values  as far as i know

**Comment by ipoopedmypantsuups** [comment]
Console=false. 
Unless you play in Windowed or Borderless windowed mode, you will have this bug in Fullscreen.

**Comment by CaptainJack710** [comment]
> Console=false.
> Unless you play in Windowed or Borderless windowed mode, you will have this bug in Fullscreen.

the problem accured no matter what value this setting was set to

**Comment by holysnipz** [comment]
> 2020-12-21 00:00:36.138] [info] Disable intro movies patch: success

maybe try set `disable_intro_movies` to false, since i have somewhat same problem with it

**Comment by ridewind** [comment]
change to window or  borderless can fix this problem
#137

**Comment by rdmurphy** [comment]
I was having this happen too and flagging `console=false` and `disable_intro_movies=false` worked for me. Unfortunately didn't try either one by itself so not sure which one did it. 🤔

**Comment by CaptainJack710** [comment]
Well it works now i just have to not touch my pc at all till i am in the main menu than it works with everything exept smt enabled

**Comment by Borobo729** [comment]
Just want to comment that just Console=false alone works for me.  The rest is default as it was.
