### ISSUE TITLE
The Console button is causing a CTD, unknown reason why.

### ISSUE THREAD

**Issue by Shilanas** [yamashi/CyberEngineTweaks#188]
Everytime I use the console button (~) it is an instant crash to desktop, unsure why at this point in time.

Only things installed are Reshade settings, and this performance overhaul. Debug menu is set to true.

Game version is GOG 1.5

**Comment by mgsallen** [comment]
> Everytime I use the console button (~) it is an instant crash to desktop, unsure why at this point in time.
> 
> Only things installed are Reshade settings, and this performance overhaul. Debug menu is set to true.
> 
> Game version is GOG 1.5

Same, just installed this and when hitting the console button, game instantly crashes. Any updates/suggestions?

**Comment by Code-You-Fools** [comment]
The debug console was allegedly removed in the latest hotfix (1.05, which I assume you mean, unless GOG uses different version numbers for some reason).

**Comment by mgsallen** [comment]
> The debug console was allegedly removed in the latest hotfix (1.05, which I assume you mean, unless GOG uses different version numbers for some reason).

Ah ok thank you for the information, I assume they are currently working on the fix. I will be patient then 👌

**Comment by Code-You-Fools** [comment]
Disregard my comment, I thought the mod was just drawing output for the console that existed up until 1.05. It appears to be creating its own console, which is working fine for me.

**Comment by bad1dea** [comment]
Make sure you do not have... RESHADE.. other than that, it works fine in Steam/GOG

**Comment by mgsallen** [comment]
> Make sure you do not have... RESHADE.. other than that, it works fine in Steam/GOG

Aww man, I have to remove reshade? I like my reshade 😢

**Comment by bad1dea** [comment]
Yes unfortunately right now the console is not compatible with reshade.

**Comment by mgsallen** [comment]
> Yes unfortunately right now the console is not compatible with reshade.

Sweet thanks for the info. So I just temporarily removed the Reshade dxgi.dll into a root folder. Accessed the console, got what from i needed from it "items" and just put the dxgi.dll back. Temporary win-win. Again thanks for your info and assistance!
