### ISSUE TITLE
Resolution changing broken when using mod

### ISSUE THREAD

**Issue by marcmicalizzi** [yamashi/CyberEngineTweaks#193]
Exactly as the title indicates. 
Unfortunately, right now cyberpunk is half broken with multi-monitor resolutions, but the workaround I've found is to change the resolution in UserSettings.json to something invalid, game starts at 1024x768, I then change the resolution to 11520x2160 (my native resolution) and 90% of things that don't work without doing these steps work at that point. Problem now, is with this mod installed, the screen resolution stays at 1024x768, however the game resolution changes to 11520x2160, so I'm stuck only being able to see the top 1024x768 of the screen. I've tried starting the game at 11520x2160, change resolution down to 1024x768 by memorizing the keypresses to do it, after which the screen resolution still hasn't changed and the 1024x768 rendered image is in a tiny top corner of my screen, and then changing back to 11520x2160, but unfortunately that doesn't fix the 90% of issues that I was fixing with the resolution changing in the first place.

**Comment by HysanDev** [comment]
Can confirm this, when alt-tabing, the game crash
