### ISSUE TITLE
about move command

### ISSUE THREAD

**Issue by zhanghack** [yamashi/CyberEngineTweaks#194]
please tell me
before player.teleport(X,Y,Z) or player.printPosition() what is it now thk.

**Comment by ipoopedmypantsuups** [comment]
I'd like to know this as well. I'd like a full documentation of all commands that are currently enterable with this new lua console.

**Comment by ArturVRSampaio** [comment]
> I'd like to know this as well. I'd like a full documentation of all commands that are currently enterable with this new lua console.

i never used the console, but the pc gamer made an article with some of the game commands.... how a said, i had never used it, so, not sure if it works, fell free to check it out.

https://www.pcgamer.com/cyberpunk-2077-cheats-pc/

**Comment by travisnewman** [comment]
Those worked for the old CyberConsole mod but don't work here
