### ISSUE TITLE
Not An Issue - Decided to Format Items for the Overlay 

### ISSUE THREAD

**Issue by Starlights-Smile** [yamashi/CyberEngineTweaks#198]
Took some time using a list I had already compiled to format it to work for the game's overlay for those interested. Things will be updated as I have more information for the items - if it's helpful.

https://docs.google.com/spreadsheets/d/1CCOmY__uhYhpRixs3XizqwUvx1LICqa2GrmyVpA2Nlc/edit?usp=sharing

**Comment by yamashi** [comment]
Would be nice to add the link to the wiki if you want to make a PR.

**Comment by Starlights-Smile** [comment]
You'll forgive me if I say, I have never used this site previous to even posting this link. Do what now? How can I help?
