### ISSUE TITLE
console code doesn't work

### ISSUE THREAD

**Issue by rebel1985** [yamashi/CyberEngineTweaks#200]
player.inventory.addItem(Items.money,1000)
doesn't work 
link where i hve from:
https://www.eurogamer.de/articles/cyberpunk-2077-cheats-geld-waffen-und-cyberware-bekommen

but have you a solution for the CMD?

**Comment by Racsan** [comment]
Noticed that the command doesn't work for me as well. It produces a lua error stating that the String is attempting to index a nil value (player).

**Comment by Racsan** [comment]
Nvm, found out that the command is different. 
Its "Game.AddToInventory("x", 1)".

**Comment by rebel1985** [comment]
but now what is the right comand?
Game.AddToInventory("x", 1)

what is x and what is 1 ?


Game.AddToInventory("50000", 1)  maybee?

**Comment by andreirawan97** [comment]
Maybe is x is item id.

**Comment by rebel1985** [comment]
what is for money?

**Comment by andreirawan97** [comment]
Have u tried? Game.AddToInventory(Items.money,99999)

**Comment by Racsan** [comment]
> but now what is the right comand?
> Game.AddToInventory("x", 1)
> 
> what is x and what is 1 ?
> 
> Game.AddToInventory("50000", 1) maybee?

Sub x for the item's String. I can't remember the Strings off the top of my head but I'm sure it's around somewhere. 

Idk what the 1 is for, but just leave it as 1. I tried other numbers and it doesn't work for me.

**Comment by andreirawan97** [comment]
https://cp77modding.gitbook.io/cyber-engine-tweaks/console/scripts

Game.AddToInventory("Items.money", 500)

**Comment by rebel1985** [comment]
it works fine
