### ISSUE TITLE
Using Comands

### ISSUE THREAD

**Issue by Slyger** [yamashi/CyberEngineTweaks#205]
I have 2 bugged quest guns. Skippy and Crash. I have completed their associated questlines but the yellow exclamation mark did not go away and I am unable to place it in my apartment stash for them to be shown on the wall. Is there any way to use the commands to remove this "Quest item" tag from the item. When I spawn in a new Crash gun ones using either 

Game.AddToInventory("Items.sq029_rivers_gun", 1)

or 

Game.AddToInventory("Items.Preset_Overture_River", 1)

The quest tag is still on the gun. Even though it shows that quest "sq029" is completed in the metadata of the save.

**Comment by Slyger** [comment]
Edit: it looks like for Skippy, the yellow quest marker goes away if i select "Im keeping you" instead of "ill take you back to regina"

**Comment by Fyter87** [comment]
Is their a command to finish a quest? I’m stuck on completing Cyber Pyschosis: Phantom of Night City, I did the mission awhile back and thought I had completed it, but now if I go back to the area everything is gone. I have the messages and shard with me, but it just won’t complete and I can’t send a message to Regina.
