### ISSUE TITLE
Disable (c|g)pu_memory_pool_fraction

### ISSUE THREAD

**Issue by azrinyi** [yamashi/CyberEngineTweaks#211]
Is it possible to disable _(c|g)pu_memory_pool_fraction_?

Currently, we supply a real number between 0 and 1 as parameter, but what if I do not want this value to be changed?
You could theoretically add the option to supply -1.0 which will be interpreted as do not use this option.

Thanks.

**Comment by yamashi** [comment]
This doesn't do anything anymore.
