### ISSUE TITLE
Console not showing

### ISSUE THREAD

**Issue by ArjanvdL** [yamashi/CyberEngineTweaks#213]
So I turned off anything that could be using an overlay (rivatuner, NZXT CAM) and I even remembered to turn off the GOG Galaxy overlay, but I still only see the mouse cursor when hitting the tilde button. 
Is there anything I missed?

cyberpunk version 1.05 on GOG

[2020-12-21 11:10:18.670] [info] Game version 1.5
[2020-12-21 11:10:18.702] [info] 	AMD SMT Patch: success
[2020-12-21 11:10:18.702] [warning] 	Spectre patch: failed, unknown version
[2020-12-21 11:10:18.714] [warning] 	Virtual Input Patch: failed
[2020-12-21 11:10:18.745] [info] 	Unlock menu patch: success
[2020-12-21 11:10:18.745] [info] 	Unlock debug functions: success
[2020-12-21 11:10:18.777] [info] 	Start screen patch: success
[2020-12-21 11:10:18.779] [info] 	Disable intro movies patch: success
[2020-12-21 11:10:18.802] [info] 	Hook mouse clip function!
[2020-12-21 11:10:18.819] [info] 	Log function hook complete!
[2020-12-21 11:10:19.006] [info] 	D3D12 hook complete

**Comment by Deklepek** [comment]
Same problem here

**Comment by ZeroMaki** [comment]
I have this too, its not showing.

**Comment by ArturVRSampaio** [comment]
dont know for sure, but from what i remember from reading the 1.05 patch notes, the console has been removed because of crashes

**Comment by ArturVRSampaio** [comment]
not sure if that is why, but here it is the patch notes

https://www.cyberpunk.net/en/news/37166/hotfix-1-05
`Removed debug console to prevent functions that could lead to crashes or blocked quests. This doesn't mean we don't want to support the modding community. Stay tuned for more info on that.`

**Comment by Hanaseria0** [comment]
Also have this problem. to open the console you use the END button right? did nothing for me

running the latest ver. steam
[2020-12-21 19:01:22.112] [info] Game version 1.5
[2020-12-21 19:01:22.248] [info] 	AMD SMT Patch: success
[2020-12-21 19:01:22.248] [warning] 	Spectre patch: failed, unknown version
[2020-12-21 19:01:22.288] [warning] 	Virtual Input Patch: failed
[2020-12-21 19:01:22.351] [info] 	Start screen patch: success
[2020-12-21 19:01:22.357] [info] 	Disable intro movies patch: success
[2020-12-21 19:01:22.395] [info] 	Hook mouse clip function!
[2020-12-21 19:01:22.422] [info] 	Log function hook complete!
[2020-12-21 19:01:22.704] [info] 	D3D12 hook complete

**Comment by Racsan** [comment]
Can confirm its still working on 1.05. I had to turn off everything (riva, afterburner, etc) that could block it. But it works.

**Comment by MrPapagenu** [comment]
I disabled the Steam overlay. That did it. Now it works.

**Comment by Deklepek** [comment]
I don't have any overlay (nvidia, steam or whatever) and it still does not work :/

**Comment by Lod3** [comment]
Try putting the game in full-screen borderless or windowed, and try opening the console again. This fixed some interactivity issues with the console window for me.

**Comment by class101** [comment]
For me the End key on Linux is not 192 but **35**, after this change in the config.json, console is showing up

**Comment by asrandor** [comment]
Same as OP, I can't get the console opening on 1.05 version, on GOG.
And I have the same warning in the logs : [warning] Virtual Input Patch: failed

**Comment by Hanaseria0** [comment]
somehow managed to get it work. now for my purpose to install this mod. how do you add items to your inventory. tried several strings but it shows as this: (for example I want to get back my satori)

here's my string input: player.inventory.addItem(Items.Preset_Katana_Saburo,1)
the console output: 
lua: error: [string "player.inventory.addItem(Ite..."]:1: attempt to index a nil value (global 'player')

**Comment by ArjanvdL** [comment]
Ok, I actually got it to work. Turns out that disabling the overlay in MSI afterburner was not enough. If I quit afterburner and run the game then the console actually works! Luckily, when the game is already running I can then start afterburner again because I need it for my gpu fancurve, without it breaking the console!
For all the ppl still having trouble, try and troubleshoot by killing all programs that may be still using an overlay even if you disabled it

**Comment by ArjanvdL** [comment]
Ok, I actually got it to work. Turns out that disabling the overlay in MSI afterburner was not enough. If I quit afterburner and run the game then the console actually works! Luckily, when the game is already running I can then start afterburner again because I need it for my gpu fancurve, without it breaking the console!
For all the ppl still having trouble, try and troubleshoot by killing all programs that may be still using an overlay even if you did disabled it.

**Comment by Racsan** [comment]
> somehow managed to get it work. now for my purpose to install this mod. how do you add items to your inventory. tried several strings but it shows as this: (for example I want to get back my satori)
> 
> here's my string input: player.inventory.addItem(Items.Preset_Katana_Saburo,1)
> the console output:
> lua: error: [string "player.inventory.addItem(Ite..."]:1: attempt to index a nil value (global 'player')
> 
> did I put the string in a wrong format or something else?

Its Game.AddToInventory("x",1).
