### ISSUE TITLE
How would I go about deleting an item from my inventory?

### ISSUE THREAD

**Issue by svfeplvce** [yamashi/CyberEngineTweaks#219]
Simply put, I just want to delete a few items that I can't sell or store.

**Comment by impoint** [comment]
Yes, I found that some of the added items cannot be sold or discarded.

**Comment by CIKOMELANTIK** [comment]
i would like to know abt this too

i tried to add with -1 as the quantity but it didnt delete it

**Comment by glowinthedarkninja** [comment]
You could use ~RemoveItem(itemID, Count)~ with the console I had before. If I understand things correctly the dev of that console has his work used in some part of this project. I used this to remove a couple of things from my inventory. The one item I wanted removed, the thruster boots, could not be removed from my character though. They also cannot be unequiped.

**Comment by xunknxwnx** [comment]
> You could use ~RemoveItem(itemID, Count)~ with the console I had before. If I understand things correctly the dev of that console has his work used in some part of this project. I used this to remove a couple of things from my inventory. The one item I wanted removed, the thruster boots, could not be removed from my character though. They also cannot be unequiped.

That was with the old console, this one is a bit different. Thank you, though. I just hope I can figure this out haha.

**Comment by Rorschach1219** [comment]
> 
> 
> You could use ~RemoveItem(itemID, Count)~ with the console I had before. If I understand things correctly the dev of that console has his work used in some part of this project. I used this to remove a couple of things from my inventory. The one item I wanted removed, the thruster boots, could not be removed from my character though. They also cannot be unequiped.

In the latest version, what command is used to delete equipment?

**Comment by Who-42** [comment]
i would also like to know the command for deleting items :)
