### ISSUE TITLE
Issues in console

### ISSUE THREAD

**Issue by atis2345** [yamashi/CyberEngineTweaks#222]
Hi all.
When I do input `player.inventory.addItem(Items.money,1000)` or any other commands in console I see next issue.
`lua: error: [string "player.inventory.addItem(Ite..."]:1: attempt to index a nil value (global 'player')`.

Steam, v1.05

**Comment by SkebbZ** [comment]
Read the wiki, the command is different now

**Comment by Hanaseria0** [comment]
is it the game.AddToInventory or game.AddItems one?

**Comment by atis2345** [comment]
Input: `Game.AddItems(Items.money,1000)`
Result: `lua: error: [string "Game.AddItems(Items.money,10..."]:1: attempt to index a nil value (global 'Items')`

Input: `Game.AddToInventory(Items.money,1000)`
Result: `lua: error: [string "Game.AddToInventory(Items.mo..."]:1: attempt to index a nil value (global 'Items')`

**Comment by atis2345** [comment]
In the top of console:
```
InitializeScripts
WeaponPositionComponent: Attach
[ASSERT] [EquipmentSystem::GetPlayerData] Unable to find player data!
[ASSERT] [EquipmentSystem::GetPlayerData] Unable to find player data!
[ASSERT] [EquipmentSystem::GetPlayerData] Unable to find player data!
[ASSERT] [EquipmentSystem::GetPlayerData] Unable to find player data!
[ASSERT] [EquipmentSystem::GetPlayerData] Unable to find player data!
[ASSERT] [PlayerDevelopmentSystem::GetDevelopmentData] Unable to find player data!
[ASSERT] [PlayerDevelopmentSystem::GetDevelopmentData] Unable to find player data!
[DevelopmentManager] GetProficiencyIndexByType(): No proficiency found! Return value equals -1!
[DevelopmentManager] GetProficiencyIndexByType(): No proficiency found! Return value equals -1!
[DevelopmentManager] GetProficiencyMaxLevel(): Proficiency of given type doesn't exist!! Return value equals -1 !!
[DevelopmentManager] GetProficiencyIndexByType(): No proficiency found! Return value equals -1!
```

```
{
    "avx": true,
    "console": true,
    "console_key": 192,
    "cpu_memory_pool_fraction": 0.5,
    "disable_antialiasing": false,
    "disable_async_compute": false,
    "disable_boundary_teleport": false,
    "disable_intro_movies": true,
    "disable_vignette": false,
    "dump_game_options": false,
    "enable_debug": false,
    "gpu_memory_pool_fraction": 1.0,
    "memory_pool": true,
    "remove_pedestrians": false,
    "skip_start_menu": true,
    "smt": true,
    "spectre": true,
    "virtual_input": true
}
```

**Comment by Hanaseria0** [comment]
> Input: `Game.AddItems(Items.money,1000)`
> Result: `lua: error: [string "Game.AddItems(Items.money,10..."]:1: attempt to index a nil value (global 'Items')`
> 
> Input: `Game.AddToInventory(Items.money,1000)`
> Result: `lua: error: [string "Game.AddToInventory(Items.mo..."]:1: attempt to index a nil value (global 'Items')`

for injecting money. try this: `Game.AddToInventory("Items.money",amount)`
change the amount to your desire

**Comment by atis2345** [comment]
> > Input: `Game.AddItems(Items.money,1000)`
> > Result: `lua: error: [string "Game.AddItems(Items.money,10..."]:1: attempt to index a nil value (global 'Items')`
> > Input: `Game.AddToInventory(Items.money,1000)`
> > Result: `lua: error: [string "Game.AddToInventory(Items.mo..."]:1: attempt to index a nil value (global 'Items')`
> 
> for injecting money. try this: `Game.AddToInventory("Items.money",amount)`
> change the amount to your desire

Thank you. Now it works!
