### ISSUE TITLE
v131 - d3d12.dll is missing

### ISSUE THREAD

**Issue by sumyunggai** [yamashi/CyberEngineTweaks#223]
Jumped from v081 to v131 and now get this error upon launch. Did a fresh reinstall of the game w/ 1.05 and it still persists. Win7 x64, no issues prior to v131, and CPv1.05 throws no errors booting w/o the overhaul present. 

edit: found the version that broke it (on my system) - starting with v1.0.0 (https://github.com/yamashi/CyberEngineTweaks/releases/tag/v1.0.0), I get this error and thus the plugin doesn't load and none of the settings take effect. v0.10.0 and prior don't have this problem.

**Comment by puchev** [comment]
See #134

**Comment by ArturVRSampaio** [comment]
win 7 support seems buggy :/

**Comment by sumyunggai** [comment]
> 
> 
> See #134

Thanks, rrrud's steps work for me ([link](https://github.com/yamashi/CyberEngineTweaks/issues/134#issuecomment-748824832)).
