### ISSUE TITLE
Secret Ending

### ISSUE THREAD

**Issue by maxkoshe5** [yamashi/CyberEngineTweaks#225]
It would be great if console somehow allowed the ability to get secret ending without replaying whole game from scratch.

**Comment by Simzy** [comment]
All the commands what you can use are what have been dumped from the game engine, this mod has no control over things like that, it just allows you to use the commands that are available.

**Comment by bad1dea** [comment]
From Discord.

 Nifnat: Game.SetDebugFact("sq032_johnny_friend", 1)

Unlocks secret ending
