### ISSUE TITLE
CONTINUES CRASH EVERY 5 MINUTES WITH 1.05 CODEX VERSION

### ISSUE THREAD

**Issue by Jordan1777777** [yamashi/CyberEngineTweaks#227]
Before this patch i never had crashes in the game. Now i crash every 5 minutes. This mod can fix It? There's a way to fix It? A lot of people have the same issues with this version. 

PLEASE ANGELS HELP US :(

**Comment by Jordan1777777** [comment]
Why you close???

**Comment by Jordan1777777** [comment]
I'm being mad with this game i try all please give me an answer

**Comment by yamashi** [comment]
No support for piracy.
