### ISSUE TITLE
Game won't start at all.

### ISSUE THREAD

**Issue by DevilSam96** [yamashi/CyberEngineTweaks#232]
The game won't start, he tryes but won't open at all, i have to kill the process.
On the log 
`[2020-12-21 20:15:48.422] [info] Game version 1.05
`

**Comment by b-zhang93** [comment]
happens to me too. Started since 1.05, nothing has been updated to fix this except more tweaks. I would look into some other more performance oriented mods rather than cheat oriented like this one if you guys want to just improve FPS

**Comment by ArturVRSampaio** [comment]
> The game won't start, he tryes but won't open at all, i have to kill the process.
> On the log
> `[2020-12-21 20:15:48.422] [info] Game version 1.05 `

GoG or Steam game? witch is your SO? the game works without the mod? if you already had a old mod version, had you deleted the x64 and downloaded it again before updating the mod?

**Comment by DevilSam96** [comment]
> > The game won't start, he tryes but won't open at all, i have to kill the process.
> > On the log
> > `[2020-12-21 20:15:48.422] [info] Game version 1.05 `
> 
> GoG or Steam game? witch is your SO? the game works without the mod? if you already had a old mod version, had you deleted the x64 and downloaded it again before updating the mod?

Steam Version.
Windows 10 64bit, latest vers.
Game works without mod, vers 1.5.
I downloaded the latest version on ModNexus

**Comment by ArturVRSampaio** [comment]
well, i'm not a specialist, but try using the mod from git or a older mod version

**Comment by ArturVRSampaio** [comment]
I'm not sure if the nexus is always updated

**Comment by glukianets** [comment]
For me it was bad `console_key` setting
