### ISSUE TITLE
Game.PrintAttributes causes CTD.

### ISSUE THREAD

**Issue by willuwontu** [yamashi/CyberEngineTweaks#233]
Using the console command `Game.PrintAttributes()` causes the game to crash in 1.4.1.

Reverting back to 1.3.1 fixes this, so it must be something introduced by the addition of handling handles.

**Comment by yamashi** [comment]
I am not sure what you mean I just tried and it seem to be working fine

**Comment by willuwontu** [comment]
IDK why it works for you, I just tried it again, and it crashed once more. The other commands seem to work fine though.

**Comment by willuwontu** [comment]
1.4.2 Somehow lets it work for me.
