### ISSUE TITLE
Enable Secret Ending

### ISSUE THREAD

**Issue by AB110297** [yamashi/CyberEngineTweaks#234]
Do you guys think its possible to enable the secret ending manually using the dev console ? or do you know of any modding efforts to make the secret ending easily available for people who dont want to replay the whole game again just to get that ending ? 

Happy Holidays and thanks for the great work 👍

**Comment by rmarquis** [comment]
Duplicate of #225.

**Comment by bad1dea** [comment]
I posted a copy and paste from discord with answer.
