### ISSUE TITLE
Unflagging Quest Items so people can sell/store things.

### ISSUE THREAD

**Issue by Sleetzer** [yamashi/CyberEngineTweaks#235]
There's a console command called Game.SetQuestWeaponState(weaponState) but i'm not sure that's exactly what were looking for. This would help a lot of people, if there was a more in-depth way to unflag quest items.

For example: Crafting the Epic tier of any of the Johnnys Clothes leaves behind the original Rare tier (which just takes up space in your inventory) and you can craft an unlimited amount of higher-tiered replicas if you are looking for RNG. Crash and Amnesty are also always flagged as Quest Items. Crash (River's Overture), and Amnesty (Cassidy's Revolver) from Panam ending.

**Comment by bloodaxis** [comment]
https://github.com/PixelRick/CyberpunkSaveEditor and https://github.com/WolvenKit/CyberCAT can both unflag items, and delete them if that's what you want.
