### ISSUE TITLE
Alt-tabbing caused CTD

### ISSUE THREAD

**Issue by HysanDev** [yamashi/CyberEngineTweaks#236]
WIth console disabled, when I alt-tab, it immediately crashes the game, no matter in menu or in game

**Comment by TrapStoner** [comment]
Same here with 1.4.1 on 1.05 causes the game to flatline when alt-tabbing. Also on start i don't see the project red and red engine intros, but i can hear them. Idk if that's intentional.

**Comment by HysanDev** [comment]
> Same here with 1.4.1 on 1.05 causes the game to flatline when alt-tabbing. Also on start you don't see the project red and red engine intros when disabled, but you can hear them. Idk if that's intentional.
> 
> Also console doesn't matter for me it still CTD when console is enabled

Engine intros is probably disabled in config.json intentionally, and yes just confirmed even with console enabled, alt-tabbing still resulted in crash to desktop

**Comment by boboben1** [comment]
Try disabling Focus Assist in Windows.

**Comment by TrapStoner** [comment]
Yes intros are disabled i said it in my first post, but i thought it would disable the sounds of them too. Also Focus Assist did nothing it still crashes with version 1.7.0
