### ISSUE TITLE
crash/ game is completely broken because of the mod

### ISSUE THREAD

**Issue by ddylard** [yamashi/CyberEngineTweaks#238]
After updating to latest AMD driver 20.12.1 all versions of the program (even the old ones stopped working). At that moment if i took out the files from the mod the game would run normally...
Now i have a much worse problem... As i wanted the mod on win 7 i followed the steps recommended on the "windows7 support" issue and put d312to7 files on plugins folder , along with the dxinput_3.dll renamed to dxinput_4.dll.

Now my game is completely broken an refuses to startup everytime even if i took out every mod file. Pleas yamashi could you help me somehow?

reverted back to 20.7.2 amd drivers and still same problem.

**Comment by ddylard** [comment]
this is my lates dmpp crash  file just take the.zip part out. thanks!
[Cyberpunk2077.dmp.zip](https://github.com/yamashi/CyberEngineTweaks/files/5727490/Cyberpunk2077.dmp.zip)

**Comment by rrrudd** [comment]
I don't think it's drives related problem - I updated drivers to 20.12.1 shortly after game release. Maybe you messed up game files - did you copied or moved d3d12.dll and xinput1_3.dlll files? Try to reinstall game - before that, you may try to delete game settings located in `C:\Users\USER\AppData\Local\CD Projekt Red\Cyberpunk 2077`.

**Comment by yamashi** [comment]
Windows 7 is not supported closing.

**Comment by ddylard** [comment]
Well thanks. I reinstalled the game and got it working again. I guess i wont ve using this mod anymore. Sadly...
