### ISSUE TITLE
opening command console causes a crash

### ISSUE THREAD

**Issue by VrorserEzdekai** [yamashi/CyberEngineTweaks#240]
my game version is v1.05 GOG
I installed following directions

so I got no clue why it's crashing unless it's to do with the spectre patch failing
heres the crash report and tweak log
[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/5727946/cyber_engine_tweaks.log)

[Cyberpunk2077-20201222-130902-7408-22020.zip](https://github.com/yamashi/CyberEngineTweaks/files/5727947/Cyberpunk2077-20201222-130902-7408-22020.zip)

**Comment by bad1dea** [comment]
Do you have reshade?

**Comment by VrorserEzdekai** [comment]
yeah

**Comment by VrorserEzdekai** [comment]
`yeah uninstalled reshade it works now wtf
