### ISSUE TITLE
Guide Improvement: Game.GetPlayer() returns Error: Function 'GetPlayer' not found or is not a global - because game needs to be run as admin.

### ISSUE THREAD

**Issue by oloffl** [yamashi/CyberEngineTweaks#242]
I was about to post an issue about not being able to run Game.GetPlayer(), but I set the game to run as admin because of a hunch, which now allows me to run that command. So this issue is now instead just a suggestion to add that information in the script tutorial/releases 😃

**Comment by yamashi** [comment]
Is this with 1.4.2?

**Comment by oloffl** [comment]
Yes, and 1.0.5

**Comment by gibbed** [comment]
Admin isn't required and shouldn't be. You have something strange with your setup.

**Comment by oloffl** [comment]
I saw in the release notes that a fix relating to autoexec.lua not running when starting the game from the launcher, seems likely that my problem what related to that rather than running as admin.
