### ISSUE TITLE
Rivatuner equivalent

### ISSUE THREAD

**Issue by Primordiarch** [yamashi/CyberEngineTweaks#245]
So, using Rivatuner OSD will prevent the GUI to appear. Is there any other software that does the same thing but not blocking the GUI?

Thank you.

**Comment by ArturVRSampaio** [comment]
show fps? i think u can use the steam fps counter

**Comment by LittleZen** [comment]
@ArturVRSampaio 

RiviaStatistics allow you to show more information than fps (like temps, workloads, cpu load, mem usage ...)

**Comment by Primordiarch** [comment]
> show fps? i think u can use the steam fps counter

Yes, I need not only fps counter but also stats like GPU Util, GPU Temp, CPU Util, CPU temp, etc.

**Comment by LittleZen** [comment]
@Primordiarch when you talking about "preventing GUI to appear" are you talking about the console? If yes, have you tried to change the default button?

**Comment by ArturVRSampaio** [comment]
> @ArturVRSampaio
> 
> RiviaStatistics allow you to show more information than fps (like temps, workloads, cpu load, mem usage ...)

well, i remember seeing something like that when i was looking for a equivalent on linux side... i will take a look

**Comment by LittleZen** [comment]
@Primordiarch 

https://fpsmon.com/en/

i didn't try it, but it could be useful !

**Comment by ArturVRSampaio** [comment]
https://alternativeto.net/software/fps-monitor/ https://fpsmon.com/en/? maybe this?

**Comment by ArturVRSampaio** [comment]
> @Primordiarch
> 
> https://fpsmon.com/en/
> 
> i didn't try it, but it could be useful !

dam, faster than me ahhahah

**Comment by LittleZen** [comment]
@ArturVRSampaio 

2 options are better than one ! 🦾🦾🦾

**Comment by Primordiarch** [comment]
> @Primordiarch when you talking about "preventing GUI to appear" are you talking about the console? If yes, have you tried to change the default button?

Did you mean to change the console's default key from " ` " to something else?

**Comment by LittleZen** [comment]
@Primordiarch 
it was just a test... i believe you can fix it by using other application shared with you up there

**Comment by JReming85** [comment]
MSI afterburner with hwinfo plugin

**Comment by Primordiarch** [comment]
Really? I thought HWInfo uses rivatuner too.

**Comment by SztifelsoN** [comment]
Hi!

To make the console work with RivaTuner, for example in Notepad ++, edit the Global file, which is located in x: \ Program Files (x86) \ RivaTuner Statistics Server \ ProfileTemplatesand add "cyber_engine_tweaks.asi" to the end of the decimal in the line:

`InjectionDelayTriggers`

[IMAGE](https://imgur.com/a/mmd0n1R) 

Sorry for my english (google translate).

**Comment by WSSDude420** [comment]
Worked for me, thanks @SztifelsoN !

But tbh, it is kinda weird that this is required. [https://github.com/praydog/RE2-Mod-Framework](RE2 Mod Framework) works flawlessly for me, and it uses ImGui for its UI too. Also hooks and stuff... 

Something must be done wrongly from side of this project I believe.

**Comment by Primordiarch** [comment]
> Hi!
> 
> To make the console work with RivaTuner, for example in Notepad ++, edit the Global file, which is located in
> `x:\Program Files(x86)\RivaTuner Statistics Server\ProfileTemplates` and add `cyber_engine_tweaks.asi` to the end of the decimal in the line:
> 
> `InjectionDelayTriggers`
> 
> [IMAGE](https://imgur.com/a/mmd0n1R)
> 
> Sorry for my english (google translate).

Thanks, it worked but I decided to buy fpsmonitor.

Thanks also @LittleZen

**Comment by JReming85** [comment]
> Really? I thought HWInfo uses rivatuner too.

It does all 3 RivaTuner/MSI Afterburner/EVGA Precision On-Screen Display

**Comment by WSSDude420** [comment]
Dont know why this is open too :P
