### ISSUE TITLE
[Suggestion] Mute the "news" during loading

### ISSUE THREAD

**Issue by Eymiks** [yamashi/CyberEngineTweaks#246]
I find the news during loading very annoying. Moreover, it changes very rarely. 
So, if it's possible, I think it would be nice to be able to disable them.

Thanks.

**Comment by Xanoreus** [comment]
> I find the news during loading very annoying. Moreover, it changes very rarely.
> So, if it's possible, I think it would be nice to be able to disable them.
> 
> Thanks.

It changes based on main story progression. It is meant as a placeholder while the game is loading. If it was editable, would a black screen suffice? Either way, you will be waiting.

**Comment by RedEyedRocker** [comment]
> 
> 
> I find the news during loading very annoying. Moreover, it changes very rarely.
> So, if it's possible, I think it would be nice to be able to disable them.
> 
> Thanks.

Switch from HDD to SSD and loading times will be so fast that you won't have to listen to those news.

**Comment by arwent** [comment]
> > I find the news during loading very annoying. Moreover, it changes very rarely.
> > So, if it's possible, I think it would be nice to be able to disable them.
> > Thanks.
> 
> Switch from HDD to SSD and loading times will be so fast that you won't have to listen to those news.

Give him an SSD so.

**Comment by RedEyedRocker** [comment]
> 
> 
> > > I find the news during loading very annoying. Moreover, it changes very rarely.
> > > So, if it's possible, I think it would be nice to be able to disable them.
> > > Thanks.
> > 
> > 
> > Switch from HDD to SSD and loading times will be so fast that you won't have to listen to those news.
> 
> Give him an SSD so.

It's an advice, take it or leave it.
This is coming from a person who recently made the switch and the difference it makes in the loading times is just significantly better and saves so much time that you'd otherwise waste minutes waiting in the loading screen.
