### ISSUE TITLE
Console commands to add item not working

### ISSUE THREAD

**Issue by Zyphinex** [yamashi/CyberEngineTweaks#247]

**Comment by Zyphinex** [comment]
I entered the sequence to add an item directly copy pasted from the hash list and it says "parameter 0 must be ScriptGameInstance"

**Comment by Kyle873** [comment]
Make sure you are running the latest build. I believe that issue was fixed quite a while ago.

**Comment by bad1dea** [comment]
Make sure you're using the right command, please post more details when reporting issues.

Game.AddToInventory("ItemName", 1)

**Comment by Zyphinex** [comment]
I used these:
Game.AddToInventory("Items.Preset_Copperhead_Genesis", 1)
Game.AddToInventory("Items.Recipe_Preset_Copperhead_Genesis", 1)
And another one I can't remember exactly the name

**Comment by Zyphinex** [comment]
Got it to work after redownloading the mod again
