### ISSUE TITLE
What are the commands?

### ISSUE THREAD

**Issue by unfofafj** [yamashi/CyberEngineTweaks#250]
I used the format Game.AddToInventory("ItemName", 1) and it does not work, I am not really a programmer but I know how to set it up but now I have no clue how to get what I need/want. Help needed.

**Comment by Venetas** [comment]
Check out [this spreadsheet](https://docs.google.com/spreadsheets/d/1CCOmY__uhYhpRixs3XizqwUvx1LICqa2GrmyVpA2Nlc/)

**Comment by AcesGamingUK** [comment]
> I used the format Game.AddToInventory("ItemName", 1) and it does not work, I am not really a programmer but I know how to set it up but now I have no clue how to get what I need/want. Help needed.
#224
