### ISSUE TITLE
[Request] Noclip Function or Command

### ISSUE THREAD

**Issue by MdosTV** [yamashi/CyberEngineTweaks#254]
I've tried looking in a lot of different places and there doesn't seem to be a Noclip command left in the game. I've looked for alternatives and all I can find are some sketch mods. I was wondering if you had plans to add this to the mod.

Thank you for the great mod thus far!

**Comment by ArturVRSampaio** [comment]
i need it too... i want to know whats on the locked room at the afterlife

**Comment by JReming85** [comment]
only one available is this 
https://github.com/hoiblij/cyberpunknoclip/tree/main/Cyberpunk%20trainer/Cyberpunk%20trainer

made for 1.04 but still works

**Comment by MdosTV** [comment]
Yeah saw that. I saw mixed reviews on that one and it doesn't have a lot traffic right now. Seems like it could be sketch. Not sure if I trust it quite yet.

**Comment by WSSDude420** [comment]
I started looking into this already, have some idea how it could be done already, just need to get around to try to implement it fully and test it.

**Comment by JReming85** [comment]
> I started looking into this already, have some idea how it could be done already, just need to get around to try to implement it fully and test it.

Cant wait for it to get completed.



> Yeah saw that. I saw mixed reviews on that one and it doesn't have a lot traffic right now. Seems like it could be sketch. Not sure if I trust it quite yet.

I can vouch it is safe, ran it through my cuckoo sandbox and found nothing malicious.  No internet communication, no dropped files, no vm detection or antivm functions.  Strings were fine, etc.

But it is your choice on whether you want to use it or wait for something better.

**Comment by seifer7** [comment]
@JReming85 
> only one available is this
> https://github.com/hoiblij/cyberpunknoclip/tree/main/Cyberpunk%20trainer/Cyberpunk%20trainer
> 
> made for 1.04 but still works

@MdosTV 
> Yeah saw that. I saw mixed reviews on that one and it doesn't have a lot traffic right now. Seems like it could be sketch. Not sure if I trust it quite yet.

Just read through the coding on that trainer, **it is perfectly safe.**
