### ISSUE TITLE
[Crash] Games crashes on press of tilda key

### ISSUE THREAD

**Issue by Creativious** [yamashi/CyberEngineTweaks#257]
I followed the instructions on this website https://wiki.cybermods.net/cyber-engine-tweaks/ and everything works until I press the tilda key crashing my game. No overlay software running either.

**Comment by Kyle873** [comment]
Are you using Reshade?

**Comment by NumberXer0** [comment]
Same here. Using Reshade. They worked together fine before.
Any way to have them both functional? Reshade is basically a requirement to remove blur..
