### ISSUE TITLE
[SCRIPTING] [QUESTION] How to set Attribute/Perk points?

### ISSUE THREAD

**Issue by dankadank** [yamashi/CyberEngineTweaks#258]
I am wondering how to set attribute points and perk points through the Lua API.

**Comment by gibbed** [comment]
```lua
Game.GiveDevPoints('Attribute', 1337)
Game.GiveDevPoints('Primary', 1337)
```

**Comment by dankadank** [comment]
> ```lua
> Game.GiveDevPoints('Attribute', 1337)
> Game.GiveDevPoints('Primary', 1337)
> ```

thanks dude you're L33t
