### ISSUE TITLE
Spectre patch: failed, unknown version

### ISSUE THREAD

**Issue by BlueDevil** [yamashi/CyberEngineTweaks#261]
Always fails to apply the patch with my current CPU. Got enough reasons to upgrade my i7 2700k ASAP, but for now I'd at least like to squeeze out everything possible out of it :)

**Comment by TonyRL** [comment]
See https://github.com/yamashi/CyberEngineTweaks/issues/155#issuecomment-749126779
> 
> 
> > why Spectre patch fails?
> > I'm sorry for asking, I'm sure many of us have the same problem, we just want to be aware that the developer of this tool is solving it, thank you very much
> 
> It fails because the memory addresses of the trampolines etc this mod patches has changed due to the update. The new memory addresses have to be found before the patch can be re-applied properly.
> 
> There are over [34k addresses](https://github.com/yamashi/CyberEngineTweaks/blob/master/src/spectre_patch_1_4.cpp#L9) which need patched/evaluated so it may take a while to find them again.

**Comment by yamashi** [comment]
The sources for the spectre patch generation are here: https://github.com/yamashi/SpectreAway/
Still need to be updated for 1.05
