### ISSUE TITLE
Question about Memory Pool Budgets and versions 1.05/+

### ISSUE THREAD

**Issue by DarthJahus** [yamashi/CyberEngineTweaks#262]
In 1.05 version notes, we can read:

> Removed the memory_pool_budgets.csv file. which was not connected with the final version of the game and had no influence on it (it was a leftover file used during the development to estimate memory usage. It had no effect on how much memory was actually allocated). Perceived performance increase after editing the file may have been related to restarting the game.

Was CyberEngineTweaks changing that file? Or changing something in the game itself? Do we know if that part of the patch really works? I haven't seen any discussion about it, here.

**Comment by holysnipz** [comment]
Not the dev themself but i think i can give you some answer...

> Was CyberEngineTweaks changing `memory_pool_budgets.csv` file?

[obviously not](https://github.com/yamashi/CyberEngineTweaks/blob/5d074ce6d0b32e2717eb1502be6c14acf749b729/src/pool_patch.cpp#L82) 

> changing something in the game itself

Yes

> Do we know if that part of the patch really works?

i still doubt this too, but since people said it work. So... idk

**Comment by NielsGx** [comment]
I saw someone saying that the game was actually reading the csv file, and parsing values from it...

tbh it wouldn't be surprising that CDPR did a huge mistake with this file, and they have fixed it now, under the hood...

**Comment by WSSDude420** [comment]
This can be closed I believe @yamashi
