### ISSUE TITLE
[REQUEST] Fix missing sounds, because CDPR can't

### ISSUE THREAD

**Issue by IgorEisberg** [yamashi/CyberEngineTweaks#263]
Hey mate. This issue is out of my expertise and C++ and Assembly are beyond my understanding at this point, as I'm dealing with high-level languages mostly. This sound issue has been plaguing a lot of players, and is somehow connected to Sound "Enhancements" having to be enabled for the audio endpoint on many audio codecs (mostly Realtek, but others as well).

Missing sounds like music (clubs and radio), NPC interactions (when they reply something, text above them shows and their lips move, but no speech), gunshots and explosions, etc.
Proton has been facing this [issue](https://github.com/ValveSoftware/Proton/issues/4450#issuecomment-742229069) since they introduced support for CP2077, but they managed to fix this: "Implemented the Spatial Audio sound API, fixing Cyberpunk 2077 world sounds."
https://github.com/ValveSoftware/Proton/wiki/Changelog#available-in-proton-experimental

Sadly on Windows this isn't the solution. Whether Spatial sound is enabled or disabled, the sounds will be missing until "Disable all enhancements" (aka "Disable All Sound Effects" in Realtek Audio Console/Control") is toggled off **and** the Audio Service is restarted or the PC restarted (mandatory to take effect).
This workaround can be applied manually ([registry editing](https://forums.cdprojektred.com/index.php?threads/sound-issues.11040671/post-12477605)) and by tools like "[FX Configurator](https://forums.cdprojektred.com/index.php?threads/sound-issues.11040671/post-12510353)", if the toggle is not available for a specific sound card/chip.

This isn't a great solution, as sound effects are not always desirable.
I tried using hooks like "DirectSound Control", but looking at the loaded modules shows that "dsound.dll" isn't used by CP2077, which means the sound engine probably uses WASAPI directly, and that complicates things.

Will be grateful for any insights you might have.

**Comment by ipoopedmypantsuups** [comment]
Blame their buggy shite engine
