### ISSUE TITLE
Delete Item With Console Commands?

### ISSUE THREAD

**Issue by Rorschach1219** [yamashi/CyberEngineTweaks#264]
i'm looking how to delete item from inventory and i found a functrion that seems to work but make my game crash tho i don't know the parameter of the las 2 param 

player = Game.GetPlayer()
ts = Game.GetTransactionSystem()

result = ts:RemoveItem(player, PARAM2, PARAM3)
if result then
    print("We del ")
else
    print("Failed to del ")
end

**Comment by xunknxwnx** [comment]
The second parameter is probably the item, and PARAM3 is most likely count.

**Comment by yamashi** [comment]
public native function RemoveAllItems(obj : ref:GameObject) : Bool;
  public native function RemoveItem(obj : ref:GameObject, itemID : ItemID, amount : Int32) : Bool;
  public native function RemoveItemByTDBID(obj : ref:GameObject, tdbID : TweakDBID, amount : Int32) : Bool;

So it would be something like


itemid = TweakDBID.new("Item.name")
ts:RemoveItemByTDBID(Game.GetPlayer(), itemid, 1)

**Comment by Rorschach1219** [comment]
> 
> 
> public native function RemoveAllItems(obj : ref:GameObject) : Bool;
> public native function RemoveItem(obj : ref:GameObject, itemID : ItemID, amount : Int32) : Bool;
> public native function RemoveItemByTDBID(obj : ref:GameObject, tdbID : TweakDBID, amount : Int32) : Bool;
> 
> So it would be something like
> 
> itemid = TweakDBID.new("Item.name")
> ts:RemoveItemByTDBID(Game.GetPlayer(), itemid, 1)

![图片](https://user-images.githubusercontent.com/20067002/103057855-a565d200-45db-11eb-9f5c-e75d1da7a2a9.png)

**Comment by willuwontu** [comment]
RemoveItemByTDBID seems to not work for quest items, I can confirm that it works for money and for MK bounce backs though.

**Comment by Rorschach1219** [comment]
> 
> 
> RemoveItemByTDBID seems to not work for quest items, I can confirm that it works for money and for MK bounce backs though.
> 
> My Script version of it
> 
> ```lua
> local ts = Game.GetTransactionSystem()
> local result = ts:RemoveItemByTDBID(Game.GetPlayer(), TweakDBID.new(itemname), 1)
> print(tostring(result))
> ```

I only tried money, which really worked, but I wanted to remove mission items or props

**Comment by willuwontu** [comment]
InventoryManager seems to have a couple of functions that seems like they could be useful.

RemoveEquipmentStateFlag(gameEEquipmentManagerState)
ClearSlot(Uint8)

ClearSlot seems to be fucky though as 
```LUA
im = Game.GetInventoryManager()
im:ClearSlot(5)
```
gives this error
```Error: Function 'ClearSlot' parameter 0 must be Uint8.```

**Comment by Rorschach1219** [comment]
> 
> 
> InventoryManager seems to have a couple of functions that seems like they could be useful.
> 
> RemoveEquipmentStateFlag(gameEEquipmentManagerState)
> ClearSlot(Uint8)
> 
> ClearSlot seems to be fucky though as
> 
> ```lua
> im = Game.GetInventoryManager()
> im:ClearSlot(5)
> ```
> 
> gives this error
> `Error: Function 'ClearSlot' parameter 0 must be Uint8.`

RemoveEquipmentStateFlag(gameEEquipmentManagerState)
I've also looked up this function, but I don't know what the parameters are and how to call it

**Comment by Hxmada** [comment]
Its not about deleting it its about removing the quest icon I think I found something useful though but I have no idea how to use it Game.SetQuestWeaponState(weaponState)

**Comment by willuwontu** [comment]
My guess is that since that's weapon specific, is that's the state that locks you into only being able to use that weapon. E.g. Only fists during beat on the brat fights, only able to use pistol during shooting contest, etc.

**Comment by Hxmada** [comment]
You're right because I tried and it didn't work in anyway but I'm still trying to figure out a way to remove the icon from some items even though its not about the weight because you can simply decrease your weight its just annoying and I'm sure there is a way.

**Comment by Rorschach1219** [comment]
> 
> 
> You're right because I tried and it didn't work in anyway but I'm still trying to figure out a way to remove the icon from some items even though its not about the weight because you can simply decrease your weight its just annoying and I'm sure there is a way.

Thank you for your dedication and contribution to this. Indeed, currently only non-mission items can be removed, but as long as you find a way to remove the yellow exclamation mark on the weapon, I think you can remove it. The parameter type of the state is currently unknown, I am also trying it, looking forward to your research results

**Comment by bloodaxis** [comment]
https://fearlessrevolution.com/viewtopic.php?p=172029#p172029 That should point you to how to actually remove that lock, but I have no fucking clue how to even begin to understand it. I did manage to remove the lock on weapons though with the use of https://fearlessrevolution.com/viewtopic.php?f=4&t=14633 the weapon script and using the address from the pointer offset +60. Might be of some use to figuring out locking/unlocking items through the console.

**Comment by Hxmada** [comment]
> https://fearlessrevolution.com/viewtopic.php?p=172029#p172029 That should point you to how to actually remove that lock, but I have no fucking clue how to even begin to understand it. I did manage to remove the lock on weapons though with the use of https://fearlessrevolution.com/viewtopic.php?f=4&t=14633 the weapon script and using the address from the pointer offset +60. Might be of some use to figuring out locking/unlocking items through the console.

Thanks alot, this is a good method instead of deleting the item you can drop it or sell it, I still haven't found a way to remove the icon through the console, so this is the best solution so far!

**Comment by bloodaxis** [comment]
Figured I'd add this here as well, https://github.com/PixelRick/CyberpunkSaveEditor you can easily both delete items and remove the lock on them with this editor, both much faster and less of a hassle than cheat engine/console.

**Comment by Rorschach1219** [comment]
> 
> 
> Figured I'd add this here as well, https://github.com/PixelRick/CyberpunkSaveEditor you can easily both delete items and remove the lock on them with this editor, both much faster and less of a hassle than cheat engine/console.

Thank you very much，It's very helpful
