### ISSUE TITLE
[1.06] Openning console results in CTD with RTSS running

### ISSUE THREAD

**Issue by WSSDude420** [yamashi/CyberEngineTweaks#267]
Latest version of the mod seems to work fine with one exception...

Console is not working... That is the only thing I found out wrong with latest version.

**Comment by WSSDude420** [comment]
Sorry, I can see that in the mean time, you started committing fixes... 

Closing this issue, sorry for disturbance 🙏

**Comment by WSSDude420** [comment]
Actually reopening - latest fixes didn't help me...

Still crashes to desktop when I try to open console on latest version.

**Comment by yamashi** [comment]
Can't repro, please send log file and list of stuff you have installed.

**Comment by WSSDude420** [comment]
Ok, found what's up...

RivaTuner Server Statistics crashes it. This is new behaviour though, so still should be noted I believe.
With 1.05, having RTSS running was no issue, openning console would just not render it (fixed though with https://github.com/yamashi/CyberEngineTweaks/issues/245#issuecomment-750009640 so this was ultimately non-issue)

Now, having RTSS on causes CTD when openning console.
Completely shutting down RTSS helps this issue, console works fine.

Log attached. It is reproducible 100% of the time for me.
[Cyberpunk2077-20201223-235009-17280-2248.zip](https://github.com/yamashi/CyberEngineTweaks/files/5737404/Cyberpunk2077-20201223-235009-17280-2248.zip)

**Comment by WSSDude420** [comment]
Ok, it may still somehow be caused by order...

Fix for 1.05 is not working for 1.06 it seems, RTSS seems to inject first for some reason now even with it applied...
This causes the crash. Previously, it would just not render the console in this case as said. Now it crashes.

Just confirmed this by few tests. 
Launching CP77 with RTSS completely turned off allows me to use console without crashes. Starting RTSS afterwards produces wanted result (running game, RTSS on, console working).

I use version 7.2.3 of RTSS... Should have probably said that sooner.

**Comment by WSSDude420** [comment]
Should be fixed to an extent with upcoming release now.

Note though that you should follow this comment for RTSS to work reliably (otherwise, console works half the time and other half is not rendering, depending on which hook was faster...)
#245 (comment)

Working on revising whole DX12 hooking procedure now, so hopefully, we will have some more robust solution in place SOON™ which would not require similar stunts from user.
