### ISSUE TITLE
请问这是甚么问题

### ISSUE THREAD

**Issue by wgf0330** [yamashi/CyberEngineTweaks#269]
<img width="520" alt="Snipaste_2020-12-24_07-28-40" src="https://user-images.githubusercontent.com/18156721/103043967-bbfb3180-45b9-11eb-942e-f623cb3a9980.png">

**Comment by wgf0330** [comment]
<img width="1186" alt="Snipaste_2020-12-24_07-30-12" src="https://user-images.githubusercontent.com/18156721/103044007-e0570e00-45b9-11eb-8bb5-c02af856c40d.png">
输入之后报错
pc： 3950x 3090 x570

**Comment by wgf0330** [comment]
1.06 或者1.05 都是如此

**Comment by PhantomGamers** [comment]
Are you typing ?Items.Preset_Burya_Comrade? ?

It should be "Items.Preset_Burya_Comrade"

**Comment by wgf0330** [comment]
![image](https://user-images.githubusercontent.com/18156721/103046191-4f386500-45c2-11eb-92d6-eb8f561b37f0.png)
也不对

**Comment by wgf0330** [comment]
Game.AddToInventory("Items.Preset_Burya_Comrade",1)
 这样不对么？

**Comment by wgf0330** [comment]
think，解决了，原来是标点问题……

**Comment by Rorschach1219** [comment]
你直接粘贴Excel表格里的代码吧，https://pan.aoe.top/Cyberpunk2077/ItemList/

**Comment by ttimasdf** [comment]
你用中文描述问题（你这title一点信息量没有，甚至根本连问题都没描述出来），不光开发者看不懂，后面遇到问题的人，还没办法用关键字去搜，四舍五入等于发出来对别人一点都没有帮助。反正问题解决了，直接close吧。

**Comment by baka-gourd** [comment]
This user has realized that this is a minor problem and has successfully solved it, this issue can be closed.
@yamashi
