### ISSUE TITLE
autoexec.lua not running on start.

### ISSUE THREAD

**Issue by willuwontu** [yamashi/CyberEngineTweaks#270]
Was looking into running some scripts, but I was getting annoyed when I noticed that "scripts/perks.lua" wasn't running it even though the scripts folder was in bin/x64. So I took a look at autoexec.lua and noticed that I was never getting the printed output that marks its completion.

After a bit more trial and error I ended up manually running it with `dofile("bin/x64/plugins/cyber_engine_tweaks/scripts/autoexec.lua")`, I also ended managing to run my script with `dofile("bin/x64/scripts/perks.lua")`. The config json file works properly though (obviously), so this left me a bit flummoxed.

**Comment by zingfharn** [comment]
Same issue. Your solution works, though, so thank you.
I guess it must be a path issue somewhere.

**Comment by WaschBaer0395** [comment]
steam version here, same issue , starting it via steam opens the launcher , pressing play opens the game.. and autoexec wont execute , aswell as i cant do :  dofile "scripts/myfile.lua" for example,  only via full windows path 
running the cyberpunk exe directly tho works

**Comment by zingfharn** [comment]
Yup. Steam for me. Not the end of the world (I don't mind typing a few extra chars). Might be worth noting on the documentation site though if it can't be easily fixed?
