### ISSUE TITLE
command enter

### ISSUE THREAD

**Issue by xBILLBOUSx** [yamashi/CyberEngineTweaks#271]
in console type
Game.AddExp(Strength, 12345)
error no proficiency
![Screenshot (14)](https://user-images.githubusercontent.com/76541989/103055882-4dce5480-4550-11eb-88ea-4cf78e026676.png)

**Comment by xBILLBOUSx** [comment]
in console type
Game.AddExp(Strength, 12345)

and get this
error

**Comment by PhantomGamers** [comment]
it should be 
`Game.AddExp("Strength", 12345)`
Quotes included, because it's a string.

**Comment by WSSDude420** [comment]
This can be closed I believe @yamashi
