### ISSUE TITLE
Unable to type in console

### ISSUE THREAD

**Issue by Tomgeo64** [yamashi/CyberEngineTweaks#275]
Am running in windowed borderless, version 1.04 never updated from release day. I can make the console pop-up, and I skip the opening cutscenes so I believe it's working. I just can't type in the console, I've tried every key on the keyboard. 
![image](https://user-images.githubusercontent.com/7005219/103072392-762b7280-4593-11eb-95c6-431c24e3a4a6.png)
I also think my console doesn't look right.

**Comment by gibbed** [comment]
I believe console UI doesn't get shown if your version of the game hasn't been detected by CET.

**Comment by zhangdafu12** [comment]
I'm in the same situation. How can I solve it!

**Comment by Aestheticus159** [comment]
Make sure you dropped the files into /Cyberpunk 2077/bin/x64 and not just /Cyberpunk 2077
I messed this step up when updating but after double checking the directory i had it installed in I realized the issue.

**Comment by Tomgeo64** [comment]
Definetly put the files in the right spot, any idea how I can make CET detect my game version? Or can I tell it somewere?

**Comment by Shogunotaku** [comment]
i am having the same problem, placed the files in the correct path aswell

**Comment by maxovitsj** [comment]
I had the same issue.
I removed all of the old folders / items (from the initial versions of the tool), then did a reinstall and it works now :)

**Comment by Shogunotaku** [comment]
> 
> 
> i am having the same problem, placed the files in the correct path aswell

update: i just turned off the geforce overlay and reinstalled the nexus mod v1.06 patch ver it works now.
