### ISSUE TITLE
ps4 con....算了写中文。。。ps4手柄没法用

### ISSUE THREAD

**Issue by whcwhc123** [yamashi/CyberEngineTweaks#276]
自从更新1.05之后的版本都是没法在steam版里用ps4手柄的，表现为按键完全没反应，但是游戏右下角又会跳出来识别出ps4手柄的提示的。。。
把补丁删了后，又可以用手柄了，所以肯定是补丁哪里冲突了

谁知道怎么解决么，或者写一下英文反应下，我英文实在太烂，只能看不能写。。。

**Comment by hulovexu1314** [comment]
ps4 gamepad is invalid!
After updating the game version 1.05,
Install the latest patch, enter the game will prompt that the handle has been inserted, but there is no response to the handle buttons!
Once the patch is uninstalled, it is normal!

**Comment by skeevy420** [comment]
My DS4 works fine for me with Cyberpunk 1.05 and 1.06 with DS4Windows and having Playstation Controller support enabled within Steam all paired with whatever was the latest release of CyberEngineTweaks at the time. I've been using it the virtual input patch set to false since I've never needed it.
