### ISSUE TITLE
1.06 patch console is not working

### ISSUE THREAD

**Issue by Ckwvong** [yamashi/CyberEngineTweaks#277]
![image](https://user-images.githubusercontent.com/71842225/103090947-93ad1a80-462d-11eb-85b7-9dd58b373928.png)

I've got this log after opening the game, but no matter how hard I try ` , the console will not show up, only a mouse icon will show.

I also try to type in some command under this situation, but it just not working, could anyone help?

**Comment by yamashi** [comment]
Read the wiki.

**Comment by Ckwvong** [comment]
> Read the wiki.

I read but still not help ` is the same button with ~

**Comment by yisonPylkita** [comment]
I had the same problem and solution was to shutdown RivaTuner (MSI FPS stuff)
