### ISSUE TITLE
SteamInput broken

### ISSUE THREAD

**Issue by RobotRoss** [yamashi/CyberEngineTweaks#281]
Tested with both DS4 and DS5.

Installing this mod completely breaks controller support through SteamInput.

Only way to get it working is to force SteamInput OFF (which breaks DS5 compatibility), and DS4 deadzones cannot be configured natively on Windows which causes flickering on the button prompts and erratic camera behaviour.

Uninstalling the mod fixes the issue.

**Comment by NielsGx** [comment]
I also have issues with Moonlight Gamestream, with a ds4 controller on my phone

**Comment by sqparadox** [comment]
Can confirm this is also broken for Steam controller. Mouse and Keyboard bindings work but controller bindings do not.

It literally the opposite of the Steam Input issue the game shipped with. And this mod fixed that so something broke with the mod after that.

**Comment by afiaka87** [comment]
The new release may fix these issues.

**Comment by WSSDude420** [comment]
This should be fixed also I believe by now. Solved by game update, virtual_input patch was removed already too, should be non-issue now i believe.
