### ISSUE TITLE
Item ID for the SPT32 Grad - Overwatch Unique Sniper?

### ISSUE THREAD

**Issue by ipoopedmypantsuups** [yamashi/CyberEngineTweaks#282]
I looked all over the Item Hash List but couldn't find it (Overwatch sniper). What is it called, and how do I add it to my inventory? Please help, thanks.
![image](https://user-images.githubusercontent.com/73392805/103100917-f1684500-45e2-11eb-931c-7e8145953925.png)
does it not have an item hash?

**Comment by vopefulhitamins** [comment]
Overwatch is Panam's weapon. The item name is Preset_Grad_Panam. Add with `Game.AddToInventory("Items.Preset_Grad_Panam", 1)`

Opening an issue here may not be an appropriate place to ask about specific item codes, as inventory hacking is not the primary focus of this mod. Item lists are freely available from this wiki, or from other resources such as https://www.nexusmods.com/cyberpunk2077/mods/186
