### ISSUE TITLE
Console Doesnt work

### ISSUE THREAD

**Issue by Batpimp** [yamashi/CyberEngineTweaks#284]
Attempted date 12.24.20
Compatible with V1.06
Win 10 Machine
followed the step by step - https://wiki.cybermods.net/cyber-engine-tweaks/setting-up/installing

this never shows up -
Optional) To check that everything works you can look at the logs in <cyberpunk install path>/bin/x64/plugins/cyber_engine_tweaks/**cyber_engine_tweaks.log:**

Per the troubleshooter i ran redistr v64..still nothing

rebooted PC and still nothing. Anyone else?

**Comment by Aestheticus159** [comment]
Make sure you dropped the files into /Cyberpunk 2077/bin/x64 and not just /Cyberpunk 2077
I messed this step up when updating but after double checking the directory i had it installed in I realized the issue.

**Comment by Batpimp** [comment]
doesnt show up

![image](https://user-images.githubusercontent.com/76568779/103103904-27083080-45d9-11eb-883e-268b6b09b670.png)

**Comment by seberoth** [comment]
You need to put the content of the release folder in the x64 folder. Not the release folder itself.

**Comment by Batpimp** [comment]
> You need to put the content of the release folder in the x64 folder. Not the release folder itself.

ah that wasnt clear. it worked.
