### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by yamashi** [yamashi/CyberEngineTweaks#287]
Here are the few tasks that need I need help with.

- [ ] Add event handlers for Lua  #288 
- [ ] Add property read/write
- [ ] Release memory of Array/StrongHandle/WeakHandle in the destructor
- [ ] More internal type decoding, like for example EntityID
- [ ] Add Imgui support for Lua #289

**Comment by willuwontu** [comment]
> Release memory of Array/StrongHandle/WeakHandle in the destructor

See <a href="https://www.lua.org/manual/5.4/manual.html#2.5.3">`__gc`</a>, [here's a bit more on it](https://www.lua.org/pil/29.html).

**Comment by yamashi** [comment]
It isn't related to Lua, this is related to the game's memory needing to be released so it needs to be reversed
