### ISSUE TITLE
Skip unskippable intro

### ISSUE THREAD

**Issue by mikhnal** [yamashi/CyberEngineTweaks#29]
Is there a chance to add the option to skip the unskippable intro and go straight to the game menu?

**Comment by yamashi** [comment]
It is planned, don't have an ETA tho

**Comment by miartan** [comment]
The breaching skip is very nice - cause for me it's so annoying.
But we need to somehow find a solution to get rid of all the logos/warnings etc. and also the "intro video".

**Comment by Saibamen** [comment]
@miartan: He has it in TODO list

**Comment by extract** [comment]
@Saibamen where? Is there a discord?

**Comment by miartan** [comment]
@Saibamen where? Additionally, is there a discord?
It was previously on the project page - but got removed when he implemented the skip_start_menu parameter todat I guess?

**Comment by yamashi** [comment]
I investigated this a bit today, it appears to be script driven so it's going to be quite hard to do until we get a decent script decompiler/compiler. We shall see...

**Comment by miartan** [comment]
I guess they've used the same method as for the W3 so yeah - we need to wait a little more.

**Comment by mikhnal** [comment]
@yamashi good luck!

**Comment by TheOne320** [comment]
What does "skip_start_menu" actually do? I thought it would be related to this topic. Wiki says: 

> Skips the main menu asking you to press space bar when "Breaching..."
But what does this mean? I still have to click spacebar to get into the main menu when starting the game.

**Comment by PhantomGamers** [comment]
> But what does this mean? I still have to click spacebar to get into the main menu when starting the game.

It skips the "BREACHING" screen, so you only have to press spacebar to skip the "welcome to Night City" video rather than having to press it additionally after that.

**Comment by Morritz** [comment]
> > But what does this mean? I still have to click spacebar to get into the main menu when starting the game.
> 
> It skips the "BREACHING" screen, so you only have to press spacebar to skip the "welcome to Night City" video rather than having to press it additionally after that.

It would be nice to be able to skip the video also :D

**Comment by PhantomGamers** [comment]
> It would be nice to be able to skip the video also :D

Sadly, like in Witcher 3, you need to modify the scripts in the game in order to do this. So until either CDPR releases official modding tools or someone releases a tool to decompile/recompile the game scripts this probably won't be done

**Comment by shaund** [comment]
A temporary workaround is to use cheat engine, enable speedhack, and put it to like 20x. It will zoom through the title screens.
