### ISSUE TITLE
[Request] cyber_engine_tweaks.log to include Tool version

### ISSUE THREAD

**Issue by callmenemo491** [yamashi/CyberEngineTweaks#292]
An enhancement for tool owner to know from the **cyber_engine_tweaks.log** printout, the version of the tool the end-user is currently using.

**Comment by WSSDude420** [comment]
Should not be an issue I think... I can add it if you do not oppose @yamashi .

**Comment by WSSDude420** [comment]
I suggest creating a define in xmake.lua that would resolve into <version_number> for regular public builds, probably adding separate mode for public release... And <version_number>-git-<commitnum>(-modified if some changes were made by the user) for all other builds.

Should be easily identifiable then what build is used and if it was tampered with in any way.

**Comment by WSSDude420** [comment]
This can be closed i believe? Dunno now if we log version to log also, but we have means now.

**Comment by Saibamen** [comment]
In latest released version we don't log CET version

**Comment by yamashi** [comment]
There is the GetVersion() lua function now...

**Comment by Saibamen** [comment]
@yamashi: Did you add output from `GetVersion()` to logs?

**Comment by Saibamen** [comment]
OK, it is logged now
