### ISSUE TITLE
Steam controller input broken regardless of "virtual_input" setting

### ISSUE THREAD

**Issue by brettp** [yamashi/CyberEngineTweaks#293]
All versions from 1.0.4 - 1.0.6 break Steam controller input if installed, regardless of the `virtual_input` setting. The game doesn't detect a controller at all.

Please see the attached log. I'm happy to provide additional debug info if needed.

[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/5742239/cyber_engine_tweaks.log)

**Comment by Pluis3** [comment]
Yeah it doesn't work. You can look for alternative. For my switch pro controller I use now betterjoyforcemu and it work really well.

**Comment by hrdkbhatnagar** [comment]
Same, steam input doesn't work now. Only option is to uninstall the plugin for it to work  :/

**Comment by grapenut** [comment]
I think maybe the issue is that the overlay is capturing gamepad input because of
`imgui_impl_win32.h:23://#define IMGUI_IMPL_WIN32_DISABLE_GAMEPAD`
being commented out.

**Comment by Jahfry** [comment]
Confirming same issue as OP. Either can have this plugin installed or use the Steam Controller (note: my CP2077 is bought through GOG and added as a non-steam game).

**Comment by grapenut** [comment]
> Confirming same issue as OP. Either can have this plugin installed or use the Steam Controller (note: my CP2077 is bought through GOG and added as a non-steam game).

I can confirm that including the above define when building solves the issue. These changes have already been merged, but it's not in the release yet so you'll have to clone the repo and build the lib yourself.

**Comment by grapenut** [comment]
There's a new release out now, with this fix included.

**Comment by afiaka87** [comment]
Resolved for me. Thanks.

**Comment by brettp** [comment]
Confirmed working. Thanks!
