### ISSUE TITLE
Spectre disabled or enabled on default?

### ISSUE THREAD

**Issue by Mohamed2277** [yamashi/CyberEngineTweaks#294]
Stupid question but I'm kinda confused, which one is spectre disable in, true or false?

**Comment by maxovitsj** [comment]
> 
> 
> Stupid question but I'm kinda confused, which one is spectre disable in, true or false?

https://wiki.cybermods.net/cyber-engine-tweaks/setting-up/configuration shows that the 'spectre' option is 'true' by default, which removes the spectre mitigation.

**Comment by WSSDude420** [comment]
They are not working at all after 1.05 I believe.

They should be removed already by the devs.
