### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by alkxkaras** [yamashi/CyberEngineTweaks#296]
![无标题](https://user-images.githubusercontent.com/76609016/103146832-cb5bb580-4746-11eb-88f6-f89ad769899f.png)

**Comment by PhantomGamers** [comment]
You need to wrap the item name in quotes because it's a string, so "Items.Base_Silverhand"

**Comment by Konohamaru04** [comment]
> You need to wrap the item name in quotes because it's a string, so "Items.Base_Silverhand"

Still getting same error

![Uploading Screenshot (158).png…]()

**Comment by Rorschach1219** [comment]
https://wiki.cybermods.net/cyber-engine-tweaks/console/scripts
