### ISSUE TITLE
Game CTD even when the console is set to FALSE in the .json

### ISSUE THREAD

**Issue by Reny900** [yamashi/CyberEngineTweaks#298]
i've cheked the plenty of "solutions" of this same error, adding the .asi in the global file of RTSS, or even starting msi afterburner after the loading on the  HDD  was done.
And even after crashing in these 2 events, i went and  set the console in the .json file to False

Lo and behold the game still CTD. 
Any news on this  ?
I'm on 1.06

**Comment by WSSDude420** [comment]
I see you commented 2 hours before latest release was published.

Latest release should fix issues with RTSS, as long as you have that Global profile template tweak you mentioned applied, it should work now.

**Comment by Megalomaniak** [comment]
Game CTD at which point? Note that the game itself is still very unstable and crashy depending on your HW setup.

**Comment by WSSDude420** [comment]
I think the guy just went away...

It works with RTSS with 0 issues when using the config tweak now, working on making it not needed that tweak.

@yamashi I think we can close this.
