### ISSUE TITLE
Attribute Points

### ISSUE THREAD

**Issue by qlimaxtm** [yamashi/CyberEngineTweaks#300]
Can anyone tell me what code I have to enter to add more Attribute Points to spend?

**Comment by Hxxzii** [comment]
`Game.GiveDevPoints("Attribute", val)` 

Replace `val` with the number of attribute points you want to give yourself

Take a look at the wiki [here](https://wiki.cybermods.net/cyber-engine-tweaks/console/functions) for more info/docs

**Comment by qlimaxtm** [comment]
> `Game.GiveDevPoints("Attribute", val)`
> 
> Replace `val` with the number of attribute points you want to give yourself
> 
> Take a look at the wiki [here](https://wiki.cybermods.net/cyber-engine-tweaks/console/functions) for more info/docs

Thankyouuuu! 

There is also this mission called 'Getting warmer...'  that doesn't start for me. It's stuck on 'Undiscovered, who knows what you might find'. Do you have any idea how I can use the console commands to progress in the quest or finish it so I can get the achievement for the district?
