### ISSUE TITLE
Fix for Delamain phone visual bug after completing Epistrophy

### ISSUE THREAD

**Issue by stu177** [yamashi/CyberEngineTweaks#302]
I've made various attempts at trying to fix this through editing the save and the console in-game but with no luck.

It seems to be either this effect:

![one](https://i.imgur.com/EwRk5ZC.png)

Or this:

![two](https://i.imgur.com/x168H4y.png)

I believe the quest is sq025 and from there looks to be four facts for this quest:

- sq025_delamain_fate
- sq025_scan_quest_done
- sq025_failed
- sq025_done

Any help is greatly appreciated.

**Comment by DrStalker** [comment]
This was supposed to be fixed in hotfix 1.0.5 https://www.cyberpunk.net/en/news/37166/hotfix-1-05

> Fixed an issue with Delamain's image displayed on top of the current caller during phone calls.

**Comment by stu177** [comment]
Ah sorry, I should have mentioned I'm running 1.06, so still getting it after the supposed 1.05 fix.

**Comment by stu177** [comment]
Closed?

**Comment by yamashi** [comment]
Unrelated to the mod.

**Comment by stu177** [comment]
Ah ok. Just saw there were a lot of other people putting up issues for potential fixes using the console so thought it could be used to fix this.
