### ISSUE TITLE
Any way of displaying ingame framerate/frametime cpu/gpu time statistics ? 

### ISSUE THREAD

**Issue by seccentral** [yamashi/CyberEngineTweaks#306]
You know, something like DOOM or the source games have 
I can use RTSS but that doesnt always work and has it's own problems. 
Would rather have an 'in-engine' approach

**Comment by WSSDude420** [comment]
Should be fairly easy to do I believe, as we hook directly on Present function responsible for final blit...

**Comment by NielsGx** [comment]
Use the nvidia experience thing. ALT+Z

**Comment by seccentral** [comment]
> 
> 
> Use the nvidia experience thing. ALT+Z
> Use xbox game bar Win+G for cpu/gpu statistics

i use techpowerup's nvcleanstall to strip the nvidia installer of bloat and telemetry and opted out of anything non driver-only related. 

i don't and never used xbox game bar and have all those things disabled. 
i already have a very detailed and well constructed rtss overlay but i'd rather not use any 3'rd party tools. btw if you don't know, rtss is the thing that comes bundled with msi afterburner and allows it to hook into processes and many more things but it does come with its own problems.
here it is in action 
![rtss overlay](https://user-images.githubusercontent.com/3766320/103171214-021ef200-4853-11eb-8eb2-4b460acb494b.jpg)


> 
> 
> Should be fairly easy to do I believe, as we hook directly on Present function responsible for final blit...

that sounds promising

**Comment by NielsGx** [comment]
Well, your problem if you don't want to use anything from nvidia ... It's not bloatware ...
good luck I guess

**Comment by WSSDude420** [comment]
Thing is, you could make RTSS display whatever you want and configure it to all hell, while you cannot do this for Nvidia for example.

If update frequency is too often for you, change it to once per second for example
Want just sma and slick gui to show simple number? Why not, can set it like that.

Tbh, RTSS while being more bloaty in this regard is not that performance heavy, aa long as you do not try to draw graphs and such and update too often. All can be configured.

But yes, people crying over one fps difference is stupid imo too, mainly when you probably drop much more with heavier utils many tend to use (and misuse).

**Comment by NielsGx** [comment]
Well do what do you want, just I wouldn't keep fps counter and all while actually playing. I prefer to look at the beautiful buildings than a fps counter. It catch your attention

tbh I just opened task manager to check infos when choosing the "best" settings for me and my config, after that I just play without bothering with any rtss ui

**Comment by seccentral** [comment]
nevermind, i give up.
