### ISSUE TITLE
[Experience sharing] Delete any equipment or props

### ISSUE THREAD

**Issue by Rorschach1219** [yamashi/CyberEngineTweaks#307]
Using Cheat Engine, set the HashID of the game item focused by the mouse to 0 to remove it. You can also exchange HashID to achieve cloning or transformation

Youtube : https://youtu.be/Nl34PrMY4cg
Google Drive : https://drive.google.com/drive/folders/1D67C0g7WAg9V6oI2boFJr8YBXY3YSnxo?usp=sharing

**Comment by SilverFenixFyre** [comment]
Is there a version in English, as opposed to Mandarin?

**Comment by gabrielfsousa** [comment]
nice, work
