### ISSUE TITLE
How do I change the default key from '~' to 'F1"?

### ISSUE THREAD

**Issue by meetblake** [yamashi/CyberEngineTweaks#311]
As the title,
is this possible?

**Comment by Rorschach1219** [comment]
Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\config.json  
Line4  :  "console_key": 192,   
http://cherrytree.at/misc/vk.htm
F1 = 112

**Comment by meetblake** [comment]
> Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\config.json
> Line4 : "console_key": 192,
> http://cherrytree.at/misc/vk.htm
> F1 = 112
Thank you very much.

**Comment by WSSDude420** [comment]
Close this issue if it is resolved please, @meetblake
