### ISSUE TITLE
[Issue] Debug data dumping into Command Console Output

### ISSUE THREAD

**Issue by MdosTV** [yamashi/CyberEngineTweaks#321]
I don't know if anyone has posted this already or if anyone is aware, but when Debug is enabled, it will dump a bunch of the debug data into the output of the command console and it just keeps adding. This inturn adds load to the computer, which causes low fps and game crashes.

I tested seeing if clearing the output would relieve some of the stress. When I did (when I was at like 10 fps with the command console open), my fps spiked back up to normal (60-80fps), if not better levels. 

Not sure if you have plans on this or not, but a fix for this could prob be to add a limit (or a smaller limit, if one already exists) of how much of the command console output is stored. 

For now, I recommend to those who don't need it, to keeping debug disabled. And if you do enable debug, to only use it for a short session.

Edit:  I believe the other part of the problem is data from in game interactions being dumped into the Command Console output. I am not sure if there is a limit on this right now. If there was a way to disable all interaction data from showing up in the Command Console (only show data that was typed into the console), that may solve the biggest reason for crashes and lag.

**Comment by WSSDude420** [comment]
Yeah, noticed it too... 

Wanted to look into it but did not have a time yet.
Problem is almost definitely not the number of items in ouptut, but I bet we are drawing (or at least trying to draw) every single item in the list.

Mentioning this as this is something I already encountered with ImGui. Solution was to use some ImGui function which i forgot about now... Which has given you a range of items from a list that should be visible and rendered just them.

**Comment by WSSDude420** [comment]
As suspected, we try to draw every single item in output...

Already working on fix, should be quick and small...

**Comment by WSSDude420** [comment]
Should be fixed in following release.

**Comment by MdosTV** [comment]
Awesome! Thank you for the response and looking into this!
