### ISSUE TITLE
Reset Fingers state?

### ISSUE THREAD

**Issue by Zaionn** [yamashi/CyberEngineTweaks#328]
Hi, I was wondering if you could reset ripperdoc Fingers state after having punched him via a command.
I know you can give yourself his items but I don't like that. Any ideas?

**Comment by MdosTV** [comment]
Not sure exactly what your game is looking like. But I did something similar in mine. Can't remember if I loaded a previous save or if he just came back on his own.

**Comment by NielsGx** [comment]
I guess it could be possible with Game.SetDebugFact("xxxxxxxx", value)
(like Game.SetDebugFact("mq007_skippy_aim_at_head", 1))

**Comment by NielsGx** [comment]
Game.SetDebugFact("q105_fingers_dead", 0)
I know, he's not dead, but that's the name of the "fact"

Next time, check here : https://wiki.cybermods.net/cyber-engine-tweaks/console/how-do-i
and here : https://docs.google.com/spreadsheets/d/1aVeMGOg7mhrz-vgs5fFTrr72bh0kudK0jQmtSDYPjBQ/edit?usp=sharing
