### ISSUE TITLE
[warning] 	Virtual Input Patch: failed

### ISSUE THREAD

**Issue by Hugzmy** [yamashi/CyberEngineTweaks#330]
I'll type in: player.inventory.addItem(Items.money,1000)  and I get: lua: error: [string "player, inventory.additem(Ite...")]:1: attempt to index a nil value (global 'player')  

In the /cyber_engine_tweaks.log I see the line I put in the subject heading:     [warning] 	    Virtual Input Patch: failed   every input I make.

Any ideas??

thanks

**Comment by travisnewman** [comment]
You're using the syntax from the old console mod, check the doc for this mod: https://wiki.cybermods.net/cyber-engine-tweaks/console/how-do-i
