### ISSUE TITLE
[Trivial Feature Request] Set qualityLevel 

### ISSUE THREAD

**Issue by Sekkei** [yamashi/CyberEngineTweaks#334]
Adding qualityLevel to config.json
Reason: on (weaker nvidia non RTX) systems the option "GeForceNow" improves the gpu usage without a real disadvantage in quallity as you can still use the ingame settings 
Using this as a default could help all users to maximize the ingame settings

Even using "RTXUltra" on the same ingame settings improves performance ( but not as much as "GeForceNow")
There is no different in "Ultra" and "RTXUltra" and may be usefull for RTX users to use this value as default

"Cinematic" Presets needs more power
"Console" not tested as it changes the visuals to much 

*bonus
the following dlls are not needed on a normal windows installation 
`api-ms-win-downlevel-kernel32-l2-1-0.dll
d3dcompiler_47.dll
dbgcore.dll
dbghelp.dll
dxilconv7.dll
GFSDK_Aftermath_Lib.x64.dll
nvngx_dlss.dll
nvToolsExt64_1.dll
PxPvdSDK_x64.dll
symsrv.dll
WinPixEventRuntime.dll`
removing them will load system, driver or no dlls which could help with compatibility performance problems

**Comment by WSSDude420** [comment]
That last thing you wrote is plain stupid tbh...

They are there for a reason. They have precedence over whatever is in system folder.
Also, some of these things you want to remove are essential for running game on Windows 7.

Do not remove any DLLs!

**Comment by NielsGx** [comment]
Sounds like Karen in action reading this 😄

**Comment by WSSDude420** [comment]
Someone suggests something without actually knowing what it does, probably causing issues for us and others in future...
Of course I'll take a stance against it :)

I'd say this is different if you try to reference past issue I reacted there that way... You started demands from us while being super arrogant, or at least it sounded like that to me.

Calling someone on their BS is whole another thing I believe @NielsGx ;)
