### ISSUE TITLE
I Can't Seem to Find My Problem Anywhere

### ISSUE THREAD

**Issue by KelpieTheWelpie** [yamashi/CyberEngineTweaks#340]
Anytime I try to add an item to my inventory by Game.addtoinventory("items.money,50000") I keep getting the error "attempt to index a nil value". I'm not well-versed in this area so I'm not sure what this means. Also, if I try to activate a script file, it says "no such file or directory", however I placed the file in my scripts folder of this mod. Could anyone help me figure these issues out?

**Comment by yamashi** [comment]
It is case sensitive, please read the wiki.
