### ISSUE TITLE
Does not support super-ultrawide (32:9) resolution

### ISSUE THREAD

**Issue by Dilliox** [yamashi/CyberEngineTweaks#346]
The plug-in does not seem to support super-ultrawide (32:9) resolution. Unable to click the input bar and enter any command in the console.

changing resolution to standard 16:9 works.

Tested with Samsung CRG9

**Comment by JustMaier** [comment]
Might be something else because I'm on a 32:9 1440p display and it seems to work as expected.

I know that RivaTuner and MSI Afterburner made the console not appear for me initially though.

**Comment by WSSDude420** [comment]
May be resolved by #345 but am unsure now if it is caused by what i think it is...

So try to test latest build when it drops, changes already merged.

**Comment by Dilliox** [comment]
Thanks. I can confirm the issue can no longer be reproduced with the latest build 
console now takes full width of the screen.
