### ISSUE TITLE
Requested: io.read() support

### ISSUE THREAD

**Issue by khafir** [yamashi/CyberEngineTweaks#348]
io.read() support is requested. If it is already supported then I have missed it in the wiki and you have my apologies. 

Use case would be to create a console driven menu system that would operate on user input (feedback).

**Comment by yamashi** [comment]
I do think it's already supported

**Comment by khafir** [comment]
t=io.read(); print(t);

I tried this as an example both at the command line and in a script ran using dofile(), in both cases there is no wait for user input; it's like io.read() is ignored.

If it is indeed supported, is there a particular syntax I should try other than what I am?

**Comment by khafir** [comment]
I have tried a multitude of variations for gather user input, from io.read() to io.input(io.stdin) and am unable to capture anything from the user. I also attempted the 'read a number' script linked in the wiki (https://wiki.cybermods.net/cyber-engine-tweaks/console/usage -> [lua](https://www.lua.org/pil/1.html) and am getting the same behavior as I first reported.

**Comment by khafir** [comment]
> I do think it's already supported

I have tried a multitude of variations for gather user input, from io.read() to io.input(io.stdin) and am unable to capture anything from the user. I also attempted the 'read a number' script linked in the wiki (https://wiki.cybermods.net/cyber-engine-tweaks/console/usage -> lua and am getting the same behavior as I first reported.

**Comment by yamashi** [comment]
But io.read is implemented it just wont work on stdin since there is no stdin in this case. I really dont see the expected usage here. Console commands are processed by the lua vm, you can expose a function taking a string as arg if you want to parse commands but I suggest you use the lua scripting method instead.
