### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by scx1125** [yamashi/CyberEngineTweaks#349]
error: cl: 命令行 warning D9025 :正在重写“/std:c++17”(用“/std:c++latest”)
Converter.cpp
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(5): error C2955: “FixedString”: 使用 类 模板 需要 模板 参数列表
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\common/Meta.h(5): note: 参见“FixedString”的声明
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(5): error C2993: “FixedString”: 非类型模板参数“REDName”的类型非法
src\reverse\Converter.cpp(11): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(11): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(11): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(11): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(11): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(11): note: 目标类型无构造函数
src\reverse\Converter.cpp(12): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(12): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(12): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(12): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(12): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(12): note: 目标类型无构造函数
src\reverse\Converter.cpp(13): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(13): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(13): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(13): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(13): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(13): note: 目标类型无构造函数
src\reverse\Converter.cpp(14): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(14): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(14): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(14): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(14): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(14): note: 目标类型无构造函数
src\reverse\Converter.cpp(15): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(15): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(15): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(15): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(15): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(15): note: 目标类型无构造函数
src\reverse\Converter.cpp(16): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(16): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(16): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(16): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(16): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(16): note: 目标类型无构造函数
src\reverse\Converter.cpp(17): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(17): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(17): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(17): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(17): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(17): note: 目标类型无构造函数
src\reverse\Converter.cpp(18): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(18): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(18): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(18): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(18): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(18): note: 目标类型无构造函数
src\reverse\Converter.cpp(19): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(19): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(19): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(19): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(19): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(19): note: 目标类型无构造函数
src\reverse\Converter.cpp(20): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(20): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(20): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(20): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(20): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(20): note: 目标类型无构造函数
src\reverse\Converter.cpp(21): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(21): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(21): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(21): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(21): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(21): note: 目标类型无构造函数
src\reverse\Converter.cpp(22): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(22): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(22): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(22): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(22): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(22): note: 目标类型无构造函数
src\reverse\Converter.cpp(23): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(23): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(23): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(23): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(23): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(23): note: 目标类型无构造函数
src\reverse\Converter.cpp(24): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(24): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(24): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(24): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(24): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(24): note: 目标类型无构造函数
src\reverse\Converter.cpp(25): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(25): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(25): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(25): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(25): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(25): note: 目标类型无构造函数
src\reverse\Converter.cpp(26): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(26): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(26): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(26): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(26): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(26): note: 目标类型无构造函数
src\reverse\Converter.cpp(27): error C2762: “LuaRED”: 作为“REDName”的模板参数的表达式无效
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(27): error C2641: 无法推导“LuaRED”的模板参数
src\reverse\Converter.cpp(27): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“T”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(27): error C2783: “LuaRED<T,REDName> LuaRED(void)”: 未能为“REDName”推导 模板 参数
C:\Users\41080\Desktop\CyberEngineTweaks\CyberEngineTweaks\src\reverse\LuaRED.h(7): note: 参见“LuaRED”的声明
src\reverse\Converter.cpp(27): error C2512: “LuaRED”: 没有合适的默认构造函数可用
src\reverse\Converter.cpp(27): note: 目标类型无构造函数
src\reverse\Converter.cpp(10): error C2672: “operator __surrogate_func”: 未找到匹配的重载函数
src\reverse\Converter.cpp(49): error C3536: “s_metaVisitor”: 初始化之前无法使用
src\reverse\Converter.cpp(49): error C2064: 项不会计算为接受 1 个参数的函数
src\reverse\Converter.cpp(72): error C2064: 项不会计算为接受 1 个参数的函数
src\reverse\Converter.cpp(95): error C2064: 项不会计算为接受 1 个参数的函数

**Comment by WSSDude420** [comment]
Ok, are you using Visual Studio 2019?
That would be first thing to start with if not.

If yes, did you update it?
Latest version should be used. I believe there was some bug in older VS2019 preventing compilation.

**Comment by yamashi** [comment]
Update visual studio to the latest version, LuaRED uses C++20 extensions not available before that.
