### ISSUE TITLE
AMD fix? 

### ISSUE THREAD

**Issue by CrossTalkMan** [yamashi/CyberEngineTweaks#351]
I'm using a Ryzen 7 3700X 8-core CPU. Before installing this MOD, I reached 60 fps on version 1.04 by editing the .exe file. 

After updating the game to v1.06 and installing this MOD, the fps dropped to 30 with the same graphic setting. 

I checked with the log file, which states `AMD SMT Patch: success`, but the CPU usage keeps around only 20-30%. BTW I set `cpu_memory_pool_fraction = 1.0` in the `config.json`

Did I miss anything?

**Comment by CrossTalkMan** [comment]
BTW I also set `skip_start_menu` and `disable_intro_movies` to `true` but they seems not working. Maybe this indicates that the MOD does not actually activate?

**Comment by WSSDude420** [comment]
Patch is not working from 1.05 onwards.

That patch is already basically inside game EXE. 
It will be removed in future release, already is here in sources if you look at changes.

**Comment by CrossTalkMan** [comment]
> Patch is not working from 1.05 onwards.
> 
> That patch is already basically inside game EXE.
> It will be removed in future release, already is here in sources if you look at changes.
> 
> Memory pools were also removed, along with spectre patches.
> 
> You can safely disregard these.

Yeah, from the CDPR official article, I saw that they fix the AMD CPU issue with 4-core and 6-core in v1.05. But will this MOD do the rest for 8-core, 12-core and 16-core processors?

**Comment by WSSDude420** [comment]
Look, if even AMD, CPU manufacturer itself, says this is of no real benefit, it most probably is not ;)

Patch was removed and there is no plan to reintroduce it, as it was not working anyway for few game version now and is of no real benefit.

**Comment by Megalomaniak** [comment]
> Yeah, from the CDPR official article, I saw that they fix the AMD CPU issue with 4-core and 6-core in v1.05. But will this MOD do the rest for 8-core, 12-core and 16-core processors?

Only 6 cores and below was negatively affected. The patch never had any effect on 8 cores or above.
