### ISSUE TITLE
[1.06] Non responsive dialogues, can't select other options in any dialogue

### ISSUE THREAD

**Issue by Veretragna** [yamashi/CyberEngineTweaks#357]
Cyberpunk 2077 on Steam, version 1.06.

After installing this tweak dialogues in the game become unresponsive. Once the game is freshly launched from Steam, dialog options except very first are not available: mouse wheel, arrows and W/S buttons do nothing when one tries to choose other options. This continues until saving and loading. Removing this tweak instantly solves the problem and dialogues become responsive.
Please check.

**Comment by ZeroSuf3r** [comment]
Had this issue as well, not really common in my case, but it happened.
