### ISSUE TITLE
Remove forced sharpening?

### ISSUE THREAD

**Issue by Sekerali** [yamashi/CyberEngineTweaks#36]
A sharpening filter was forced into 1.04, and theres very little complaints about it. Im trying my luck here with a request for disabling it as it seems like it will only ever get removed officially - whenever that is.

**Comment by pcktm** [comment]
While I haven't tested this myself on Cyberpunk yet, you could try adding
```
[PostProcess]
SharpenAmount=0.f
```
to rendering.ini config file. This is how it was done in Witcher 3 and might work in Cyberpunk.

**Comment by pcktm** [comment]
Nevermind, I was wrong. Some comment from nexusmods:

> Shut down Developer***/**/ConstrastAdaptiveSharpening doesn't work. Didn't make any difference. That is so frustrating since 
> CDPR turned it on by force in v1.04. Hope that we'll find a way to shut it down.

**Comment by MrUltimate** [comment]
THIS. Couldn't figure out why my game was looking like crap despite being on Ultra settings. The forced sharpening sucks. If someone figures out how to disable it, please do tell!

**Comment by Pogogo007** [comment]
Take a look at https://www.nexusmods.com/cyberpunk2077/mods/193?tab=files&file_id=421

**Comment by MrUltimate** [comment]
@Pogogo007 Lots of people on the CDPR forums have tried it, I can only find the ContrastAdaptiveSharpening and that apparently doesn't seem to fix it. https://forums.cdprojektred.com/index.php?threads/forced-sharpening-in-1-04.11045372/page-2

**Comment by d3x84** [comment]
they forced CAS because a HUUUUGE amount of people complained about the ghosting effects of TAA.
so either you have a very blurry game or some CAS artifacts. in fact some studios even hardcode a CAS solution into into their TAA

**Comment by Sekerali** [comment]
Confirming the sharpen filter is still forced on 1.05.

**Comment by MrUltimate** [comment]
> they forced CAS because a HUUUUGE amount of people complained about the ghosting effects of TAA.
> so either you have a very blurry game or some CAS artifacts. in fact some studios even hardcode a CAS solution into into their TAA

Still, there should be a toggle to just turn this off for those of us who don't like it at all. We can only hope they add one in the future or the modding community figures out how to disable it
