### ISSUE TITLE
[Raytracing] category doesn't function.

### ISSUE THREAD

**Issue by romelsalwi** [yamashi/CyberEngineTweaks#360]
I tried out few INI settings under [Raytracing] category. few of them gave feedback but mostly didn't.

**Comment by NielsGx** [comment]
Is this related to this mod at all?

**Comment by romelsalwi** [comment]
GameOptions.GetBool("Developer/FeatureToggles", "GlobalIllumination")

BOOL

GameOptions.SetBool("RayTracing", "EnableShadowCasadesOptimization", false)
GameOptions.SetBool("RayTracing", "EnableImportanceSampling", false)
GameOptions.SetBool("RayTracing", "EnableDiffuseIllumination", false)
GameOptions.SetBool("RayTracing", "EnableGlobalIllumination", false)
GameOptions.SetBool("RayTracing", "EnableLocalLights", false)
GameOptions.SetBool("RayTracing", "EnableAmbientOcclusion", false)
GameOptions.SetBool("RayTracing", "LocalLightTraceLightVolumes", false)

GameOptions.SetBool("RayTracing/Debug", "AmbientOcclusion", true)
GameOptions.SetBool("RayTracing/Debug", "EnableVisibilityCheck", true)
GameOptions.SetBool("RayTracing/Debug", "Reflection", true)
GameOptions.SetBool("RayTracing/Debug", "SkipStaticMeshes", true)
GameOptions.SetBool("RayTracing/Debug", "SkipDynamicMeshes", true)
GameOptions.SetBool("RayTracing/Debug", "TransparentReflection", true)

GameOptions.SetBool("RayTracing/NRD", "DiffuseAntiLag", false)
GameOptions.SetBool("RayTracing/NRD", "ReferenceAccumulation", true)
GameOptions.SetBool("RayTracing/NRD", "EnableAmbientOcclusion", false)

GameOptions.SetBool("Developer/FeatureToggles", "GlobalIllumination", false)

GameOptions.SetBool("Rendering", "UseSkinningLOD", false)
GameOptions.SetBool("Traffic", "DisableLOD", false)
GameOptions.SetBool("Streaming", "ForceUnstream", true)

GameOptions.SetBool("Rendering/AsyncCompute", "HairClears", false)

FLOAT

GameOptions.SetFloat("RayTracing/Reflection","RoughnessThreshold", "8.0")
GameOptions.SetFloat("RayTracing","EmittanceScale", "1.0")
GameOptions.SetFloat("RayTracing","EmissiveClipRadius", "1.0")
GameOptions.SetFloat("RayTracing","LocalLightClipRadius", "1.0")
GameOptions.SetFloat("RayTracing","EmissiveRangeScale", "1.0")
GameOptions.SetFloat("RayTracing","DeflickerStrength", "0.0")
GameOptions.SetFloat("RayTracing","TracingRadiusReflections", "0.0")
GameOptions.SetFloat("RayTracing","TracingRadius", "100.0")
GameOptions.SetFloat("RayTracing","VisibilityCullingRadius", "0.0")
GameOptions.SetFloat("RayTracing","VisibilityFrustumOffset", "0.0")
GameOptions.SetFloat("RayTracing","AccumulationSpeed", "0.0")
GameOptions.SetFloat("RayTracing","DynamicInstanceUpdateDistanceFactor", "0.0")
GameOptions.SetFloat("RayTracing","LocalLightClipRadius", "0.0")
GameOptions.SetFloat("RayTracing","ImportanceSamplingTransitionMax", "0.0")
GameOptions.SetFloat("RayTracing","ImportanceSamplingTransitionMin", "0.0")
GameOptions.SetFloat("RayTracing","DynamicInstanceUpdateDistanceFactor", "0.0")
GameOptions.SetFloat("RayTracing","DynamicInstanceUpdateDistanceThreshold", "25.0")
GameOptions.SetFloat("RayTracing","TransparentReflectionEnvironmentBlendFactor", "1.0")

GameOptions.SetFloat("RayTracing/Debug", "ClipRadius", "1")
GameOptions.SetFloat("RayTracing/Debug", "PrimaryRays", "1")

GameOptions.SetFloat("RayTracing/NRD","MaxHitDistanceDiffuse", "20.0")
GameOptions.SetFloat("RayTracing/NRD","DiffuseDenoisingRadius", "00.0")
GameOptions.SetFloat("RayTracing/NRD","DiffuseMaxAdaptiveRadiusScale", "00.0")
GameOptions.SetFloat("RayTracing/NRD","SpecularDenoisingRadius", "00.0")
GameOptions.SetFloat("RayTracing/NRD","Debug", "1.0")

GameOptions.SetFloat("Editor/VolumetricFog","Exponent", "10.0")

GameOptions.SetFloat("Streaming","DistanceBoost", "10.0")
GameOptions.SetFloat("Streaming","PrecacheDistance", "10.0")
GameOptions.SetFloat("Streaming","MinStreamingDistance", "00.0")
GameOptions.SetFloat("Streaming","MaxStreamingObserverHeight", "00.0")
GameOptions.SetFloat("Streaming","MaxStreamingDistance", "1000.0")
GameOptions.SetFloat("Streaming/Culling/NonAirVehicle","MaxStreamingRadius", "10.0")

GameOptions.SetFloat("Editor/Characters/Hair","RoughnessFactor", "0.0")
GameOptions.SetFloat("Editor/Characters/Hair","SpecularRandom_Max", "0.0")
GameOptions.SetFloat("Editor/Characters/Hair","SpecularRandom_Min", "-0.1")

INT
GameOptions.SetInt("RayTracing","DynamicInstanceUpdateNumMax", "16")
GameOptions.SetInt("RayTracing","DynamicInstanceUpdateBatchSize", "16")
GameOptions.SetInt("RayTracing","LightGridSize", "16")
GameOptions.SetInt("RayTracing","LocalLightBatchSize", "16")
GameOptions.SetInt("RayTracing","LocalLightNumMax", "16")

GameOptions.SetInt("RayTracing", "DebugMode", "1")

GameOptions.SetInt("RayTracing/Debug","ForcedLod", "1")
GameOptions.SetInt("RayTracing/Debug","ImportanceSampling", "1")

GameOptions.SetInt("Streaming","MaxNodesPerFrame", "100")

GameOptions.SetInt("Occlusion", "MultiFrustumOcclusionMode", "1")

**Comment by romelsalwi** [comment]
Here are the function I have been using though CET. Few setting don't give me feedback as intended.

**Comment by romelsalwi** [comment]
I don't think you are interested in looking in this aspect.

**Comment by romelsalwi** [comment]
These don't work/ give feedback. I was using CET to check the features on the go:

GameOptions.SetBool("RayTracing", "EnableLocalLights", false)
GameOptions.SetFloat("RayTracing","ImportanceSamplingTransitionMax", "0.0")
GameOptions.SetFloat("RayTracing","ImportanceSamplingTransitionMin", "0.0")
