### ISSUE TITLE
Command Prompt key not working

### ISSUE THREAD

**Issue by TheCaptain57** [yamashi/CyberEngineTweaks#361]
I am using US keyboard so I know the key should be `/~, but in the game when I press it nothing happens. I followed all instructions, put all files into cyberpunk 2077/bin/x64 and made sure I was in windows borderless mode, but nothing still. Not sure if I did this right, do certain files go somewhere else or something?

**Comment by WSSDude420** [comment]
There are some major issues currently with 1.8.1

Try to downgrade to 1.8.0 till fix is ready.

Also, if you have RTSS running, you need to either completely shut it down or delay it. RTSS is known to cause console not to render.

**Comment by WSSDude420** [comment]
Hopefully this can be closed now with latest changes in master.
