### ISSUE TITLE
"avx": true, Does It Disable The In-Game AVX?

### ISSUE THREAD

**Issue by KedarWolf** [yamashi/CyberEngineTweaks#362]
Does "avx": true, mean AVX is enabled or AVX CPU fix is active and/or AVX is disabled?

**Comment by KedarWolf** [comment]
Google says  "avx": true, means AVX fix is on, but does it disable AVX as well?

**Comment by WSSDude420** [comment]
Option does nothing for 1.05+ 
They removed AVX instructions in that patch.

It was only effective in 1.04.

And yes, it was meant to patch those instructions out so effecfively disabling them.
But as said, no use on newer game versions.

**Comment by WSSDude420** [comment]
@yamashi can be closed I believe.
