### ISSUE TITLE
[1.8.2] No Response from Commands

### ISSUE THREAD

**Issue by khafir** [yamashi/CyberEngineTweaks#365]
1. Updated to 1.8.2
2. Attempt commands that would present with response on execution ( ex: Game.PrintItems() ), received no response and console moved to newline.
3. Rolled back to v1.8.0, same behavior.
4. Rolled back to v1.7.3, expected behavior restored.
5. Reboot PC, expected behavior present (v1.7.3).
6. Uninstall CET completely, reboot machine.
7. Install v1.8.2, experience behavior initially described (2).
8. Roll back to v1.7.3, expected behavior returns.

**Comment by WSSDude420** [comment]
Uncheck `Disable Game Log`, this is game log related I believe.

**Comment by khafir** [comment]
> Uncheck `Disable Game Log`, this is game log related I believe.

That resolved my issue. Thank you for your response, I'm embarrassed that I missed that. Please mark this bug report as closed or resolved, thank you!

**Comment by WSSDude420** [comment]
Only you can or owner :P

Anyway, glad to help!
