### ISSUE TITLE
Commands won't work

### ISSUE THREAD

**Issue by TheBeepMan** [yamashi/CyberEngineTweaks#367]
I'm fairly certain i did everything correctly, but I copy-past commands exactly as they were on websites, including all necessary structures, and they won't, it worked once, but won't now, anyone know what's wrong?

**Comment by MrShady187** [comment]
> I'm fairly certain i did everything correctly, but I copy-past commands exactly as they were on websites, including all necessary structures, and they won't, it worked once, but won't now, anyone know what's wrong?

I just had the same problem, but figured out..
Try this format:
Game.AddToInventory("Items.Preset_Kenshin_Frank", 1)
