### ISSUE TITLE
ABNT2 (Brazilian) keyboard - console key the same as ' and "

### ISSUE THREAD

**Issue by imsys** [yamashi/CyberEngineTweaks#370]
In Brazil, the most common keyboard layout is ABNT2, and the Console Key for Cyber Engine is the single quotation mark ' but if I try to type commands that uses double quotation mark ", I need to press Shift + ' but pressing it closes the console.
But if I open the console with Shift + ' it will open and insert the " but it's annoying toggling the console while typing a command.
![640px-KB_Portuguese_Brazil-consolekey](https://user-images.githubusercontent.com/911254/103508509-df3aa200-4e3f-11eb-8da5-1de149f4456b.png)

**Comment by yamashi** [comment]
You can configure the key to something else in config.json

**Comment by imsys** [comment]
Okay, thanks!
I changed it to 45 (Insert key).
I looked into the documentation before posting, and when I saw this page I thought there wasn't a way to change, maybe a note there would also help other users:
https://wiki.cybermods.net/cyber-engine-tweaks/console/usage#how-to-open-the-console
