### ISSUE TITLE
Console not doing anything

### ISSUE THREAD

**Issue by L4UR155** [yamashi/CyberEngineTweaks#373]
Hello,

I was trying to install one mod but for some reason console does not do anything. I have fallowed installation video, updated VC_redist. It creates ,,cyber_engine_tweaks.log. I tried loading file from scripts, mods, main game folders, nothing changed, tried to reinstall came and CET completely, nothing changed. Last action that I tried is to put recip.lua (mod file) in all locations, still no luck. No command is working.

game version GOG 1.06.

adding screen of problem and log.

[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/5766025/cyber_engine_tweaks.log)

![Nothing happening](https://user-images.githubusercontent.com/76965213/103563053-ce803f80-4ec4-11eb-935c-c0c121b77f21.png)

any ideas ?

**Comment by xray** [comment]
Same here, updated to the latest version and only base game commands are working. Unable to use `dofile`.

**Comment by ZachMayer35** [comment]
From your log

> [2021-01-04 19:24:39.871] [info] Lua scripts search path: "C:\Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\mods"

Means that "C:\Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\mods" is being used as a base path for the file path value. 

It should work if you use `dofile("recip.lua")` as long as the `recip.lua` file exists at "C:\Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\mods\recip.lua"

**Comment by GreenyX1** [comment]
I'm suing v1.8.2 from nexus mods

Place scripts in the script folder of cyber engine tweaks

Try dofile("recip.lua")

**Comment by WSSDude420** [comment]
Known and already fixed issue.

Will be in next release.

For now, you can downgrade to 1.8.0 or download latest artifact from Checks.

**Comment by WSSDude420** [comment]
@yamashi can be closed I believe.

**Comment by L4UR155** [comment]
> I'm suing v1.8.2 from nexus mods
> 
> Place scripts in the script folder of cyber engine tweaks
> 
> Try dofile("recip.lua")
> 
> Edit: do not use the mods folder

Already tried in every possible location, tried mods, tried scripts, tried just main game folder (x64) as a last resort even tried all of them at once... nothing helped.
