### ISSUE TITLE
v1.8.3 results in permanent windows cursor in the middle of the screen

### ISSUE THREAD

**Issue by marcusds** [yamashi/CyberEngineTweaks#383]
v1.8.3 results in permanent windows cursor in the middle of the screen

Downgrading to 1.8.2 seems to solve this issue with the same config properties.

**Comment by cj0293** [comment]
yeah,me too,bor.

**Comment by WSSDude420** [comment]
Tbh, this is very poor info...

- post your log (found inside plugins/cyber_engine_tweaks/cyber_engine_tweaks.log)
- post your OS
- post wheter you use fullscreen or borderless (if fullscreen, try right away with borderless please)
- if you are running ANY other overlay OR recording software, try to disable it completely (turn it off, not just hide it)

**Comment by emaf94** [comment]
same problem

- [cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/5777511/cyber_engine_tweaks.log)
- Windows 10 Pro x64 20H2 (19042.685)
- fullscreen
- reshade & rivatuner (I disabled both and it was not fixed)

**Comment by tkp206093** [comment]
+1

**Comment by cyb3rm4n** [comment]
Confirming that bug.

**Comment by WSSDude420** [comment]
There was a small finding - try to disable virtual_input patch in config.json if it does not help.

**Comment by nirkons** [comment]
also for me, disabling virtual input doesn't help

**Comment by WSSDude420** [comment]
@nirkons @cyb3rm4n @tkp206093 @emaf94 @cj0293 @marcusds 

I found out what is an issue finally, will not happen in next release.
You guys disabled console, didn't you?
You need to have it enabled in current release.

**Comment by WSSDude420** [comment]
@yamashi this can be closed, have been confirmed as a fix for this on Discord by user with exact same issue.
