### ISSUE TITLE
config isnt working 

### ISSUE THREAD

**Issue by sizen15** [yamashi/CyberEngineTweaks#385]
did the install.nothing happens in game.cant open console.

**Comment by Xanoreus** [comment]
Double check the steps, make sure you are installing into the correct directory. Also, you may need to config to enable console commands. Make sure you are not running RivaTuner (it will interfere with the console UI).

**Comment by sunilrav** [comment]
Some people are thinking that console opens up automatically. Non developers don't realize you have to hit ` key after the game starts to open the console.
