### ISSUE TITLE
Flatlined on install!

### ISSUE THREAD

**Issue by AmidoNewsInside** [yamashi/CyberEngineTweaks#386]
[Cyberpunk2077-20210106-094420-8536-4656.zip](https://github.com/yamashi/CyberEngineTweaks/files/5775814/Cyberpunk2077-20210106-094420-8536-4656.zip)

installed the mod and then the game no longer opens, after deleting the mod (version.dll) the game runs normally

what am I doing wrong???

**Comment by CoffeePanda0** [comment]
Same issue as me, I get a message saying it caused a "driver timeout". Hope this is fixed soon as this plugin breaks every time.
