### ISSUE TITLE
Problems with letter O

### ISSUE THREAD

**Issue by Gokujo** [yamashi/CyberEngineTweaks#387]
I have a German Windows 10x64 Pro and I have problems with letter **O**. I try to type, but no respond in console. Only if I copy-paste this letter it works.

**Comment by TheOneDoc** [comment]
Just tested on my system also Win 10 Pro german keyboard layout o and O works fine. Remember the ö is the default key to open console on german layout so that one would need remapping if needed.

**Comment by Gokujo** [comment]
> Just tested on my system also Win 10 Pro german keyboard layout o and O works fine. Remember the ö is the default key to open console on german layout so that one would need remapping if needed.
> 
> Tested on 1.8.3 game version 1.6

[See yourself](https://youtu.be/BIz_eXhfZ8Y)
the uppercase of O works fine, but lowercase - dont.

**Comment by NielsGx** [comment]
Every time I copy paste smth into the console, it adds a " or ''
Not in the console input, or at least it's invisible, but when I execute the command, the " is at the end.
I have to copy paste, then write a char, then delete it, then enter to execute

Using swiss french keyboard (switzerland, qwertz)

**Comment by WSSDude420** [comment]
I tried with all the layouts you mentioned here, none gives me issues, so I cannot reproduced either of the two issues mentioned here...
