### ISSUE TITLE
Add user_config.json as an additional config file to check for

### ISSUE THREAD

**Issue by bradlishman** [yamashi/CyberEngineTweaks#389]
When updating the plugin, the config.json file is overwritten.  I then manually add my custom console key line and update a few more settings back into the file.  Not a huge amount of work to do of course, but it would be nice to have an alternative solution.

Maybe the plugin could look for another config file for user settings that would add additional settings or overwrite ones from the standard file.

Could we update Options.cpp to look for this file or is there a better way to do it that I missed?

**Comment by WSSDude420** [comment]
We will most probably stop packaging config.json with newer releases.

If not with following release, next one for sure.

There are plans to change this as a whole. First-time startup ever will have GUI pop-up where user will have to set toggle key (cause this seems to popup as one of the most common issues it seems, on our Discord at least)
Also, users could change settings there and just reload game to apply them.

So, following next/nextnext release, as said, no config.json will be packaged, user settings will be kept.

I think we may close this @yamashi

**Comment by bradlishman** [comment]
That all sounds good. But maybe a new gui for the settings is quite far down the line. I'd rather see more deeper integration and "tweaks" developed first. So an extra JSON file to check on load is a quick fix for now and as you say would help solve feedback regarding the console key and other settings being overwritten.

**Comment by WSSDude420** [comment]
It is not about overwritting key binds now what i meant. More like users dont know how to properly rebind or dont even know there may be an issue with key bind.

This will be in soon actually, should be today.

**Comment by WSSDude420** [comment]
I dont see any reason for extra file really, mainly when new UI is almost done.

**Comment by bradlishman** [comment]
Oh ok cool, if it's almost done then great. Thanks for your hard work. :)

**Comment by bradlishman** [comment]
@yamashi It would be good to hear your feedback on this idea.  Please could you respond with your analysis?

**Comment by WSSDude420** [comment]
#400 closes this... Dont know why you had to reopen it.
Already told you this is worked on.

Was not ready in time, we wanted to make minor release.
Will be in next major one.
