### ISSUE TITLE
Script "How can I change an item's rarity" not working for me

### ISSUE THREAD

**Issue by elastic-soul** [yamashi/CyberEngineTweaks#393]
console output looks like this:

player = Game.GetPlayer()ssc = Game.GetScriptableSystemsContainer()ts = Game.GetTransactionSystem()es = ssc:Get(CName.new('EquipmentSystem'))cs = ssc:Get(CName.new('CraftingSystem'))espd = es:GetPlayerData(player)espd['GetItemInEquipSlot2'] = espd['GetItemInEquipSlot;gamedataEquipmentAreaInt32']cs['SetItemLevel2'] = cs['SetItemLevel;gameItemData']local slots = {    Face = 1,    Feet = 1,    Head = 1,    InnerChest = 1,    Legs = 1,    OuterChest = 1,    Weapon = 3}for k,v in pairs(slots) do    for i=1,v do        print('Upgrading item in ' .. k .. ' slot ' .. (i - 1))        itemid = espd:GetItemInEquipSlot2(k, i - 1)        if itemid.tdbid.hash ~= 0 then             itemdata = ts:GetItemData(player, itemid)            cs:SetItemLevel2(itemdata)            Game['gameRPGManager::ForceItemQuality;GameObjectgameItemDataCName'](player, itemdata, CName.new('Legendary'))        end    end end

Function 'GetItemInEquipSlot;gamedataEquipmentAreaInt32' not found in system 'EquipmentSystemPlayerData'.
Function 'SetItemLevel;gameItemData' not found in system 'CraftingSystem'.
Upgrading item in OuterChest slot 0 
lua: error: [string "player = Game.GetPlayer()ssc..."]:1: attempt to call a nil value (method 'GetItemInEquipSlot2')

My item in OuterChest was not upgraded. No matter what i put in there.
Is there a save and reload procedure to see the changes? All other commands work instantly.

Thanks you for help.

**Comment by ccrofts17** [comment]
I'm having a similar issue, pasting the script into the console doesn't work for me either.

When I put it into a lua script and run it, this is the output I see:
```
Function 'GetItemInEquipSlot;gamedataEquipmentAreaInt32' not found in system 'EquipmentSystemPlayerData'.
Function 'SetItemLevel;gameItemData' not found in system 'CraftingSystem'.
Upgrading item in Face slot 0
lua: error: ...77\bin\x64\plugins\cyber_engine_tweaks\scripts\scale.lua:24: attempt to call a nil value (method 'GetItemInEquipSlot2')
```

**Comment by elastic-soul** [comment]
This is what helped me.
I went from game version 1.05 to 1.06. Reinstalled cet1.8.3.
Copied the script into console and it worked.

**Comment by ccrofts17** [comment]
Oh weird, I’m on CP2077 1.06 and I had a fresh install of CET 1.8.3. When you paste the command into the prompt, does it paste it in as a single line?

**Comment by elastic-soul** [comment]
I paste the whole script into the command line on buttom of the console. That said it is a single line.
The only thing is, if you paste it in it looks like this at the very end of the command line. ".....end    endend"
I need to manually add a space between the last both "end". To make it look like this".....end   end end".

An alternative is to to put a script file into a folder from where the console loads it. But this should not make any difference.
https://www.nexusmods.com/cyberpunk2077/mods/712?tab=posts

**Comment by Xanoreus** [comment]
FYI:

Convert equipped weapons and clothing to legendary
[https://www.nexusmods.com/cyberpunk2077/mods/712](url)

Not sure if you attempting to make your own LUA, but someone has done some nice work for us.

**Comment by krosanreaper** [comment]
> I paste the whole script into the command line on buttom of the console. That said it is a single line.
> The only thing is, if you paste it in it looks like this at the very end of the command line. ".....end endend"
> I need to manually add a space between the last both "end". To make it look like this".....end end end".
> 
> An alternative is to to put a script file into a folder from where the console loads it. But this should not make any difference.
> https://www.nexusmods.com/cyberpunk2077/mods/712?tab=posts

I was having the same issue and this fixed it, just needed a few spaces to get it working.

**Comment by Wolfsblvt** [comment]
Which spaces did you need? I can't execute the script by copy & pasting it either.

Also doesn't work when I try to put the script in a lua file and execute that via console...

**Comment by ccrofts17** [comment]
@Wolfsblvt I just needed 1 space between the last two `end` statements. So just make sure the end of your pasted command reads ...`end end end`
