### ISSUE TITLE
Console doesn't appear when i press the key

### ISSUE THREAD

**Issue by Soixanteneuf** [yamashi/CyberEngineTweaks#395]
**config.json**
![image](https://user-images.githubusercontent.com/58001227/104103474-e0068480-52d4-11eb-9136-020723a445e1.png)

cet_v1.8.3

**cyber_engine_tweaks.log**
![image](https://user-images.githubusercontent.com/58001227/104103517-20660280-52d5-11eb-8980-a0ff880ddbe6.png)

Windows 10 Home x64 10.0

I am using US keyboard keyboard, but when i press '~' nothing happens. The console doesn't appear and even my cursor also doesn't show up. I'm using GOG version, v1.04 which actually should be compatible with c.e.t. I don't have RivaTuner, MSIAfterburner, and Fraps installed.

**Comment by Soixanteneuf** [comment]
Also my windowed mode is windowed borderless

**Comment by yamashi** [comment]
1.04 isn't supported.
