### ISSUE TITLE
Footsteps sounds disappear when OnUpdate and Game.GetPlayer() used together

### ISSUE THREAD

**Issue by mrfox** [yamashi/CyberEngineTweaks#397]
https://youtu.be/-jovHoxz6Lw

CET Version: CyberEngineTweaks1.8.3_hotfix2
CET enabled. Script only consists of the following: 

```
registerForEvent("onUpdate", function(deltaTime)
    player = Game.GetPlayer()
end)
```

After the player dies and clicks Load Last Checkpoint the console shows "Error: ". Once the player respawns there are no footstep sounds.

**Comment by ArdaCsknn** [comment]
I hope this gets fixed because makes some tools unusable.

**Comment by mrfox** [comment]
What's worked for me is to only call it once. 
`player = Game.GetPlayer()`
Having it called a lot of times breaks the footsteps.

**Comment by Nats-ji** [comment]
don't put `player = Game.GetPlayer()` directly inside onUpdate. you don't need to update the player object constantly
