### ISSUE TITLE
If "console" is false, then windows' mouse pointer doesn't be disappeared

### ISSUE THREAD

**Issue by ruukina** [yamashi/CyberEngineTweaks#401]
In the config.json file, if I change "console" to "false", windows' mouse pointer (not the game's one) won't be disappeared.
It might be disappeared when the first run after changing the parameter, but even if it's disappeared, while playing game, windows' mouse pointer would be suddenly shown.

**Comment by WSSDude420** [comment]
Known and fixed, will be in next release.

Can be closed @yamashi
