### ISSUE TITLE
Add socket.http to lua for building a REST API

### ISSUE THREAD

**Issue by raknam** [yamashi/CyberEngineTweaks#405]
Is it possible to add socket.http on the LuaVM to allow to build a REST API within CET?
My idea is to create an API to allow access CET features from a Webinterface and/or Elgato StreamDeck, etc

**Comment by todduk** [comment]
Without know anything about Lua this sounds risky to me. Is Lua sandboxed in any way that would prevent malicious code from downloading malware and executing it or putting it saving it somewhere?

**Comment by WSSDude420** [comment]
Just to add some more "official" note...

We are still kind of on the fence with this one. Right now though, we have no further plans of integrating this and are more leaned towards not having it.

@todduk we have proper sandbox in place, that should not be an issue. Even if they tried to use it for that, they would almost certainly fail, as right now, mods are locked into their own folder without chance to escape, they cannot execute single thing outside of our VM and bytecode along with native modules are prohibited.

Where we see potential issues though is modders pay-walling mods through web APIs, misuse leading to huge network traffic/performance issues (misuse of features can already be observed in some mods, this could be much worse with this in), what-ifs regarding multiple mods trying to use networking at the same time and lastly potential of user tracking (although would be almost certainly fairly limited to say the least thanks to sandbox in place).

Maybe yamashi would be able to think of something else to add, but these were few we were discussing on Discord at some point.

Leaving this opened for now as a reminder of sorts.

**Comment by yamashi** [comment]
One option could be to offer two builds of CET, one with networking and one without and make the one without it the default download.

**Comment by geekosaurusR3x** [comment]
T

> Is it possible to add socket.http on the LuaVM to allow to build a REST API within CET?
> My idea is to create an API to allow access CET features from a Webinterface and/or Elgato StreamDeck, etc

Or having access to a website for registering as fixer / player and link with a quest editor
