### ISSUE TITLE
How to keybind?

### ISSUE THREAD

**Issue by seifer7** [yamashi/CyberEngineTweaks#406]
I know keybinds are not the preferred method, however this must be an instant action that is performed by key-press not via menu.

My question, how does one make a keybind?
I am new to LUA scripting, I have looked and looked but can't figure it out.

This may seem like "if you can't figure out a keybind, you couldn't possibly do anything else" but I assure you that's not the case.

**Comment by seifer7** [comment]
CyberEngineTweaks is using ImGui for it's overlays, menus, buttons, key presses, etc.
Here is a link to the readme within the CyberEngineTweaks repository: [src/sol_imgui](https://github.com/yamashi/CyberEngineTweaks/tree/master/src/sol_imgui)

**Here is an example of how to detect a keypress:**
```
registerForEvent("onUpdate", function()
	if ImGui.IsKeyPressed(0x44, false) then -- Hotkey D
		print('You pressed the letter D')
	end
end)
```

Virtual key codes (such as 0x44 shown above) can be found here: [Virtual-Key Codes (Winuser.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes)

**Comment by yamashi** [comment]
This will be removed in the update, do not rely on this, use registerHotkey
