### ISSUE TITLE
Mouse On-Screen when disabling console on config

### ISSUE THREAD

**Issue by NewJoarpa** [yamashi/CyberEngineTweaks#409]
If you disable the console in the configuration file of CyberEngineTweaks your mouse is visible and shaking in the middle of the screen.

Steps to reproduce:

1. Edit "\bin\x64\plugins\cyber_engine_tweaks\config.json".
2. Change "console" option to false.
3. Save and open the game.
4. The game now has the mouse in middle of the screen.

**Comment by WSSDude420** [comment]
That is known and already resolved, just didnt made it for release.

**Comment by WSSDude420** [comment]
This can be closed now I believe, resolved in master.
