### ISSUE TITLE
Path is off on latest build?

### ISSUE THREAD

**Issue by zingfharn** [yamashi/CyberEngineTweaks#410]
dofile used to execute files in the /mods/ folder, but it seems it doesn't any more?
I have to do e.g. dofile("bin/x64/plugins/cyber_engine_tweaks/mods/scope.lua")

**Comment by cerbero86** [comment]
i have a similar problem too, but maybe worse, it just doesn't load me the lua files, i tried to put them both in scripts and mods, but nothing, it tells me failed to execute dofile, runtime error, and that there is no such path .... yet I did everything to the letter as it says in the guide

**Comment by cgiAlexis** [comment]
I wonder if it's in relation to this other request?
https://github.com/yamashi/CyberEngineTweaks/issues/381

**Comment by Nats-ji** [comment]
Something has broken the pathing in v1.8.4

If you launch the game with admin privilege (If you use Vortex to launch your game), the starting path will be `dofile("./plugins/cyber_engine_tweaks/mods/scope.lua")`
If you launch the game normally, the starting path will be `dofile("./bin/x64/plugins/cyber_engine_tweaks/mods/scope.lua")`

To check your starting path you can type `os.execute("start explorer .\\")` in console.
