### ISSUE TITLE
Need help pls

### ISSUE THREAD

**Issue by lBoRaTl** [yamashi/CyberEngineTweaks#412]
I tried every key on my keyboard and the overlay didn't open, I'm using a laptop with English as it's system language and an azerty keyboard. Can someone help me please ? 🙏

**Comment by Rorschach1219** [comment]
https://wiki.cybermods.net/cyber-engine-tweaks/console/usage

**Comment by lBoRaTl** [comment]
> https://wiki.cybermods.net/cyber-engine-tweaks/console/usage

Thanks, but I already tried them all and none of them worked 😔

**Comment by Senfee-Cheng** [comment]
> 
> 
> > https://wiki.cybermods.net/cyber-engine-tweaks/console/usage
> 
> Thanks, but I already tried them all and none of them worked 😔

I suggest you change the input method to American English, then switch to eng mode, and press~

**Comment by lBoRaTl** [comment]
> > > https://wiki.cybermods.net/cyber-engine-tweaks/console/usage
> > 
> > 
> > Thanks, but I already tried them all and none of them worked 😔
> 
> I suggest you change the input method to American English, then switch to eng mode, and press~

I even tried that, but it didn't work

**Comment by Senfee-Cheng** [comment]
> 
> 
> > > > https://wiki.cybermods.net/cyber-engine-tweaks/console/usage
> > > 
> > > 
> > > Thanks, but I already tried them all and none of them worked 😔
> > 
> > 
> > I suggest you change the input method to American English, then switch to eng mode, and press~
> 
> I even tried that, but it didn't work

https://wiki.cybermods.net/cyber-engine-tweaks/getting-started/installing/troubleshooting

**Comment by lBoRaTl** [comment]
Sad

> > > > > https://wiki.cybermods.net/cyber-engine-tweaks/console/usage
> > > > 
> > > > 
> > > > Thanks, but I already tried them all and none of them worked 😔
> > > 
> > > 
> > > I suggest you change the input method to American English, then switch to eng mode, and press~
> > 
> > 
> > I even tried that, but it didn't work
> 
> https://wiki.cybermods.net/cyber-engine-tweaks/getting-started/installing/troubleshooting

Sadly nothing seems to work 😔
I even tried changing the key bind in config.json to 32(spacebar) and the console didn't show up.

**Comment by WSSDude420** [comment]
What version are you using lol

From 1.9.0 version of CET, there is a popup on first launch asking you to set at least key for toggle.
Without that, you cannot do a thing as overlay is blocking the game till it is set.

**Comment by lBoRaTl** [comment]
Oh I'm on 1.06, gotta wait for the game update to check if it's fixed.

**Comment by Senfee-Cheng** [comment]
> 
> 
> Oh I'm on 1.06, gotta wait for the game update to check if it's fixed.

You can close this issue
