### ISSUE TITLE
Update for Patch 1.1

### ISSUE THREAD

**Issue by dionmunk** [yamashi/CyberEngineTweaks#420]
Game patch 1.1 was released today.

```
[2021-01-22 16:34:24.444] [info] Unknown Game Version, update the mod
[2021-01-22 16:34:24.445] [error] Unsupported game version! Only 1.06 is supported.
```

**Comment by yamashi** [comment]
1.9.0 supports it

**Comment by XCanG** [comment]
@yamashi is it worth to update to it? It seems you remove AMD SMT fix (because it included it patch or support is currently broken?).
I still use 1.04 on GOG and decided to skip 1.05 and 1.06.

**Comment by yamashi** [comment]
> @yamashi is it worth to update to it? It seems you remove AMD SMT fix (because it included it patch or support is currently broken?).
> I still use 1.04 on GOG and decided to skip 1.05 and 1.06.

The game includes the SMT patch out of the box now

**Comment by XCanG** [comment]
Hm, then it look like at this moment this patch is no need. Only one option remain usable is skip start menu.
