### ISSUE TITLE
Can the console support the display of Japanese and Simplified Chinese (UTF-8)

### ISSUE THREAD

**Issue by hulovexu1314** [yamashi/CyberEngineTweaks#425]
The console output shows that Japanese and Chinese characters will not be displayed. Can the console display in Chinese and Japanese in the next version?
There is also a MODS output interface that can also display Japanese and Chinese (UTF-8)
please! Thank you very much!

**Comment by Senfee-Cheng** [comment]
我早都支持了：https://github.com/yamashi/CyberEngineTweaks/pull/407

**Comment by WSSDude420** [comment]
Yeah you can.

Honestly dont know what the other guy said now, but you can for now manually edit config.json after first launch of CET to change FontPath, FontSize and glyph ranges.
There will be GUI for this, is not rn.

Here are glyph ranges currently there (those "ChinneseFull" in if for example is one):
https://github.com/yamashi/CyberEngineTweaks/blob/3d9d42003e5cc9b086c6b3cd375bc985ce762fdb/src/d3d12/D3D12_Functions.cpp#L338

Write that string to ranges inside config.json and it should pick it up I believe.
You would almost certainly need to specify some font which supports it though, keep that in mind.
Default font does not support these i believe

**Comment by WSSDude420** [comment]
This is solved i believe @yamashi :P
