### ISSUE TITLE
No keyboard/mouse response when using CET

### ISSUE THREAD

**Issue by ademlabs** [yamashi/CyberEngineTweaks#426]
Using CP2077 v1.1 with CET 1.9.2 causes the game to lose focus of keyboard and mouse. Game doesn't respond to any keys and desktop mouse cursor floats above. Removing CET allows the game to respond normally. Also, the config.json file is not present in the cyber_engine_tweaks folder.

[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/5859785/cyber_engine_tweaks.log)
[scripting.log](https://github.com/yamashi/CyberEngineTweaks/files/5859786/scripting.log)

**Comment by Senfee-Cheng** [comment]
You should delete all the files and decompress CET
![1](https://user-images.githubusercontent.com/20067002/105571194-1c33ed80-5d89-11eb-9f2f-380fddbc0fe2.png)

**Comment by ademlabs** [comment]
I did delete everything, I do that systematically for any new release that I use. I didn't get that screen upon launch. Let me try that again and see.

**Comment by ademlabs** [comment]
Well, it's working now. Somehow RivaTuner server didn't exit like I thought and caused conflict. I made sure it wasn't loaded and now I can see the CET overlay. Thanks for your help, I'm closing the issue.
