### ISSUE TITLE
[crash] Every 15-20 minutes game crashes (v1.04)

### ISSUE THREAD

**Issue by zzzombie1989** [yamashi/CyberEngineTweaks#43]
Apparently pointless to send requests to CD Project RED, so please help me and many other players who faced with exactly the same error. It appeared after the patch version 1.04. On the release of the game version 1.03 worked perfectly stable. I do not know what there broke the developers, but apparently they do not understand what it is, since it is still not fixed their hotfix 1.04.
The problem is: the game crashes completely randomly after a time interval of 15-20 minutes (sometimes runs a little longer). Not important order of action, but the car ride in my subjective opinion brings the time of the crash closer. I'm sending you all the crash reports that I saved.

[Cyberpunk2077-20201212-193144-2052-4528.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691698/Cyberpunk2077-20201212-193144-2052-4528.zip)
[Cyberpunk2077-20201212-231350-3076-3996.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691700/Cyberpunk2077-20201212-231350-3076-3996.zip)
[Cyberpunk2077-20201213-021543-1232-3104.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691701/Cyberpunk2077-20201213-021543-1232-3104.zip)
[Cyberpunk2077-20201213-024846-12984-3464.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691702/Cyberpunk2077-20201213-024846-12984-3464.zip)
[Cyberpunk2077-20201213-232556-8820-2996.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691703/Cyberpunk2077-20201213-232556-8820-2996.zip)
[Cyberpunk2077-20201215-000251-12204-3976.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691704/Cyberpunk2077-20201215-000251-12204-3976.zip)

**Comment by marceloavf** [comment]
@zzzombie1989 Just disable `memory_pool` in the config.json and you're free.

**Comment by iRTsuki** [comment]
@marceloavf Do you mean the Memory_pool_budgets? I have edited this and it was a bit more stable for a few minutes but same result flatline when it crashed and then it wont open.

**Comment by marceloavf** [comment]
@iRTsuki This mod changes it in runtime, take a look at `\bin\x64\performance_overhaul` in config.json.

The memory_pool option may be taking the wrong values and crashes your game.

**Comment by zzzombie1989** [comment]
> 
> 
> @zzzombie1989 Just disable `memory_pool` in the config.json and you're free.

It's not help.

**Comment by JReming85** [comment]
It looks like your getting EXCEPTION_ACCESS_VIOLATION (0xC0000005) on your crashes.

Typically that means you may have a bad stick of RAM. Try doing a clean install of your GPU drivers first and if that does not resolve it, try doing a RAM test.

RAM Testing Soft
https://www.memtest86.com/ or Windows Memory Diagnostic (Windows Key + R, type “mdsched.exe”)

Recommend the memtest86 over windows though

**Comment by zzzombie1989** [comment]
> 
> 
> It looks like your getting EXCEPTION_ACCESS_VIOLATION (0xC0000005) on your crashes.
> 
> EXCEPTION_ACCESS_VIOLATION (0xc0000005) = It tried to read/write to RAM/MEMORY and failed
> 
> Typically that means you may have a bad stick of RAM or it was trying to read from a location not allocated to cyberpunk2077.exe. Try doing a clean install of your GPU drivers first and if that does not resolve it, try doing a RAM test.
> 
> RAM Testing Soft
> https://www.memtest86.com/ or Windows Memory Diagnostic (Windows Key + R, type “mdsched.exe”)
> 
> Recommend the memtest86 over windows though

My system was passed all test without error: memtest86, linx, prime95...

**Comment by yamashi** [comment]
How much ram do you have?

**Comment by JReming85** [comment]
What CPU do you have, does it support AVX?

**Comment by zzzombie1989** [comment]
> 
> 
> How much ram do you have?

16 GB (2 x 8 GB) 
Crash problem only in v1.04 (I played in v1.03 above 7 hours in a row and game was stable).




> 
> 
> Not sure what to tell you, we have similar specs
> 
> You have the i7-8700 and I have a ryzen 2700
> We both have the RTX2070
> 
> I see you only have 8.5GB Ram (unless I am reading it wrong) I read it wrong 8.5GBx2 and your drive F:\ is using MS basic driver `Microsoft Storage Space Device` looks like you have your Seagate 1TB multipartitioned right? Not sure why its showing as 3 physical disks though.
> 
> Do you have additional ram or swap enabled, the min requirements calls for 8GB alone and anything higher then min is 12-16GB?
> https://cdn-l-mkt.cdprojektred.com/image/16_9_EN_3-_02qt7qdkx3b50kqk.jpg

Game install on ADATA XPG GAMMIX S11 Pro 512 GB
Swap file - 18 GB

**Comment by lorddickfist** [comment]
> Not sure what to tell you, we have similar specs
> 
> You have the i7-8700 and I have a ryzen 2700
> We both have the RTX2070
> 
> I see you only have 8.5GB Ram (unless I am reading it wrong) I read it wrong 8.5GBx2 and your drive F:\ is using MS basic driver `Microsoft Storage Space Device` looks like you have your Seagate 1TB multipartitioned right? Not sure why its showing as 3 physical disks though.
> 
> Do you have additional ram or swap enabled, the min requirements calls for 8GB alone and anything higher then min is 12-16GB?
> https://cdn-l-mkt.cdprojektred.com/image/16_9_EN_3-_02qt7qdkx3b50kqk.jpg

Like Kisak-Valve has stated in the proton thread, its a nvidia related issue for now. I have a 2080ti and I have freezing as well anywhere from 5 mins to 30 mins of gameplay my lgos are much different 
[Uploading steam-1091500.log…]()

**Comment by JReming85** [comment]
> > Not sure what to tell you, we have similar specs
> > You have the i7-8700 and I have a ryzen 2700
> > We both have the RTX2070
> > I see you only have 8.5GB Ram (unless I am reading it wrong) I read it wrong 8.5GBx2 and your drive F:\ is using MS basic driver `Microsoft Storage Space Device` looks like you have your Seagate 1TB multipartitioned right? Not sure why its showing as 3 physical disks though.
> > Do you have additional ram or swap enabled, the min requirements calls for 8GB alone and anything higher then min is 12-16GB?
> > https://cdn-l-mkt.cdprojektred.com/image/16_9_EN_3-_02qt7qdkx3b50kqk.jpg
> 
> Like Kisak-Valve has stated in the proton thread, its a nvidia related issue for now. I have a 2080ti and I have freezing as well anywhere from 5 mins to 30 mins of gameplay my logs are much different
> I also have 32GB of ram 0GB swap
> Uploading steam-1091500.log…

If its NVidia related I should have it as well.  I have a RTX2070 and 1050ti, no freezing and 64GB of ram

**Comment by lorddickfist** [comment]
> > > Not sure what to tell you, we have similar specs
> > > You have the i7-8700 and I have a ryzen 2700
> > > We both have the RTX2070
> > > I see you only have 8.5GB Ram (unless I am reading it wrong) I read it wrong 8.5GBx2 and your drive F:\ is using MS basic driver `Microsoft Storage Space Device` looks like you have your Seagate 1TB multipartitioned right? Not sure why its showing as 3 physical disks though.
> > > Do you have additional ram or swap enabled, the min requirements calls for 8GB alone and anything higher then min is 12-16GB?
> > > https://cdn-l-mkt.cdprojektred.com/image/16_9_EN_3-_02qt7qdkx3b50kqk.jpg
> > 
> > Like Kisak-Valve has stated in the proton thread, its a nvidia related issue for now. I have a 2080ti and I have freezing as well anywhere from 5 mins to 30 mins of gameplay my logs are much different
> > I also have 32GB of ram 0GB swap
> > Uploading steam-1091500.log…
> 
> If its NVidia related I should have it as well.  I have a RTX2070 and 1050ti, no freezing and 64GB of ram

You do not freeze after certain time of gameplay.  Is your game able to use more than 3gb of ram? Whenever I set the pools no matter will only use 3gb max

**Comment by JReming85** [comment]
![image](https://user-images.githubusercontent.com/21246660/102673251-58a87400-4161-11eb-9770-ef8b3bb63586.png)

Also for pools I have everything except for GPU set to 0 (auto config)
![image](https://user-images.githubusercontent.com/21246660/102673273-7970c980-4161-11eb-9ab1-cc931226408e.png)
