### ISSUE TITLE
How to force car exit?

### ISSUE THREAD

**Issue by nibravo** [yamashi/CyberEngineTweaks#430]
Hello everyone,

Looking up the wiki I couldn't find a console command to exit the car. I suffered a bug that trapped my V inside the car on all my save files, because I was AFK for an hour leaving V inside the car without pausing.

Thanks for the help and keep your hard work, this mod is really handy for everyone.

**Comment by seifer7** [comment]
I can't find a way to exit the car using a console command, but I may have a solution.
Open your saved game and run this code in the console:
```
print(tostring(Game.GetPlayer():GetCurrentContext()))
```

You should see a result like this:
```
ToCName{ hash_lo = 0xCF2A54B5, hash_hi = 0xB25AE73D --[[ VehicleDrive --]] }
```

If it says "VehicleDrive" at the end, then I don't know what is wrong.
If it doesn't say VehicleDrive, I may be able to help.

**Comment by nibravo** [comment]
Thank you @seifer7 for your quick response.

The command you suggest outputs:

`ToCName{ hash_lo = 0x21BA9045, hash_hi = 0x79D34978 --[[ VehiclePassenger --]] }

Hope this has a solution.

**Comment by seifer7** [comment]
The context that your's is showing, `VehiclePassenger` implies that you are in the passenger seat.
This would normally be used if you're in a mission scripted area where you are being driven somewhere.
Is your player in the passenger seat or driver's seat? And were you driven somewhere by an NPC?

**Comment by nibravo** [comment]
I am doing the "Gimme Danger" mission where Takemura brings you to Arasaka Industrial Park as a passenger. During the ride I went AFK for an hour and never got out of the car. Now the car is stopped and I'm trapped in the passenger seat. I can move the camera, hack, get into the inventory and menu. Every button is working except the one to get off the car.

The has been my view of the game for days....
![This is my view for days](https://user-images.githubusercontent.com/48862200/105651113-a5841680-5e94-11eb-995d-7bb074beef3c.png)

**Comment by nibravo** [comment]
I tried to teleporting with a console command, but it moves the entire car with me inside haha

**Comment by seifer7** [comment]
If you send me your save file, I can try some stuff later today and let you know how I go.
Your save files are located at `"%userprofile%\Saved Games\CD Projekt Red\Cyberpunk 2077"`
Just send me, presumably, the last one.
Just ZIP up the folder and upload it here: http://copyit.to/s/4e02d2c8B

**Comment by nibravo** [comment]
Thank you very much for your help @seifer7 !!

I uploaded the zip of all the saved files, doesn't matter which one to open because all are in the same place and context. They overwrote all the older saved files.

**Comment by seifer7** [comment]
Got it. Will have a look tonight! I'm intrigued now, I want to figure it out haha.

**Comment by seifer7** [comment]
@nibravo I tried for over an hour but couldn't figure it out :(

If anyone else is interested in trying to figure this out I found that out the following:
```
Game.PrintEffectsOnPlayer()
> Status effects currently on Player:
> GameplayRestriction.VehicleScene
```

From what I can tell, the reason you're unable to get out of the car, draw your weapon etc, is because of that `GameplayRestriction.VehicleScene` status effect applied to the player.

I tried many different ways to try and remove the status effect but none of them worked.
```
Game.RemoveEffectPlayer("VehicleScene") -- No result
Game.RemoveEffectPlayer("GameplayRestriction.VehicleScene") -- No result
ses = Game.GetStatusEffectSystem()
ses:RemoveAllStatusEffectOfType(player:GetEntityID(),"") -- No result
ses:RemoveAllStatusEffectOfType(player:GetEntityID(),"VehicleScene") -- No result
ses:RemoveAllStatusEffectOfType(player:GetEntityID(),"GameplayRestriction.VehicleScene") -- No result
```

I believe that then a "Fast Travel" is performed all Status Effects are removed, therefore if someone can figure out how to use the Fast Travel system to perform a Fast Travel via console, that may fix it.
Here was my attempt:
```
ft = player:GetFastTravelSystem()
ft.PerformFastTravel(1,player)
> sol: runtime error: stack index 2, expected userdata, received number: value is not a valid userdata (bad argument into 'sol::variadic_results(Type*, sol::variadic_args, sol::this_environment, sol::this_state)')

**Comment by nibravo** [comment]
Thank you for the effort @seifer7.
This problem seems deeper than expected.
I think I will have to start over, seems like it's the fastest solution haha...

Again, thank you so much, I'm very appreciated.
