### ISSUE TITLE
Why isn't AMD SMT supported in this patch anymore?

### ISSUE THREAD

**Issue by travySwole** [yamashi/CyberEngineTweaks#431]
Hello, I appreciate all the work that goes into this patch. That being said, I've noticed after 1.7 that the AMD SMT patch has been completely dropped from the mod. I notice this because it no longer shows in the config. I don't believe CDPR has fixed the issue (only 4-6 core CPUS are fixed) as people with 8+ core CPUs (myself having a 3700x 8-core CPU) are being bottlenecked by the game not utilizing all the available CPU processing power. I don't mind using the older version of this mod as it still works with the 1.1 update, but I'm confused as why the mod no longer supports SMT?

**Comment by seccentral** [comment]
can confirm, have a special manual save just for this. at the corner of misty's shop. used to get 71-75 fps previously with patch on. now solid 60.

**Comment by travySwole** [comment]
Glad I'm not the only one. My game is currently updated to 1.1 but I successfully installed the 1.7 version of the mod since the newer versions only focus on the console mod and not the actual performance increase that it was originally designed for. I can confirm that the 1.7 version works with 1.1. It's still a shame that we have to downgrade to a previous version though.

**Comment by WSSDude420** [comment]
Must be placebo guys, that patch was literally not working from 1.05 game version. That is why it was removed.

We do not keep support for older versions so it made no sense to keep it there.

Can be closed I believe.

**Comment by Saymite** [comment]
I can confirm what @travySwole said, 1.7 works fine and makes all of my cores do some work, it's understandable to remove the fix if it's not working properly but for now i'll stick with 1.7 as my frame rates while driving in the city are better.
