### ISSUE TITLE
config.json is not provided in the cet_1_9_2.zip

### ISSUE THREAD

**Issue by callmenemo491** [yamashi/CyberEngineTweaks#432]
as per:   https://wiki.cybermods.net/cyber-engine-tweaks/getting-started/configuration
it mentions:
_The config file is found in: <cyberpunk install path>/bin/x64/plugins/cyber_engine_tweaks/config.json_

however when open the ZIP there is nothing....

![image](https://user-images.githubusercontent.com/13878580/105620524-5cef3d80-5e41-11eb-9ef2-2f144753d9c8.png)

**Comment by alefnull** [comment]
config.json is deprecated in new versions. you can change all settings in-game now using the console overlay and clicking on the settings tab along the top.

**Comment by callmenemo491** [comment]
@alefnull , ah ok  thanks for the clarification.

then the wiki  needs updating then.

**Comment by WSSDude420** [comment]
This is not an issue :P 

We do not package it cause of the reasons alefnull said.

Also, we were effectively reseting settings by each update, this should in general be much better solution I believe.

@yamashi can be closed
