### ISSUE TITLE
Windows cursor over the game window - game isn't working

### ISSUE THREAD

**Issue by nskgamer** [yamashi/CyberEngineTweaks#433]
[cyber_engine_tweaks.zip](https://github.com/yamashi/CyberEngineTweaks/files/5862148/cyber_engine_tweaks.zip)
Your configuration file - **in attachment**
Your Cyber Engine Tweaks version and your Cyberpunk 2077 version - **latest: CET - 1.9.2, game - 1.1**
Your log file - **in attachment**
Your OS version - **Winwows 10 pro 20h2**
A description of your issue:
**When i start the game, i see windows cursor over the game window, i can't do anything in game window, it does not respond to pressing on mouse and keyboard**
[Video](https://youtu.be/huk1nu8IHtM)

**Comment by WSSDude420** [comment]
Is this first run with 1.9.2?

**Comment by WSSDude420** [comment]
Ok, disregard that, almost certainly is...

Some overlay must be intercepting with our hooks. Usually, this is cause by GOG overlay or Rivatuner Statistics Server (you may not even know you have this one, is part of MSI Afterburner)

Try to run it without any overlays active, it should work properly then.

**Comment by WSSDude420** [comment]
With 1.9.0 onwards, users have to set toggle key for overlay (just on first launch) so my best bet is our overlay tries to ask for bind, but some other overlay is causing it to not render.

**Comment by nskgamer** [comment]
> Ok, disregard that, almost certainly is...
> 
> Some overlay must be intercepting with our hooks. Usually, this is cause by GOG overlay or Rivatuner Statistics Server (you may not even know you have this one, is part of MSI Afterburner)
> 
> Try to run it without any overlays active, it should work properly then.

I was sure that I did not have any overlays, since the previous version worked. Thank you! Solved!

**Comment by WSSDude420** [comment]
Can be closed then :P
You have to close it (or owner)
