### ISSUE TITLE
Cyberpunk freezes on startup

### ISSUE THREAD

**Issue by c0ball** [yamashi/CyberEngineTweaks#437]
I installed the Cyberpunk 1.1 patch and version 1.9.2 of CET.
Upon start the hotkey configuration screen of CET pop up, and I am unable to do anything, I can not enter a hotkey or leave the menu and Cyberpunk in the background is stuck on the loading screen.

**Comment by WSSDude420** [comment]
Launch the game in borderless windowed mode.

Run game without CET, change mode, next run with CET should be fine.

There was small regression which was fixed.
So other solution would be to download latest artifact from Actions (select topmost action so last one and at the bottom is zip file)

**Comment by WSSDude420** [comment]
... or just click the link here, points to latest artifact
https://github.com/yamashi/CyberEngineTweaks/suites/1889367382/artifacts/36946922

**Comment by c0ball** [comment]
> 
> 
> ... or just click the link here, points to (as of time of writting) latest artifact
> https://github.com/yamashi/CyberEngineTweaks/suites/1889367382/artifacts/36946922

Thanks, with this version everything works fine
