### ISSUE TITLE
The game crash when CyberEngineTweaks is installed

### ISSUE THREAD

**Issue by DrumSlayers** [yamashi/CyberEngineTweaks#444]
Hello, i was a user of CyberEngineTweaks before Cyberpunk 1.1, everything was working well

I updated to 1.1, removed the whole CyberEngineTweaks then installed Cet 1.9.4 : and the game crash at start.
I tested to just remove the plugin/ folder and the game start again

I'm using GoG

Game crash dump: 
```
Registered crash info file...
InternalVersion: 3.0.3256355  P4CL: 4197920  Stream: //R6.Root/R6.Patch0Hotfix2 
!!!CRASHED!!!
Error Reason: Unhandled exception
Expression: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
Message: The thread attempted to read inaccessible data at 0x0.
File: <Unknown>
Line: 0

"uptimeSeconds":9
"stopThreadID":24744
"exceptionCode":0xC0000005
"processID":13072
"Engine/CommitFailedErrorCode@1#TID=0":"0"
"ResourceLoaderThrottler/NumThrottleTokensAcquired@35472#TID=0":"477"
"ResourceLoaderThrottler/NumThrottleTokensSoftLimit@35471#TID=0":"4294967295"
"Gpu/RayTracing/Enabled@61#TID=0":"true"
"Configuration/Name@2#TID=0":"FINAL"
"Configuration/Name2@3#TID=0":"FINAL"
"Game/Patch@7#TID=0":"1.1"
"Engine/OOM@4#TID=0":"false"
"GlobalMode/IsClosing@5#TID=0":"false"
"GlobalMode/IsGame@17#TID=0":"true"
"Jobs/InitParam/MaxLatentJobs@8#TID=0":"131072"
"Jobs/InitParam/MaxCriticalPathJobs@9#TID=0":"65536"
"Jobs/InitParam/MaxImmediateJobs@10#TID=0":"2048"
"Jobs/InitParam/WorkerThreadStackSizeKB@11#TID=0":"1024"
"Jobs/InitParam/MaxThreads@12#TID=0":"27"
"Jobs/InitParam/AllJobsCriticalPath@14#TID=0":"false"
"Jobs/InitParam/UseJobDebugger@13#TID=0":"false"
"Jobs/Dispatcher/NumDispatcherThreads@15#TID=0":"7"
"Jobs/Dispatcher/MaxHWConcurrency@16#TID=0":"8"
"Gpu/Device/Name@56#TID=0":"NVIDIA GeForce RTX 3070"
"Gpu/Device/Vendor@57#TID=0":"Nvidia"
"Gpu/Device/DriverVersion@58#TID=0":"Nvidia v 46140 [r461_36]"
"Gpu/Device/TotalMemoryMB@55#TID=0":"8043"
"Gpu/Device/UsedMemoryMB@35523#TID=0":"419"
"Engine/InitParams/InteropStartingPort@18#TID=0":"0"
"Engine/InitParams/RenderPreset@19#TID=0":"1"
"Engine/InitParams/QualityLevelName@20#TID=0":"None"
"Engine/InitParams/TextureQualityLevelName@21#TID=0":"High"
"Engine/InitParams/WatchdogTimeoutSecondsOverride@22#TID=0":"0"
"Engine/InitParams/ScriptsSilentCompilation@23#TID=0":"false"
"Engine/InitParams/ScriptsSilentValidation@24#TID=0":"false"
"Engine/InitParams/TweakDBSilentValidation@25#TID=0":"false"
"Engine/InitParams/PvdDumpToFile@26#TID=0":"false"
"Engine/InitParams/ProfilerEnabled@27#TID=0":"false"
"Engine/InitParams/ShowVersionWatermark@28#TID=0":"true"
"Engine/InitParams/WindowCaption@29#TID=0":""
"Engine/PC/SystemName@30#TID=0":"Windows 10 Profe...#<truncated>#"
"Engine/PC/SystemVersion@31#TID=0":"10.0.19042"
"Engine/SafeInit@31034#TID=0":"DebugNetwork"
"Engine/IsHeadless@33#TID=0":"false"
"Engine/VersionWatermark@32#TID=0":"3.0.3256355  P4CL: 4197920  Stream: //R6.Root/R6.Patch0Hotfix2  Jan 15 2021 18:58:22  (FINAL) Total memory: 22923051008 bytes "
"Engine/Scripts/PrimaryBlobModifiedDate@40#TID=0":"132560015612775070"
"Engine/Scripts/FallbackBlobModifiedDate@41#TID=0":"0"
"Engine/Scripts/BlobPathUsed@42#TID=0":"Loaded"
"Engine/Scripts/ShouldCompileScripts@39#TID=0":"true"
"Engine/Scripts/Loaded@43#TID=0":"true"
"##CrashDump##/DumpCrashDataSeconds":"0"
```

Thank you

**Comment by nodeg** [comment]
I can confirm this issue with Cyberpunk Hotfix 1.11 and CET 1.9.4 but with 1.9.5 the issue is gone for me.

**Comment by Steve-xmh** [comment]
Same issue, but I reviewed the installation and noticed that my steam overlay is enabled. So I disabled it then everything is working.
That's my solution, hope that can help you.

[Wiki](https://wiki.cybermods.net/cyber-engine-tweaks/getting-started/installing)

> 5. Ensure all apps that add overlays to the game (Rivatuner, Fraps, Afterburner, Discord, Steam, Gog, Windows 10 Game Bar, Geforce Experience, et cetera) are disabled as the console may not open with overlays active.

**Comment by nodeg** [comment]
I am using the gog version of Cyberpunk 2077. I disabled the gog overlay in the settings (game features -> overlay) but I still got the same error mentioned in my [previous comment](https://github.com/yamashi/CyberEngineTweaks/issues/444#issuecomment-770186976). I am using the gog version` 2.0.35.19 - Beta`.

**Comment by MilesTEG1** [comment]
For me, it was Aferburner and RTSS. After exiting those two, nor more crashes.

**Comment by DrumSlayers** [comment]
> For me, it was Aferburner and RTSS. After exiting those two, nor more crashes.

I tried to exit everything but gog galaxy and the issue still there: the game can't launch with CET

**Comment by MilesTEG1** [comment]
> > For me, it was Aferburner and RTSS. After exiting those two, nor more crashes.
> 
> I tried to exit everything but gog galaxy and the issue still there: the game can't launch with CET

Is it possible you have another overlay software running ? Another mod witch causes the crash ?

**Comment by DrumSlayers** [comment]
> > > For me, it was Aferburner and RTSS. After exiting those two, nor more crashes.
> > 
> > 
> > I tried to exit everything but gog galaxy and the issue still there: the game can't launch with CET
> 
> Is it possible you have another overlay software running ? Another mod witch causes the crash ?

As i said, i litteraly quitted everything then checked to the taskmanager, even gog galaxy overlay is disabled
Also, i cleaned everything from the game (deleted Plugin folder, uninstalled CET, checked game files with GOG, then installing CET) so this is just a fresh install

**Comment by DrumSlayers** [comment]
> I can confirm this issue with Cyberpunk Hotfix 1.11 and CET 1.9.4/1.9.5/1.9.6. Everytime I exit the game to desktop it opens the crash report:
> 
> ![image](https://user-images.githubusercontent.com/12104291/106353588-f314df00-62eb-11eb-8544-18cf763bdeb7.png)

This is an other issue, i had it when CET was working but this is when the game quit so it does not impact the game, my issue is about crashing at startup

**Comment by MilesTEG1** [comment]
> > > > For me, it was Aferburner and RTSS. After exiting those two, nor more crashes.
> > > 
> > > 
> > > I tried to exit everything but gog galaxy and the issue still there: the game can't launch with CET
> > 
> > 
> > Is it possible you have another overlay software running ? Another mod witch causes the crash ?
> 
> As i said, i litteraly quitted everything then checked to the taskmanager, even gog galaxy overlay is disabled
> Also, i cleaned everything from the game (deleted Plugin folder, uninstalled CET, checked game files with GOG, then installing CET) so this is just a fresh install

Ok, then I don't know what made your game crash...

I still have GoG Overlay activated, CET mod and severals others and the game's not crashing anymore at launch.

**Comment by WSSDude420** [comment]
Running as admin seems to help some people on Discord. Dunno which overlay required this when running witht CET now, but it seems to help in some crash scenarios for whatever reason.
