### ISSUE TITLE
issues with 1.11 hotfix

### ISSUE THREAD

**Issue by diras2010** [yamashi/CyberEngineTweaks#447]
Installed the CET as per instructions, started the game, game video frozen, but audio still playing normally

AT+Tabbing allows the imagen on screen to refresh but no pop-up window requesting for setting up a dedicated key for the console

Keyboard functionality gone

closing the game normally or by force and re-starting it brings back video playback, but no keyboard+mouse and no way to open the console

i5-6500 / 32GB RAM DDR4 / GTX 1050ti / Win 10 pro / latest drivers and updates

**Comment by ZeroSuf3r** [comment]
At first would suggest to check .log file for any clues.
cyber_engine_tweaks.log

**Comment by WSSDude420** [comment]
There is mandatory popup at the start, it is prolly not rendering because you have some overlay running in the background doing shit with our hooks. I would start there.

Rivatuner (part of MSI Afterburner), GOG, Steam and Discord are some I know of that cause issues for sure.
