### ISSUE TITLE
[crash] Flatline when opening or within 15-30min of gameplay

### ISSUE THREAD

**Issue by iRTsuki** [yamashi/CyberEngineTweaks#45]
Either I can play a little bit or I cant open the game at all.

-i5 6600k
-rtx 2080 ti
-Steam

Crash logs attached.
[Cyberpunk2077-20201212-122529-1728-5884.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691970/Cyberpunk2077-20201212-122529-1728-5884.zip)
[Cyberpunk2077-20201211-201646-16048-3764.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691973/Cyberpunk2077-20201211-201646-16048-3764.zip)
[Cyberpunk2077-20201211-195350-9588-16620.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691975/Cyberpunk2077-20201211-195350-9588-16620.zip)
[Cyberpunk2077-20201211-195111-16220-17112.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691978/Cyberpunk2077-20201211-195111-16220-17112.zip)
[Cyberpunk2077-20201211-193606-1288-10204.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691980/Cyberpunk2077-20201211-193606-1288-10204.zip)
[Cyberpunk2077-20201211-011016-17024-17188.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691981/Cyberpunk2077-20201211-011016-17024-17188.zip)
[Cyberpunk2077-20201210-182228-6852-13780.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691983/Cyberpunk2077-20201210-182228-6852-13780.zip)
[Cyberpunk2077-20201210-002157-7928-7680.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691984/Cyberpunk2077-20201210-002157-7928-7680.zip)
[Cyberpunk2077-20201209-230116-15424-7928.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691985/Cyberpunk2077-20201209-230116-15424-7928.zip)
[Cyberpunk2077-20201214-173637-12756-16300.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691987/Cyberpunk2077-20201214-173637-12756-16300.zip)
[Cyberpunk2077-20201213-224943-1184-1412.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691988/Cyberpunk2077-20201213-224943-1184-1412.zip)
[Cyberpunk2077-20201213-224837-11368-13488.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691989/Cyberpunk2077-20201213-224837-11368-13488.zip)
[Cyberpunk2077-20201213-224450-2888-13860.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691990/Cyberpunk2077-20201213-224450-2888-13860.zip)
[Cyberpunk2077-20201213-215646-216-14888.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691993/Cyberpunk2077-20201213-215646-216-14888.zip)
[Cyberpunk2077-20201213-215616-17436-18548.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691994/Cyberpunk2077-20201213-215616-17436-18548.zip)
[Cyberpunk2077-20201213-174716-11476-12756.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691995/Cyberpunk2077-20201213-174716-11476-12756.zip)
[Cyberpunk2077-20201213-170531-2252-16788.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691996/Cyberpunk2077-20201213-170531-2252-16788.zip)
[Cyberpunk2077-20201213-165020-9940-5616.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5691999/Cyberpunk2077-20201213-165020-9940-5616.zip)
[Cyberpunk2077-20201213-161011-13612-13652.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692000/Cyberpunk2077-20201213-161011-13612-13652.zip)
[Cyberpunk2077-20201213-160201-14320-13980.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692001/Cyberpunk2077-20201213-160201-14320-13980.zip)
[Cyberpunk2077-20201213-155931-14952-12340.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692002/Cyberpunk2077-20201213-155931-14952-12340.zip)
[Cyberpunk2077-20201213-153249-3940-14588.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692003/Cyberpunk2077-20201213-153249-3940-14588.zip)
[Cyberpunk2077-20201213-153030-2244-560.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692004/Cyberpunk2077-20201213-153030-2244-560.zip)
[Cyberpunk2077-20201213-152926-8648-17752.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692005/Cyberpunk2077-20201213-152926-8648-17752.zip)
[Cyberpunk2077-20201212-212845-14468-8564.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692006/Cyberpunk2077-20201212-212845-14468-8564.zip)
[Cyberpunk2077-20201212-212539-9640-4904.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692008/Cyberpunk2077-20201212-212539-9640-4904.zip)
[Cyberpunk2077-20201212-204907-14728-16136.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692009/Cyberpunk2077-20201212-204907-14728-16136.zip)
[Cyberpunk2077-20201212-202413-9184-9096.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692010/Cyberpunk2077-20201212-202413-9184-9096.zip)
[Cyberpunk2077-20201212-202241-11608-7452.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692011/Cyberpunk2077-20201212-202241-11608-7452.zip)
[Cyberpunk2077-20201212-201433-13896-14096.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692013/Cyberpunk2077-20201212-201433-13896-14096.zip)
[Cyberpunk2077-20201212-201359-8308-6420.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692014/Cyberpunk2077-20201212-201359-8308-6420.zip)
[Cyberpunk2077-20201212-122641-1992-8336.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5692016/Cyberpunk2077-20201212-122641-1992-8336.zip)

**Comment by marceloavf** [comment]
Related to #43

**Comment by iRTsuki** [comment]
Last night i was working mostly. Today i updated my files again with the new updates and now my graphics were stuttering, freezing then my pc crashed. sadly no crash log.

but yesterday when i was working things appeared ok until i tried to stream through discord and then the game flatlined. I have the crash log for that.
[Cyberpunk2077-20201214-201128-7852-11972.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5699030/Cyberpunk2077-20201214-201128-7852-11972.zip)
[Cyberpunk2077-20201214-214209-13116-3904.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5699032/Cyberpunk2077-20201214-214209-13116-3904.zip)
