### ISSUE TITLE
Expose some keybind API to mods so they can read what is bound to some action (if anything)

### ISSUE THREAD

**Issue by mesakomarevich** [yamashi/CyberEngineTweaks#465]
Looking through the code, I can't see any clear way to figure out what keys are bound to what actions. If this functionality does not exist, I think implementing it could be useful for any mod that implements a GUI with, and possibly other cases.

For instance [NPC Tool](https://www.nexusmods.com/cyberpunk2077/mods/898?tab=description) hard-codes the key-binds it uses in it's GUI. This mod is currently broken, but I've fixed it by replacing calls to `ImGui.IsKeyPressed()` with calls to `registerHotkey()` only to find out that I can't seem to update the GUI with the hotkeys chosen by the user.

**Comment by enzo522** [comment]
[SimpleAppearance.zip](https://github.com/yamashi/CyberEngineTweaks/files/5949229/SimpleAppearance.zip)

Hello, mesakomarevich.
If you only want to NPC Tool to work again, try above mod which I've implemented.
I've made it because NPC Tool doesn't exist after update.
Otherwise, just retreive what you want then merge to your project.

The mod I attached has Hotkey functions.
You could set them in Cyber Engine Tweaks overlay.
I recommend you to set "Select Next Item Hotkey" as PageDown, "Select Prev Item Hotkey" as PageUp button.

**Comment by mesakomarevich** [comment]
Hey, @enzo522, I'll take a look at your mod. I have however, already fixed NPC tool for myself and provided a fix on the mod page, but my main concern here is being able to figure out which key the user has bound to which action so that it can be displayed in the UI.

**Comment by enzo522** [comment]
> Hey, @enzo522, I'll take a look at your mod. I have however, already fixed NPC tool for myself and provided a fix on the mod page, but my main concern here is being able to figure out which key the user has bound to which action so that it can be displayed in the UI.

Ah, ha. Great.
It would be better to refer to Cyber Engine Tweak implementation.
Check: https://github.com/yamashi/CyberEngineTweaks/blob/v1.10.2/src/VKBindings.cpp

As you can see "VKBindings::GetSpecialKeyName" function, I think there is no more elegant way to display string of pressed key.

**Comment by mesakomarevich** [comment]
Thanks for pointing that out, @enzo522. Do you know how I would go about actually calling any of those functions from a lua script? I can see in here [Scripting.cpp](https://github.com/yamashi/CyberEngineTweaks/blob/v1.10.2/src/scripting/Scripting.cpp) that a `GetBinds()` function exists, but I have no idea how I would actually invoke it?

**Comment by WSSDude420** [comment]
You cant, but yeah, was requested enough, will be added for sure.
