### ISSUE TITLE
LUA syntax error causes CP2077 to not launch

### ISSUE THREAD

**Issue by pvpxan** [yamashi/CyberEngineTweaks#466]
I had a small syntax error in a secondary mod file. I had forgotten to add an "end"  closing statement in my code in a file referenced in the init.lua file. This caused CP2077 to not launch and took me forever to find out what was causing it.

**Comment by WSSDude420** [comment]
Can you provide some minimal sample to reproduce this please?

Cause what you wrote could mean multiple things lol :P

**Comment by pvpxan** [comment]
Sure. Here is a mod example that causes my game to not launch. I have purposely left out an "end" statement for an if statement. Essentially, I will hit the play button and the game will start for about a second and then the process will end.
[ExampleMod.zip](https://github.com/yamashi/CyberEngineTweaks/files/5939450/ExampleMod.zip)
