### ISSUE TITLE
As Load() was deprecated, can we have an alternative?

### ISSUE THREAD

**Issue by Potato95** [yamashi/CyberEngineTweaks#467]
A lot of mods use/used the load() function (even the one I was doing myself). Seeing as this was deprecated, do we have any new alternatives for using hashes instead of strings? If not, can we at least have a port from the load() from v1.9.6?

**Comment by Nats-ji** [comment]
I think `load` was forgotten when implementing the sandboxing. I believe it will be added back in the next release.
In the meanwhile, I think you can do something like this to replace load():

From:
```lua
f = "print([[I'm a function]])"
load(f)()
```

To:
```lua
f = function() print([[I'm a function]]) end
f()
```
Or:
`f.lua`:
```lua
local f = "print([[I'm a function]])"
return f
```
`init.lua`:
```lua
f= loadfile("f.lua")
f()
```

**Comment by WSSDude420** [comment]
They were not hashes, but bytecode.

Bytecode and native modules were prohibited, there will be no alternative.

We dont want people running bytecode, bytecode can be used to escape sandbox. Same for native modules.

This support will not be added back.
