### ISSUE TITLE
Console history

### ISSUE THREAD

**Issue by yamashi** [yamashi/CyberEngineTweaks#469]
* Store in on disk and reload on next startup.
* Classic controls to browse this history.

**Comment by Si13n7** [comment]
* Option to set output to `Errors/Warnings Only`
   _(Some mods overuse the console print function, but keeping 5000 lines of `XXX enabled` and `XXX disabled` through the use of hotkeys and invisible console is just a waste of resources. The information is often only useful for mod development, not for the players themselves.)_

**Comment by yamashi** [comment]
Please refrain from making unrelated comments on tracking issues.
