### ISSUE TITLE
GDPR: Add possibility to disable telemetry pre-launch or make it opt-in

### ISSUE THREAD

**Issue by vaporwave9** [yamashi/CyberEngineTweaks#470]
I cannot use this software in the EU as it is not GDPR compliant.

Collecting telemetry data by default does NOT conform to the General Data Protection Regulation of the EU that became effective in May 2018. It would be better to disable it per default and tell the user to enable it if he wants to share data with you.

Either you must provide a dialogue box with Yes/No at start-up or make it opt-in, defaulting to off.

Activating telemetry by default (i just tested with my firewall to block all connections) also goes against this basic principle:
https://en.wikipedia.org/wiki/Informational_self-determination

DISCLAIMER:
I *do* believe you that your intentions to add telemetry are purely benign and data collection is really just player counts, but understand the local laws and opt-**out** always takes away self-determination by forcing telemetry being on by default.
For now I am forced to add these to my hosts:
```
#cyber engine tweaks
0.0.0.0 tiltedphoques.com
0.0.0.0 cet.tiltedphoques.com
```

**Comment by bryannolen** [comment]
+1 to this - Telemetry MUST be optional

**Comment by bryannolen** [comment]
That said, reading though your implementation, you are generating a random string at each launch that is not persisted; this is an elegant way to do it.

**Comment by WSSDude420** [comment]
This is GDPR compliant. We do not store any user data.

As @bryannolen mentioned, random ID is generated on start which has absolutely no ties to user and sent to our servers.

What we count is number of active users at some point in time and peak. We dont know which user, from where, etc.

This is more-or-less what Steam does too, and you are not suing them ;) You dont even have a right to opt out of this there, we have an option.

If we were tracking users, sure. But this has nothing to do with any sort of tracking, really just active players and peak players.

**Comment by yamashi** [comment]
No data is collected, it is just a ping to count how many userd we have. It is absolutely GDPR compliant. If you are unhappy feel free to not use the mod.

**Comment by vaporwave9** [comment]
> This is GDPR compliant. We do not store any user data.
> 

Whether or not data is stored is subjective. Just opening a connection and sending data to a server creates metadata in the net.

> random ID is generated on start 
>

A persistent one after generation or at each launch?
If at each launch it is useless.
If persistent a random ID has high entropy.


> If you are unhappy feel free to not use the mod.
> 

I think a local fork and a block in hosts is the superior alternative if you are unhappy with having a mature conversation and downvote and close *WONTFIX* ;)

**Comment by WSSDude420** [comment]
At each launch. As said, this is same thing as Steam does for any game on their store tbh, there is absolutely 0 consent required for this. It is purely to have some numeric value attached to point in time denoting number of players who are in-game running CET.

Literally same as this right here:
https://steamdb.info/graph/

There is 0 actual user data attached. If you think pinging a server is against GDPR, dont use internet mate, cause you are pinging thousands of different computers till you get to the website you want, possibly even more servers if website utilizes content from other ones x)

As also said, we have an option to disable it at least. If this is what really bothers

**Comment by WSSDude420** [comment]
Last reply cause I dont want my braincells to all die out...

https://cet.tiltedphoques.com/stat

This is literally data that is stored on server... 2 integers... Active players, max. recorded players.

**Comment by yamashi** [comment]
> I think a local fork and a block in hosts is the superior alternative if you are unhappy with having a mature conversation and downvote and close WONTFIX ;)

There is no discussion to be had, you misunderstand both GDPR and what we do here, this is 100% GDPR compliant and therefore there is nothing to fix.

**Comment by MythicManiac** [comment]
Fun fact: GDPR does not apply to individuals

I understand the privacy concerns, but as pointed out here already:
1. The telemetry is GDPR compliant
2. GDPR doesn't apply to individuals in the first place
3. No actual user specific information is being transmitted

As such using GDPR as the justification for the requested change is not correct. If you don't like it, feel free to complain, but using GDPR as the basis for complaints will not lead to any productive discussion.

**Comment by vaporwave9** [comment]
Could have saved yourself the troubles if you had common sense.

**Comment by zgal88** [comment]
> Could have saved yourself the troubles if you had common sense.
> What goes around, comes around.

Please be aware, the experimental telemetry was already removed, as per the planned roadmap that was in place, in the latest release. There's no need to harp on a deprecated, no longer relevany, feature.
