### ISSUE TITLE
Is there any way to call static function of game ?

### ISSUE THREAD

**Issue by enzo522** [yamashi/CyberEngineTweaks#471]
Hello, guys.
First of all, thank you all who has contributed to this great mod.
Anyway, while I was implementing a mod in lua, I got a question.

What I tried to do is:
```
staticTweakDBInterface = Game.TweakDBInterface
staticItemIDInstance = Game.ItemID

if staticTweakDBInterface ~= nil and staticItemIDInstance ~= nil then
    local weaponRecord = staticTweakDBInterface:GetWeaponItemRecord(staticItemIDInstance:GetTDBID(weapon:GetItemID()))

    print(tostring(weaponRecord:ItemType():Type()))
    ...
end
```

Every time I call static function of static instance, I got an error below:
```
attempt to index a sol.Scripting::InternalIndex::<lambda_1> value (global 'staticTweakDBInterface')
stack traceback:
```

So I'm wondering that even though accessing to static instance was fine, why I can't call static function of it.
If there is possible way to do so, please let me know.

Thank you.

**Comment by WSSDude420** [comment]
Courtesy of @psiberx (is on our Discord server in cet-tips channel, should be added to wiki sometime I hope too)

-----------------

Static function calls

- Static native function:
`Game.StatsEffectsEnumToTDBID(1)`

- Static scripted function:
`Game['GetMountedVehicle;GameObject'](player)`
 
- Static scripted function with no args:
`Game['Pi;']()`
 
- Static scripted class method:
`Game['StatusEffectHelper::ApplyStatusEffect;GameObjectTweakDBIDFloat'](player, effectID, 0)`

**Comment by WSSDude420** [comment]
Also, this for some generic syntax (courtesy of @WopsS )

-----------

* native - call like Game.func_name(parameters)
* scripted - call like Game['[class_name::]func_name;parameter_types'](parameters)

**Comment by enzo522** [comment]
@WSSDude420 
Oh my god.
Thank you so much for replying.
It would be so helpful for many people.
And thank you for making lua sandboxing.

**Comment by WSSDude420** [comment]
Is in Readme, click on Discord image ;)

**Comment by WSSDude420** [comment]
And generic syntax - i Fd up a bit, we are discussing it now :D

But those samples should be valid at least.

**Comment by enzo522** [comment]
@WSSDude420 
Found ! Thank you again for your help !

**Comment by WSSDude420** [comment]
@enzo522 dunno how you are called on Discord now lol, wanted to ping you there (if you have joined in the meantime that is, kind of assumed you did... maybe you have different name there :P )

I updated the sample part for now with some better info, generic syntax hopefully will follow soon.

I will try to add this to wiki in the evening cause it should definitely be mentioned there too.

https://github.com/yamashi/CyberEngineTweaks/issues/471#issuecomment-775828087

**Comment by enzo522** [comment]
@WSSDude420 
I've just joined CP77 Modding Community !
Actually, the user name is "TheBs65422" without quotes which is same with my Nexus Mods account.
I've also just signed up Discord becaus of Cyber Engine Tweaks Discord though ;)

I'm surprised that there are so many people and so many informations.
I thinj I can't sleep tonight 👍

**Comment by WSSDude420** [comment]
Yeah, everybody lazy to update wiki lol...

You find more info and more people to ask about these on Discord currently unfortunately :/

**Comment by enzo522** [comment]
Yeah, you are right.
I hope many people are able to edit Wiki page.
I think it would be better that some influencing people like you get authority to edit and manage Wiki page.
Then many people will find some fun with making mods. ;))

**Comment by enzo522** [comment]
@WSSDude420 
Although you helped me a lot, I still couldn't find the way to call some static functions ...
The example code you said seems to work:
```
[2021-02-09 21:19:02 UTC+09:00] [info] >  Game['StatusEffectHelper::ApplyStatusEffect;GameObjectTweakDBIDFloat'](Game.GetPlayer(), effectID, 0)
[2021-02-09 21:19:02 UTC+09:00] [error] Error: Function 'StatusEffectHelper::ApplyStatusEffect;GameObjectTweakDBIDFloat' parameter 1 must be TweakDBID.
```

If I pass second parameter properly, the function call would success I guess.
But here is my problem:
```
local Trainer = {
    isInfiniteAmmo = false
}

function Trainer.ToggleInfiniteAmmo()
    Trainer.isInfiniteAmmo = not Trainer.isInfiniteAmmo
end

function Trainer.OnUpdate()
    if Trainer.isInfiniteAmmo and Game ~= nil then
        local player = Game.GetPlayer()

        if player ~= nil then
            local activeWeapon = Trainer.GetActiveWeapon(player)
            
            if activeWeapon ~= nil then
                local sharedData = activeWeapon:GetSharedData()
                local blackboardDefs = Game.GetAllBlackboardDefs()

                if sharedData ~= nil and blackboardDefs ~= nil then
                    local magazineAmmoCount = sharedData:GetUint(blackboardDefs.Weapon.MagazineAmmoCount)
                    local magazineAmmoCapacity = sharedData:GetUint(blackboardDefs.Weapon.MagazineAmmoCapacity)

                    if magazineAmmoCount ~= nil and magazineAmmoCapacity ~= nil and magazineAmmoCount < magazineAmmoCapacity then
                        Trainer.RefillAmmo()
                    end
                end
            end
        end
    end
end

function Trainer.GetActiveWeapon(target)
    if target == nil then
        return nil
    else
        local transactionSystem = Game.GetTransactionSystem()

        if transactionSystem == nil then
            return nil
        end

        local weapon = transactionSystem:GetItemInSlot(target, TweakDBID.new("AttachmentSlots.WeaponRight"))

        if weapon == nil then
            weapon = transactionSystem:GetItemInSlot(target, TweakDBID.new("AttachmentSlots.WeaponLeft"))
        end

        return weapon
    end
end

function Trainer.RefillAmmo()
    Game.AddToInventory("Ammo.HandgunAmmo", 1000)
    Game.AddToInventory("Ammo.ShotgunAmmo", 1000)
    Game.AddToInventory("Ammo.RifleAmmo", 1000)
    Game.AddToInventory("Ammo.SniperRifleAmmo", 1000)
    Game.AddToInventory("Ammo.Special", 1000
end
```

The code above is the feature of Infinite Ammo I've made.
Simply automatically refill ammo when player is shooting.
But I think it would be better that "refill ammo of weapon which I shoot".
Which means, if I shoot handgun, then refill handgun ammo, if I shoot shotgun, refill shotgun ammo, and so on.

So I tried to use the static function of WeaponObject:
```
public final static func GetAmmoType(weapon: wref<WeaponObject>) -> ItemID {
    let weaponID: ItemID;
    let weaponRecord: ref<WeaponItem_Record>;
    let ammoID: ItemID;
    weaponID = weapon.GetItemID();
    weaponRecord = (TweakDBInterface.GetItemRecord(ItemID.GetTDBID(weaponID)) as WeaponItem_Record);
    ammoID = ItemID.CreateQuery(weaponRecord.Ammo().GetID());
    return ammoID;
}
```
The link is here: https://codeberg.org/adamsmasher/cyberpunk/src/branch/master/cyberpunk/items/weapon.swift#L294

As you mentioned, I wrote the code below in my mod:
```
function Trainer.OnUpdate()
    ...
        Trainer.RefillAmmo(activeWeapon)
    ...
end

function Trainer.RefillAmmo(weapon)
    if weapon ~= nil then
        local ammoType = Game['WeaponObject::GetAmmoType;ItemID'](weapon:GetItemID()
    end
end
```

But still got an error:
```
[2021-02-09 21:04:20 UTC+09:00] [error] stack index -1, expected userdata, received nil: value is not a userdata 
stack traceback:
	[C]: in field 'WeaponObject::GetAmmoType;WeaponObject'
	...ugins\cyber_engine_tweaks\mods\SimpleTrainer\Trainer.lua:515: in field 'RefillAmmo'
	...ugins\cyber_engine_tweaks\mods\SimpleTrainer\Trainer.lua:345: in field 'OnUpdate'
	...\plugins\cyber_engine_tweaks\mods\SimpleTrainer\init.lua:33: in function <...\plugins\cyber_engine_tweaks\mods\SimpleTrainer\init.lua:32>
```

If I did something wrong, please let me know :D

**Comment by WSSDude420** [comment]
There is apparently one more dump...

Seems like there are aliases for some things and you have to use those.

https://cdn.discordapp.com/attachments/727800260486758410/794019913425092628/types.zip
Basically, classType in that generic syntax format have to be from dump above...
While paramTypes seem to follow adamsmasher repo I linked before.
Yeah, is kind of complex for "simple thing" :D :/

This seems to work after I inserted it into a bit modified code you posted
```lua
Game['gameweaponObject::GetAmmoType;WeaponObject'](weapon)
```
This also works (for the other overload, though looking at your code, I would prolly stick to first one)
```lua
Game['gameweaponObject::GetAmmoType;ItemID'](weapon:GetItemID())
```
