### ISSUE TITLE
The use of `GetMod(modStr)` mandatory?

### ISSUE THREAD

**Issue by FrancescoMagliocco** [yamashi/CyberEngineTweaks#472]
I don't know how to explain exactly what I'm asking here, so I will just show an example:

**init.lua**
```lua
Foo = require("foo")

registerForEvent("onInit", function()
end)

registerForEvent("onUpdate", function(delta)
end)
```

**Foo.lua**
```lua
Foo = {}

Bar = require("bar")

function Foo.John()
    print("FooJohn")
end

return Foo
```

**bar.lua**
```lua
Bar = {}

function Bar.John()
    print("BarJohn")
end

return Bar
```

I use to be able to open the console and just enter `Foo.Bar()` and `Bar.John()`.  Now I obviously can't.  Is the only way around this now to do this:

**init.lua**
```lua
local Foo = require("foo")

registerForEvent("onInit", function()
end)

registerForEvent("onUpdate", function(delta)
end)

return Foo
```

**Foo.lua**
```lua
local Foo = {}

Foo.Bar = require("bar")

function Foo.John()
    print("FooJohn")
end

return Foo
```

**bar.lua**
```lua
local Bar = {}

function Bar.John()
    print("BarJohn")
end

return Bar
```

Then in the console do `Foo = GetMod(modStr)` which will further allow me to do `Foo.John()` and `Foo.Bar.John()`?

**Comment by yamashi** [comment]
We sandboxed everything so you need GetMod now, yes.
GetMod returns what init.lu returns
