### ISSUE TITLE
Gone from the Nexus - why?

### ISSUE THREAD

**Issue by sschuchlenz** [yamashi/CyberEngineTweaks#475]
Sadly no more automatic updates via Vortex? What's behind the decision and will it be possible to still load the CET ZIPs via Vortex for updates?

**Comment by DankRafft** [comment]
You can always load a mod via Vortex no matter the source. Simply open Vortex's mod tab and drag and drop a file (archive) into the "Drop File(s)" section. If the folder structure in CET's archive stays the same with future updates you don't have to do anything else to make it work. The only thing that won't work anymore is the "Check for updates" feature.

**Comment by yggdrasil75** [comment]
it was removed because the nexus moderation staff asked him to remove the telemetry and he said "no"
