### ISSUE TITLE
Can't Find The Mod On Nexus Anymore?

### ISSUE THREAD

**Issue by Volvith** [yamashi/CyberEngineTweaks#476]
I've been trying to find the mod on Nexus, because i'm trying to install an older version of it (because of the whole telemetry thing), but i can't seem to find it anywhere on the nexus.

Why the hell was it removed?

**Comment by DankRafft** [comment]
Statement on the Nexus page:

> Hidden at 12 Feb 2021, 1:07PM by awpsoleet for the following reason:
> Moving forward the mod will only be available on the official github.
> 
> https://github.com/yamashi/CyberEngineTweaks
> 
> For support please join the discord :)

**Comment by Volvith** [comment]
> 
> 
> Statement on the [Nexus page](https://www.nexusmods.com/cyberpunk2077/mods/107):
> 
> > Hidden at 12 Feb 2021, 1:07PM by awpsoleet for the following reason:
> > Moving forward the mod will only be available on the official github.
> > https://github.com/yamashi/CyberEngineTweaks
> > For support please join the discord :)

I mean that still doesn't answer the question though.
Why was it removed in the first place, especially considering it's one of the most important mods currently available for CP2077 going by sheer volume of dependence?

Plus, being unable to access older versions of the mod is REALLY annoying if you're not playing on the latest version of the game, which, i'm not. :I
I'd at the very least expect all the uploads to be mirrored onto Github, instead of just the latest.

**Comment by DankRafft** [comment]
You can find all past releases on Github: https://github.com/yamashi/CyberEngineTweaks/releases

**Comment by Volvith** [comment]
> 
> 
> You can find all past releases on Github: https://github.com/yamashi/CyberEngineTweaks/releases

Yeah i got it, thanks.

Still wondering what Yamashi's reasoning is for pulling it from the Nexus though.

**Comment by yggdrasil75** [comment]
it was removed because the nexus moderation staff asked him to remove the telemetry and he said "no"

**Comment by Volvith** [comment]
> 
> 
> it was removed because the nexus moderation staff asked him to remove the telemetry and he said "no"

I wouldn't be surprised, but any source on that?

**Comment by yggdrasil75** [comment]
![image](https://user-images.githubusercontent.com/17131496/107778838-8ef21200-6d12-11eb-893c-6e3e2dcfc33e.png)

**Comment by Volvith** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/17131496/107778838-8ef21200-6d12-11eb-893c-6e3e2dcfc33e.png)

Lol, yep, that'll do.

**Comment by Volvith** [comment]
While we're on the subject anyways, what even was the reason to include telemetry to begin with?
It's cited as "we just want to see how many users use CET", but that doesn't explain it still... Was there more to it than that, or just plain old stubbornness?

**Comment by yggdrasil75** [comment]
based on skyrim together fiasco, just stubbornness.

**Comment by yamashi** [comment]
Nexus has policies that do not make sense in my opinion, they won't change them, that's fine by me, they do what they want with their platform as much as I do what I want with my mod. Also seeing an official mod ( @yggdrasil75 ) come and antagonize me personally shows it is something personal.

**Comment by yggdrasil75** [comment]
not personal, just got caught up while skyrim together was still going on with a whole lot of stupidity.
as for the policies, why is "dont track users without a good reason" a bad policy?
I wasnt here to antagonize, I was here to browse the code and see if I could easily compile it without the tracking at all and decided to answer some questions related to nexus while I was here.

**Comment by yamashi** [comment]
We don't track users. End of the story.

**Comment by athompson673** [comment]
@yamashi I understand you may not have intent to track users rather just how frequently you mod is used, but it does raise eyebrows a bit. The mere notion that it _could_ track users is why this is problematic.

I understand you use a new random number each time a user connects, but to add a personal anecdote; my ip address has not changed once for years despite not officially purchasing a static ip from my isp. Many residential isp's don't frequently change, meaning ip address does uniquely identify many users across multiple re-starts of the game.

I get how these analytics can be helpful, and frankly appreciate that you went to the trouble of rolling your own solution which is much less invasive rather than using google analytics, but I also don't disagree with the stance Nexus takes on the issue. Of note, I did not see any changes regarding a notification to users on installation requiring consent to collect telemetry, rather just a mention in the patch notes. GDPR requires positive consent from all users before collecting telemetry, so this could technically be considered a violation.

**Comment by yamashi** [comment]
GDPR covers personal data, no personal data is being gathered/stored therefore GDPR doesn't apply, it has been stated multiple times.

Regarding the IP address, we don't save it, the server is opensource and anyone can check.

**Comment by Volvith** [comment]
I'm still curious as to why you wish to track how many users use your mod in such a way, if it's causing you this much trouble.

If anything, the fact that you're still clinging on to forcing telemetry in your mod despite all this shit surrounding it just makes people more suspicious of your actual intentions, and i think that if you were crystal clear from the beginning what your intentions were, none of this shit would be a problem, at all.

**Comment by yamashi** [comment]
It's simple, I just want to see how many people are using it, nothing more, nothing less. In fact it's also a public endpoint anyone can hit.

**Comment by Volvith** [comment]
> 
> 
> It isn't their place to dictate what I can or cannot do with my code, especially when it is in compliance with all data processing laws.

No actually it is, because you're using their service, which essentially enables them to tell you that your mod doesn't comply with their guidelines and isn't welcome. Gore isn't illegal, but you still won't find it on YouTube.

As for your reaction to the moderating team stepping up and asking you to remove telemetry that serves no purpose other than "i want it in there", even you have to admit that it's little short of childish. I get what you're saying, and i understand that you don't mean any harm in what you're including in your work, nor mean ill with the reasons behind it, but that doesn't mean that it doesn't still paint a picture due to the current privacy-deprived world we currently live in.

I don't want to attack you for your work, and in fact i really am thankful for the hours that you've put in it.
But in my eyes, code needs to serve a purpose other than "eh, i think it's neat" if it's to be put up for public adoption of any kind.
It doesn't matter what it does, nor whether it's legal or not, because at the end of the day, it's about a state of paranoia big-data gathering companies such as Facebook have established throughout the last few years.

It's about painting a picture of someone who cares about the community.
That's what the moderators at Nexus are after.
And i hope you understand that you going "no i do what i want it's legal don't touch me" on that entire community, with a mod that is essentially the #1 work on the entire Cyberpunk 2077 website, paints a bad picture of not just yourself, but of the site as well, and poisons the well of trust in the community.

Again, i'm not saying what you're doing is wrong.
I'm saying that sadly, this isn't a matter of wrong or right, but a matter of opinion of others.
I really hope you see that, because the work you've put into this mod up until this point is staggering, and you've brought so many people joy by allowing them to use your work as a basis for theirs, for their creativity.

I think it'd be a shame if you threw all this away over a simple matter of opinion.
... That's my 2 cents anyways. No hard feelings. Just sad ones...

**Comment by yamashi** [comment]
I agree with you, it's a matter of opinion, I am of the option that their rules are too restrictive considering what the goal is. I am also of the opinion that personal data is an important matter but I can't understand how one can compare an open-source mod that just pings another open-source server and does not store anything to Facebook, sorry but this is actual paranoia, as in the definition you can find in the DSM. 

Like I said they do whatever they want with their platform, it doesn't mean I have to accept it and have to take their disrespect.

I can't admit standing up for myself and not letting a thirdparty dictate what I can or cannot do as childish, I won't set that precedent, what are they going to ask for next? It's a slippery slope and I don't want to take that risk.

Do not worry, github is a fine platform, as for telemetry I was planning on removing it after this weekend, it was just to get an idea of what a week looks like, but the mod will be returning to nexus.

**Comment by Volvith** [comment]
Shame the mod won't be returning to Nexus, i really hope at some point you'll reconsider since i kinda think it's shooting yourself in your own foot, but i get it.
I still think you're stubborn, but i get it, lol.

Anyhow, cheers for the work man. Really appreciate it. :)
