### ISSUE TITLE
I can´t type or click anything in cet

### ISSUE THREAD

**Issue by suf003** [yamashi/CyberEngineTweaks#477]
Hey, sorry to bother, but I downloaded cet but when I open it ingame I can´t type anything in there. I have already tried various versins of cet but the problem always remains the same.
My game is 1.03 version, so maybe that is the problem.
Please let me know if I need to update the game or whether it´s possbile to use this on 1.03, thanks.

**Comment by Meowdance** [comment]
I would definitely use most up to date releae of game. I also encountered this problem when trying to use CET with ReShade. I deleted ReShade and used Freestyle instead and got rid of issues.

**Comment by WSSDude420** [comment]
1.03 was never supported, lowest version that ever was was 1.04.

As it is not feasible to keep all versions supported, we always support latest game version available.

So time to stop pirating and instead buying the game if you want any support ;)
Or find better mirrors, not much else I can say...
