### ISSUE TITLE
CET not found

### ISSUE THREAD

**Issue by RuDraKon** [yamashi/CyberEngineTweaks#478]
CET does not allow to write anything, update error, any solution? version game 1.12

![CET not found](https://user-images.githubusercontent.com/79009735/107851040-1620b200-6e07-11eb-9fdc-fe708330ec7d.png)

**Comment by pussnbootlp** [comment]
I got the same issue. But my CET won't even start and I won't be able to get to the console screen with my hotkey. It seems the game won't even run the code at all. After going back to Telemetry-107-1-10-2-1612738535 that I download from Nexus before the page goes dark, my CET was able to run.

**Comment by WSSDude420** [comment]
Well as message says, your CET must be outdated or game. Game obviously isnt if it is truly 1.12 so your CET must be old.

Any version from 1.10 upward of CET should work with 1.12 game version.

If telemetry was a concern and why you did not update, was removed few moments ago. We got what we wanted out of it already, no need to keep it in any longer now.

**Comment by WSSDude420** [comment]
I will close this issue for now. If you require some further assistance, feel free to reopen.
