### ISSUE TITLE
ASI Loader not working. Message: Unable to load cyber_engine_tweaks.asi. Error: 193.

### ISSUE THREAD

**Issue by JoaoAmadi** [yamashi/CyberEngineTweaks#481]
![Captura de tela 2021-02-14 112341](https://user-images.githubusercontent.com/79049382/107879383-4162da00-6eb7-11eb-9a7d-b161cbc4672e.png)
--
### **I have the latest game and CET versions installed, but since CET_1_10 I have been getting these messages.**

**Before this message pops up, I also get a message saying that cyber_engine_tweaks.asi is not compatible with windows, and my Norton Antivirus scans the file and says it is a threat!!**
--

My game is V1.12 and my latest attempt was with CET_1_11_0. I also don't get any log files. I was getting previously though, even when CET did not work, in CET_1_10_3 for example, I still could access the log files. But not anymore.

I haven't anyone experiencing the same issue anywhere on the web, so if somebody could help me, I would appreciate it very much!!

thankyall!!!

**Comment by JulianVolodia** [comment]
Hey @JoaoAmadi probably your Norton Antivirus changed binary files. Most not sophisticated malware works like that, but this repo is safe (even, 1.11 not have so called telemetry ;))) )

**Comment by JulianVolodia** [comment]
try to add this directory do the exclusions, download it (yes, your Chrome would report back unusual rare download...) and copy. If You have copy of bin dir made after last CP77 upgrade - maybe fallback before retry. ;)

**Comment by JoaoAmadi** [comment]
> try to add this directory do the exclusions, download it (yes, your Chrome would report back unusual rare download...) and copy. If You have copy of bin dir made after last CP77 upgrade - maybe fallback before retry. ;)

ÌT WORKED!!! Thank you so very much good sir!!!

**Comment by JoaoAmadi** [comment]
All I did was add the directory to the antivirus' exclusions and restore the item that it deleted automatically.
