### ISSUE TITLE
Add Fixed Flickering Maps

### ISSUE THREAD

**Issue by cyberbug-2077** [yamashi/CyberEngineTweaks#485]
So, I saw this on discord. Can this be implemented on CET, so we dont hexedit directly to the .exe anymore?

```
80 3D E0 3B 34 01 00 Search this hex value in Cyberpunk2077.exe (My version of game when i test is GOG 1.06)
and edit to 80 3D E0 3B 34 01 01 (Must fix flickering issue with minimap)
```
[discord](https://discord.com/channels/717692382849663036/786902567778910229/795354524562227253)

But, it's for 1.06, maybe you know how to search for 1.12? Thanks

**Comment by yamashi** [comment]
I thought I had fixed this already! Apparently not, will see if I can do this today :)
