### ISSUE TITLE
Is it possible to add support for ImGuiStyleVar.CellPadding enum ?

### ISSUE THREAD

**Issue by enzo522** [yamashi/CyberEngineTweaks#495]
Hello, while I'm implementing CET based mod, I have a suggestion.

![화면 캡처 2021-02-16 021928](https://user-images.githubusercontent.com/19285190/107977391-6150e580-6ffe-11eb-88e4-d9304c615a1e.png)

The picture above is ImGui based UI of it.
You might notice padding above tab bar.
Due to padding of cell, even all the content of Info tab fits, the UI is scrollable.
Here is the picture when I scroll down:

![화면 캡처 2021-02-16 022025222](https://user-images.githubusercontent.com/19285190/107977772-05d32780-6fff-11eb-8c61-a631302b3652.png)

As you can see, gap between window and tab bar is gone.
And I've found CellPadding enum from ImGui source code:
https://github.com/ocornut/imgui/blob/master/imgui.h#L1463

As it is enum of ImGuiStyleVar, so I think it would be possible that UI of my mod is cleaner by calling ImGui.PushStyleVar(ImGuiStyleVar.CellPadding, 0, 0)
So please consider adding process of CellPadding enum.

Thank you.

**Comment by WSSDude420** [comment]
@Nats-ji could you please? 👼

**Comment by enzo522** [comment]
Thank you for quick resolution !
Issue closed.
