### ISSUE TITLE
Be honest, yamashi

### ISSUE THREAD

**Issue by CodeZ1LLa** [yamashi/CyberEngineTweaks#500]
> "Considering @CodeZ1LLa sent a DMCA takedown against Cyber Engine Tweaks to hide the comments about his tool, I feel like this issue deserves to go back into the spotlight. 
> 
> This "mod" is useless, it contains 3 config files and its author think it's ok to try and takedown the modding ecosystem of the game (most mods depend on CET) because he has an image problem and can't milk the $ out of this useless tool.
> 
> _Originally posted by @yamashi in https://github.com/yamashi/CyberEngineTweaks/issues/317#issuecomment-781333819_"

I don't know why you pretend that I sent DMCA against you or CET, while it's clearly saying that it's against the user Dartpower (https://i.imgur.com/ri2y0Df.png), who posted a source code of my tool in the comments. You know that perfectly because you just deleted his comment. 

I contacted him before sending any requests and kindly asked to delete it because I never gave permission to post the source code of my program, and I'm surprised that you as a developer don't understand that it's not OK. He refused to do that and said that he doesn't care about DMCA (it was his idea BTW, he said that GitHub will side with him, so thank him for that). 

Many ennoble people took the code from here, re-packed it with all sorts of suspicious stuff, and tried to post it on Nexus and spread it on the internet. Then people come to me and asking about stuff that doesn't exist in the original tool. I was supposed to take action to protect people who use this tool and trust it.

Moreover, this issue altogether contains nothing but false accusations as it was figured in the comments, and if you would be a honest person, you would delete it yourself, since any normal person should understand, that baseless defamation of someone's image is a very low move. 
Is it OK in your opinion, to post someone's source code without permission? Is it OK to falsely accuse people? 
I had nothing against you or your tool, but since you think that you can fool people and trying to mobilize someone against me, well, let's allow people to see the real situation and who is who.

**Comment by yamashi** [comment]
The DMCA was sent against my repo, I could have lost the repo and everyone else would have lost access as well.

You are very irresponsible and I don't care if people post your code considering it amounts to 50 lines of very basic C#. Are you going to DMCA every hello world repo out there because you wrote an hello world?

Had you contacted me I would have deleted the message containing the reversed sources but no you decided to send a DMCA against MY repo. You are not here to participate in a healthy growth of the modding community, you are only here for your personal gain and do not give a shit about what you have to do to get there. You are a despicable person and yes I want the world to know it, you don't get away with bullshit DMCA requests, had you been a real developer you would know that.

**Comment by CodeZ1LLa** [comment]
> You are very irresponsible and I don't care if people post your code considering it amounts to 50 lines of very basic C#. Are you going to DMCA every hello world repo out there because you wrote an hello world?

No need to dramatize, you would never lose your repo over the comment. If my complaint wouldn't be about the real violation of GitHub policy, the DMCA would be dismissed, but it was approved. So your attempt to make a 3rd-grade joke about "hello world" is pathetic. 

I contacted the person who posted it and asked him to delete it very kindly, despite he acted like a person who doesn't deserve to be treated nicely. He refused to do so and encouraged me to send DMCA, and I did, linking there exclusively his particular comment, not your repo. 

Once again, **be honest**, I saw the email that you received (on your own screenshot that you are sharing btw), and there is a link exclusively to that comment #317, not your repo. Proof: `https://i.imgur.com/Goi5BOI.jpg`, 

So you are trying to manipulate people who read this making them think like I endangered the Cyber Engine Tweaks or sent DMCA against it, which is false and everyone can see it. I have the same email to prove that you are not honest with people. 
Do you really think that people are so unintelligent that you can manipulate them like this? This is disrespectful, to say the least. 
You are trying to shame another developer for protecting his copyrighted code. Really? What is wrong with you? 

BTW, it's very illustrative that you commented and immediately closed the issue attempting to hide.
I thought you are a mature, honest person, and respected you for your contributions. I was wrong. 

Call every single fanboy who felt into your manipulation to dislike it, and like your comments - the eMail from GitHub says it all. and you won't fool anyone else anymore.

**Comment by yamashi** [comment]
![image](https://user-images.githubusercontent.com/672982/108538497-25a86b00-72df-11eb-96c6-13962bf30df9.png)
