### ISSUE TITLE
Debug menu not enabled?

### ISSUE THREAD

**Issue by hellray2k** [yamashi/CyberEngineTweaks#506]
Hi all,

For some reason with the new 1.11.4 release the debug menu is no longer appearing. I normally have it enabled to teleport around the map. But for some reason it is checked as enabled in the engine settings, but it doesn't show up so I cannot teleport around the map anymore? Anyone know what is going on?

Thanks. 
![Capture](https://user-images.githubusercontent.com/79395092/108618174-c165d400-73d0-11eb-880d-ed40738016a1.PNG)
![2](https://user-images.githubusercontent.com/79395092/108618178-c4f95b00-73d0-11eb-8d49-6f89fe0d6e16.PNG)

**Comment by WSSDude420** [comment]
Known and fixed, waitting for merge with master.

See #505
