### ISSUE TITLE
Unable to send keyboard or mouse input when CET is enabled

### ISSUE THREAD

**Issue by gabinuevo** [yamashi/CyberEngineTweaks#507]
Hey folks I followed all the wiki instructions for setting up CET (downloaded via vortex). To confirm, I am on game version 1.12, CET version 1.11.4, have reinstalled the mod, disabled any and all overlays (I think) and have been running all of this on Windows 10, version 20H2. When I enable the mod and start up the game I get the overlay almost immediately at the same time as when the intro video starts, however none of my keyboard or mouse input is accepted within the game, but I can click on the overlay itself.

My log file: 
[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/6019223/cyber_engine_tweaks.log)
My config file:
```
{
    "disable_antialiasing": false,
    "disable_async_compute": false,
    "disable_boundary_teleport": false,
    "disable_intro_movies": true,
    "disable_vignette": false,
    "disable_win7_vsync": false,
    "dump_game_options": false,
    "enable_debug": false,
    "font_glyph_ranges": "",
    "font_path": "",
    "font_size": 13.0,
    "overlay_key": 0,
    "remove_pedestrians": false,
    "skip_start_menu": false
}
```

Would seriously appreciate some help here. Thanks in advance!

**Comment by gabinuevo** [comment]
Well, looks like the error was that I hadn't initialized a key binding on CET. Closing out issue for now

**Comment by WSSDude420** [comment]
Yep, we need to add some prompts so user ideally knows what is happening...

We made it this way so it is easier for user to bind overlay key, which was kind of constant battle till it was introduced (you had to know VK code for your keyboard layout and assign it manually in config file, which was just... not ideal)
