### ISSUE TITLE
CET Support

### ISSUE THREAD

**Issue by SgtKUSMC** [yamashi/CyberEngineTweaks#511]
I've been offline for a bit, updated the game and CET, CET does not open on ~.
Followed the wiki troubleshoot, still does not open on ~
Read piles of discord to no avail
Cannot find the solution here

Requesting assistance.

Thank you

**Comment by yamashi** [comment]
Github issues are not the place for support.

**Comment by SgtKUSMC** [comment]
Then where is? because according to the mod maker this is where I'm supposed to be

"18 February 2021, 1:40PM
If you have an issue, go on the discord and post in the support section for CET.

The discussion section and the comment section here are not for posting bugs or troubleshooting. (so the discussion forum was removed, as was the bug report section because we want the bug reports on the github page or on discord)

Again, the comment section is not for bug reports. If you have an issue, come onto the official modding discord or post on the github page

If installing by vortex, make sure to use hardlink deployment."

**Comment by SgtKUSMC** [comment]
> Github issues are not the place for support.

Then where is? because according to the mod maker this is where I'm supposed to be

18 February 2021, 1:40PM
If you have an issue, go on the discord and post in the support section for CET.

The discussion section and the comment section here are not for posting bugs or troubleshooting. (so the discussion forum was removed, as was the bug report section because we want the bug reports on the github page or on discord)

Again, the comment section is not for bug reports. If you have an issue, come onto the official modding discord or post on the github page

If installing by vortex, make sure to use hardlink deployment.

**Comment by Masamune3210** [comment]
It literally says "If you have an issue, go on the DISCORD and port in the support section"

**Comment by SgtKUSMC** [comment]
> It literally says "If you have an issue, go on the DISCORD and port in the support section"

now read the rest of the sentence

...or post on the github page

"OR"

**Comment by SgtKUSMC** [comment]
> It literally says "If you have an issue, go on the DISCORD and port in the support section"

Re: The Discord page, unfortunately it's impossible for me to post there, for reasons unknown I don't have posting permission, and because I don't have posting permission, I can't ask someone to grant me posting permission, leaving this as the only remaining option.
