### ISSUE TITLE
Crash at startup with CET(no mods)

### ISSUE THREAD

**Issue by Sl4vP0weR** [yamashi/CyberEngineTweaks#515]
`Registered crash info file...
InternalVersion: 3.0.3276551  P4CL: 4218285  Stream: R6.Patch0Hotfix2 
!!!CRASHED!!!
Error Reason: Unhandled exception
Expression: EXCEPTION_ACCESS_VIOLATION (0xC0000005)
Message: The thread attempted to read inaccessible data at 0x0.
File: <Unknown>
Line: 0

"uptimeSeconds":15
"stopThreadID":20448
"exceptionCode":0xC0000005
"processID":2320
"Engine/CommitFailedErrorCode@1#TID=0":"0"
"ResourceLoaderThrottler/NumThrottleTokensAcquired@35020#TID=0":"889"
"ResourceLoaderThrottler/NumThrottleTokensSoftLimit@35019#TID=0":"4294967295"
"Engine/LoadExports/InitialResourcePath@35465#TID=15644":"<0x3A12B4FD1938D5CA>"
"Engine/LoadExports/ResourcePath@35466#TID=15644":"<0x3A12B4FD1938D5CA>"
"Gpu/RayTracing/Enabled@62#TID=0":"false"
"Configuration/Name@2#TID=0":"FINAL"
"Configuration/Name2@3#TID=0":"FINAL"
"Game/Patch@7#TID=0":"1.12"
"Engine/OOM@4#TID=0":"false"
"GlobalMode/IsClosing@5#TID=0":"false"
"GlobalMode/IsGame@17#TID=0":"true"
"Jobs/InitParam/MaxLatentJobs@8#TID=0":"131072"
"Jobs/InitParam/MaxCriticalPathJobs@9#TID=0":"65536"
"Jobs/InitParam/MaxImmediateJobs@10#TID=0":"2048"
"Jobs/InitParam/WorkerThreadStackSizeKB@11#TID=0":"1024"
"Jobs/InitParam/MaxThreads@12#TID=0":"27"
"Jobs/InitParam/AllJobsCriticalPath@14#TID=0":"false"
"Jobs/InitParam/UseJobDebugger@13#TID=0":"false"
"Jobs/Dispatcher/NumDispatcherThreads@15#TID=0":"5"
"Jobs/Dispatcher/MaxHWConcurrency@16#TID=0":"6"
"Gpu/Device/Name@57#TID=0":"NVIDIA GeForce GTX 1650"
"Gpu/Device/Vendor@58#TID=0":"Nvidia"
"Gpu/Device/DriverVersion@59#TID=0":"Nvidia v 46172 [r461_66]"
"Gpu/Device/TotalMemoryMB@56#TID=0":"3962"
"Gpu/Device/UsedMemoryMB@35467#TID=0":"240"
"Engine/InitParams/InteropStartingPort@18#TID=0":"0"
"Engine/InitParams/RenderPreset@19#TID=0":"1"
"Engine/InitParams/QualityLevelName@20#TID=0":"None"
"Engine/InitParams/TextureQualityLevelName@21#TID=0":"Medium"
"Engine/InitParams/WatchdogTimeoutSecondsOverride@22#TID=0":"0"
"Engine/InitParams/ScriptsSilentCompilation@23#TID=0":"false"
"Engine/InitParams/ScriptsSilentValidation@24#TID=0":"false"
"Engine/InitParams/TweakDBSilentValidation@25#TID=0":"false"
"Engine/InitParams/PvdDumpToFile@26#TID=0":"false"
"Engine/InitParams/ProfilerEnabled@27#TID=0":"false"
"Engine/InitParams/ShowVersionWatermark@28#TID=0":"true"
"Engine/InitParams/WindowCaption@29#TID=0":""
"Engine/PC/SystemName@30#TID=0":"Майкросо...#<truncated>#"
"Engine/PC/SystemVersion@31#TID=0":"10.0.17763"
"Engine/SafeInit@30980#TID=0":"DebugNetwork"
"Engine/IsHeadless@33#TID=0":"false"
"Engine/VersionWatermark@32#TID=0":"3.0.3276551  P4CL: 4218285  Stream: R6.Patch0Hotfix2  Feb  3 2021 17:58:02  (FINAL) Total memory: 9602547712 bytes "
"Engine/Scripts/PrimaryBlobModifiedDate@41#TID=0":"132599091968120605"
"Engine/Scripts/FallbackBlobModifiedDate@42#TID=0":"0"
"Engine/Scripts/BlobPathUsed@43#TID=0":"Loaded"
"Engine/Scripts/ShouldCompileScripts@39#TID=0":"true"
"Engine/Scripts/CompileScriptsSuccess@40#TID=0":"true"
"Engine/Scripts/Loaded@44#TID=0":"true"
"##CrashDump##/DumpCrashDataSeconds":"0"
`

**Comment by WSSDude420** [comment]
This is very vague and bad issue description as a whole...
We cannot do much with this, sorry...
