### ISSUE TITLE
Game.CheckFactValue(fact) does not return anything

### ISSUE THREAD

**Issue by forrestkirby** [yamashi/CyberEngineTweaks#516]
# Description

Calling the function `Game.CheckFactValue(fact)` does not return anything. I would expect to get the value for the fact from the FactDB or `0` if no fact is found, as described in the [documentation](https://wiki.cybermods.net/cyber-engine-tweaks/functions/global#game-checkfactvalue-fact). Even if I set a fact value, e.g. `Game.SetDebugFact("sq032_johnny_friend", 1)`, and then try to check it, I do not get any response.

---

By the way, the [documentation](https://wiki.cybermods.net/cyber-engine-tweaks/functions/global#game-checkfactvalue-fact) states the example `Game.CheckDebugFact("q000_vr_tutorial_skipped")` which returns the error `Error: Function 'CheckDebugFact' not found or is not a global.`.

# Reproduce

- install CET as per the wiki
- set up a hot key
- hide the console
- open a save game
- open the console
- run the command `Game.CheckFactValue("q000_vr_tutorial_skipped")` or `Game.CheckFactValue("sq032_johnny_friend")`

# Screenshot

![](https://content.screencast.com/users/forrestkirby/folders/YOOtheme/media/f5bad705-76c2-4ca1-a83c-1b262630672f/03.11.2021-10.44.png)

**Comment by forrestkirby** [comment]
Just found the following comment by chendo on the discord server which solved the issue for me:
“CheckFactValue logs to console, so you need to uncheck Disable Game Log”

**Comment by Elletre** [comment]
Reproducing again in game version 2.1.1 and mod version 1.30.1 but now there is no option Disable Game Log

**Comment by kindofweird05** [comment]
> Reproducing again in game version 2.1.1 and mod version 1.30.1 but now there is no option Disable Game Log

Hey choom, have a solution on this one. Try using an alternative command, worked for me. Game.GetQuestsSystem():SetFactStr("sq032_johnny_friend", 1)

**Comment by jt-borba** [comment]
> > Reproducing again in game version 2.1.1 and mod version 1.30.1 but now there is no option Disable Game Log
> 
> Hey choom, have a solution on this one. Try using an alternative command, worked for me. Game.GetQuestsSystem():SetFactStr("sq032_johnny_friend", 1)

Hey I was not able to get this to work. I open the CET overlay and go into the console and run this but nothing happens. No error, no change in relationship.
