### ISSUE TITLE
(May not be related to this.. still would like to see if you have any idea though)Issue with Cyberpunk suddenly running at 60fps when it previously was at 67-103

### ISSUE THREAD

**Issue by Moogle2403** [yamashi/CyberEngineTweaks#52]
Have asked quite a few tech guys about this and no luck. Its legitimately only Cyberpunk 2077 and no in game caps have been activated including vsync/frame cap. It happened in the last 2 days and the only things I have done were messing with ram OC and gpu clocks which are now back to default (what they were when game was running fine anyway) and still no luck. Reinstalled the game multiple times, no luck. Used DDU, no luck. Checked NVidia control panel profile/resolution/frame caps/vsync, all off. All other games run normally. Other things I have done were apply the AMD patch and fixes for cyberpunk, which I removed and reinstalled the game anyway and tried without.. same issue. I'm truly lost and have no where else to turn :(

**Comment by PuffyVulva** [comment]
Check in geforce experience I know I had issues with a power saving mode in there

**Comment by Moogle2403** [comment]
> Check in geforce experience I know I had issues with a power saving mode in there

You mean nvidia control panel profile?

**Comment by Moogle2403** [comment]
Seems to be a lot of people popping up now with similar issues, must be game related.

**Comment by Kirides** [comment]
Yup. I confirm a very similar issue.

Other People, any my low-power amd notebook do not experience this issue.
i had this issue from the beginning, other people start to have it now.

[Reddit Post](https://www.reddit.com/r/cyberpunkgame/comments/k0llf4/pc_questions_megathread/gftyxv1/?utm_source=reddit&utm_medium=web2x&context=10)
[YouTube Video example with overlay](https://www.youtube.com/watch?v=h2NH7WgUCyU)

**Comment by Moogle2403** [comment]
> Yup. I confirm a very similar issue. (has nothing to do with this project)
> 
> Other People, any my low-power amd notebook do not experience this issue.
> i had this issue from the beginning, other people start to have it now.
> 
> [Reddit Post](https://www.reddit.com/r/cyberpunkgame/comments/k0llf4/pc_questions_megathread/gftyxv1/?utm_source=reddit&utm_medium=web2x&context=10)
> [YouTube Video example with overlay](https://www.youtube.com/watch?v=h2NH7WgUCyU)

Yeah I remember seeing you, posted on your post. Mine wasnt like this before but over the past 2 days it happened... honestly cant remember when exactly but it may have been after I fresh installed windows.

**Comment by thefunkygibbon** [comment]
I'm not sure whats happened either, it was running at 70fps for me near constant up until yesterday... now its dropping down to 30 quite often :(   need to investigate further

**Comment by P-G19** [comment]
Check  v-sync or other frame-limiting options.. after that, Try disabling all different overlays and try again (MSI Afterburner + Rivatuner, Nvidia in-game overlay) then try again.

**Comment by Moogle2403** [comment]
> Check v-sync or other frame-limiting options.. after that, Try disabling all different overlays and try again (MSI Afterburner + Rivatuner, Nvidia in-game overlay) then try again.

as I said... tried all that basic shit.

**Comment by Kirides** [comment]
> Check v-sync or other frame-limiting options.. after that, Try disabling all different overlays and try again (MSI Afterburner + Rivatuner, Nvidia in-game overlay) then try again.

Fresh restart of windows, nothing running except cyberpunk, GOG version of the game.
No difference. Still runs like crap.

menu is still locked to ~60 fps and game runs with basically locked 50fps.
RTX 2080 + 3700x

**Comment by thefunkygibbon** [comment]
rolled back to using the hex hacked exe and removed the vram from config and also removed all of this tweek.   back to 60-70fps for a couple hour session.   I think there must be something going on with this latest version

**Comment by Moogle2403** [comment]
> rolled back to using the hex hacked exe and removed the vram from config and also removed all of this tweek. back to 60-70fps for a couple hour session. I think there must be something going on with this latest version

may be a different issue.

**Comment by Moogle2403** [comment]
Was hoping new nvidia driver may fix but no such luck.

**Comment by Vladabdf** [comment]
RTX 2070S + 3700X + 48GB RAM @3200MHz
After about 2-3 hours of playing, the game locks itself to a lower frame rate. I imagine it's got to do with some sort of cache somewhere. I'm able to hit between 55-70 fps pretty much at all times, but after a couple hours the game seems to cap out around 40-ish in most scenarios. I've left the game running while standing still and this happens as well.
