### ISSUE TITLE
Crash when highlighting text in console input box

### ISSUE THREAD

**Issue by Hawkpath** [yamashi/CyberEngineTweaks#530]
Highlighting text in the console input box and then navigating through input history with the up/down keys leads to an inconsistent selection state and crashes.

To reproduce:
1. Type "a long line here" and press enter.
2. Type "line2" and press enter.
3. Press the up arrow twice to go back to "a long line here".
4. Select all with ctrl+A.
5. Press the down arrow to go to "line2". Notice that the selection does not reset.
6. Try typing any character and the game should crash.

**Comment by WSSDude420** [comment]
This should be fixed in my PR.

Sombra reported this earlier this week on our Discord.

**Comment by WSSDude420** [comment]
Is now fixed in master, will be included in next release.
