### ISSUE TITLE
Typo in the CET Introduction wiki page code example

### ISSUE THREAD

**Issue by Hawkpath** [yamashi/CyberEngineTweaks#531]
I would've done a pull request for this myself but I couldn't find the wiki source anywhere. In the [introduction page](https://wiki.cybermods.net/cyber-engine-tweaks/introduction), line 10 of the example says `IsPlayNaked.Player` but should be `IsPlayerNaked.Player`. I thought it was worth mentioning because new users will probably copy/paste this code like me and may get tripped up by it.

**Comment by Hawkpath** [comment]
Also, if you're interested at all, I could possibly lend a hand in improving the documentation. I'm just learning the API and noticed the docs are (understandably) lacking in some areas. I had to go into the source code a bit and search the discord to find some info I needed.

**Comment by WSSDude420** [comment]
If you are on Discord, just ask for wiki access in wiki-discussion channel :)

Editting on wiki is private, we use gitbooks.

Ill close this when i change this.

**Comment by WSSDude420** [comment]
Well, if you want to help, do as I wrote and someone will add you hopefully x)
