### ISSUE TITLE
Release 1.12.1?

### ISSUE THREAD

**Issue by axefrog** [yamashi/CyberEngineTweaks#533]
I notice there's an uncompiled "release" for 1.12.1. My mod is broken until GameOptions is back in play, and people are asking me about when the mod will be fixed, so I thought I'd ask about how things are going with CET regarding 1.12.1. Thanks!

**Comment by manavortex** [comment]
+1, I'd love to have it :)

**Comment by yamashi** [comment]
It was a release candidate, 1.12.1 will be released tomorrow if all tests go well

**Comment by manavortex** [comment]
Amazing, looking forward to it. Utterly failed compiling the master myself, like a noob ;)

**Comment by axefrog** [comment]
Thankyou! And thanks for all your hard work! :)

**Comment by WSSDude420** [comment]
As you have GitHub account, you can download artifacts from Actions tab on this repo.

Just switch to Actions tab, open latest action (topmost) and scroll down. There should be a zip file you can download and use.

It is not advised though, as we sometime break mods with updates, as you may have experienced. :)

**Comment by manavortex** [comment]
I didn't even see that you have a pipeline XD Thank you

**Comment by WSSDude420** [comment]
1.12.1 released!
