### ISSUE TITLE
disable_antialiasing no longer works since 1.2 patch

### ISSUE THREAD

**Issue by Ophiolith** [yamashi/CyberEngineTweaks#542]
Pretty-much exactly as it says.  TAA is forced on regardless of whether option is true or false since 1.2 patch.  Using CET 1_12_1.  Would be extremely grateful if this was fixable, as it looks like CDPR altered how user configuration files are stored, and appear to be actively working against efforts to let users disable it through modding.

**Comment by WSSDude420** [comment]
Was fixed long time ago (should be at least)
