### ISSUE TITLE
Input window not popping up

### ISSUE THREAD

**Issue by dominicdev1** [yamashi/CyberEngineTweaks#554]
**Cyber Engine Tweaks** version- This one: [](https://wiki.cybermods.net/cyber-engine-tweaks/getting-started/installing)

**Cyberpunk 2077** version- 2.0.37

**Windows 10-** 2021-04 Cumulative Update Preview for Windows 10 Version 20H2 for x64-based Systems (KB5001391)

I installed the mod and the game opened without a problem...but the window to use it did not pop up and I could not find a way to use any scripts in other places. 

Thank you!

**Comment by WSSDude420** [comment]
These issues are for Discord. Only bug reports here please. This is not a bug most probably but some issue with either your install or game versions or third party apps we have 0 control over.
