### ISSUE TITLE
CET is not launching when opening the game

### ISSUE THREAD

**Issue by bharathvbcr** [yamashi/CyberEngineTweaks#556]
I have installed Cyber Engine Tweaks using vortex, but the CET is not opening. I even tried installing it manually by copying the bin contents into the games bin even then it not opening . 

Need help in open the CET window

**Comment by EFERRRRR** [comment]
got the same issue

**Comment by bharathvbcr** [comment]
Bro 

> got the same issue

Bro install the same version of Cyber Engine Tweaks my game version is 1.2 so I installed 1.2 supported version its working for me now
