### ISSUE TITLE
[Crash][100%] Game freezes at the same exact location without crash reports

### ISSUE THREAD

**Issue by ClemColl** [yamashi/CyberEngineTweaks#56]
Hey guys,
I finally found a 100% reproducible freeze, at least on my machine.

**How to reproduce**
Start the saved game, run forward and you will crash at the exact same spot (the wire rack on the ground that draws a line)  or after some seconds if you stay within the area

**Save**
[CrashSave.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5695688/CrashSave.zip)

**Crash Dump**
For some reasons, no crash report gets created, maybe it's because my game freezes and the CrashReporter isn't called?

**Specs**
i7 8700K (no OC)
GTX 1080Ti
16Go RAM 3200 Mhz
Installed on an SSD

**Additional infos**
I have tried many fixes (including your patch), crash occurs on high and ultra graphics.
I do have many crashes, the game is unplayable for me but this is the only one I can reproduce 

Edit:
Still freezing with release 0.7.0

**Comment by Scavw** [comment]
Same problem. Game freezes when entering the area. If teleport to the point inside the area, the game will freeze in loading screen.
