### ISSUE TITLE
Game crashes when the mod is installed

### ISSUE THREAD

**Issue by taewyth** [yamashi/CyberEngineTweaks#569]
So as long as the mod is present, the game crashes on the logo sequence (best case scenario, I get to the the trademarks for 1/2 a second).

I'm using the GOG version, 1.23, all overlays are disabled and I'm runing in borderless window

**Comment by WSSDude420** [comment]
Copy this into Explorer address bar and package last folder there into zip and upload it please.
Provided Crash Reporter popped up. These are its reports.

`%appdata%\..\Local\REDEngine\ReportQueue`

That should contain memory dump from crash + few text files with additional info. No personal info should be there in case this is what worries you.

**Comment by OrByR** [comment]
[Cyberpunk2077-20210630-195548-9128-2432.zip](https://github.com/yamashi/CyberEngineTweaks/files/6744685/Cyberpunk2077-20210630-195548-9128-2432.zip)
Here is my dump of the same issue - using steam version however.

**Comment by OrByR** [comment]
`Symbol search path is: srv*
Executable search path is: 
Windows 10 Version 19043 MP (16 procs) Free x64
Product: WinNt, suite: SingleUserTS
19041.1.amd64fre.vb_release.191206-1406
Machine Name:
Debug session time: Thu Jul  8 22:36:53.000 2021 (UTC - 5:00)
System Uptime: 0 days 0:48:35.954
Process Uptime: 0 days 0:00:09.000
................................................................
................................................................
.................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(1438.137c): Unknown exception - code e24c4a04 (first/second chance not available)
For analysis of this file, run !analyze -v
ntdll!NtWaitForMultipleObjects+0x14:
00007ffd`0c7ad974 c3              ret
0:012> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*** WARNING: Unable to verify timestamp for cyber_engine_tweaks.asi
*** WARNING: Unable to verify timestamp for nvwgf2umx.dll
*** WARNING: Unable to verify timestamp for Galaxy64.dll
*** WARNING: Unable to verify timestamp for bink2w64.dll
*** WARNING: Unable to verify timestamp for nvcuda64.dll

KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.Sec
    Value: 2

    Key  : Analysis.DebugAnalysisProvider.CPP
    Value: Create: 8007007e on PC

    Key  : Analysis.DebugData
    Value: CreateObject

    Key  : Analysis.DebugModel
    Value: CreateObject

    Key  : Analysis.Elapsed.Sec
    Value: 18

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 174

    Key  : Analysis.System
    Value: CreateObject

    Key  : Timeline.OS.Boot.DeltaSec
    Value: 2915

    Key  : Timeline.Process.Start.DeltaSec
    Value: 9


NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

CONTEXT:  (.ecxr)
rax=00007ffcf1db8790 rbx=0000000002620378 rcx=000000007075e7d0
rdx=00007ff78c38bb80 rsi=0000000000060000 rdi=0000000002620378
rip=00007ffd0a2c4ed9 rsp=000000007075ef10 rbp=0000000002620378
 r8=00007ff78c478996  r9=000000007075e820 r10=00007ff78c389af9
r11=00000001a2835ff0 r12=0000000000000000 r13=00000000030e0010
r14=00000000026203b8 r15=0000000000000000
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000202
KERNELBASE!RaiseException+0x69:
00007ffd`0a2c4ed9 0f1f440000      nop     dword ptr [rax+rax]
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffd0a2c4ed9 (KERNELBASE!RaiseException+0x0000000000000069)
   ExceptionCode: e24c4a04
  ExceptionFlags: 00000001
NumberParameters: 0

PROCESS_NAME:  Cyberpunk2077.exe

ERROR_CODE: (NTSTATUS) 0xe24c4a04 - <Unable to get error code text>

EXCEPTION_CODE_STR:  e24c4a04

STACK_TEXT:  
00000000`7075ef10 00007ffc`d7590388 : 00000000`00000000 00000000`026203b8 00000000`00000000 00000000`02620378 : KERNELBASE!RaiseException+0x69
00000000`7075eff0 00000000`00000000 : 00000000`026203b8 00000000`00000000 00000000`02620378 00000000`02657340 : cyber_engine_tweaks+0x490388


SYMBOL_NAME:  cyber_engine_tweaks+490388

MODULE_NAME: cyber_engine_tweaks

IMAGE_NAME:  cyber_engine_tweaks.asi

STACK_COMMAND:  ~12s ; .ecxr ; kb

FAILURE_BUCKET_ID:  APPLICATION_FAULT_e24c4a04_cyber_engine_tweaks.asi!Unknown

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {6abcc207-5adc-5f92-c3e3-aa26f08a0652}

Followup:     MachineOwner
---------`

**Comment by WSSDude420** [comment]
Should be fixed in master.

You should be able to download artifact for testing from here once job is finished
https://github.com/yamashi/CyberEngineTweaks/runs/3147589194

**Comment by OrByR** [comment]
Tested and working!
