### ISSUE TITLE
[Feature Request] Check mod folder for archives

### ISSUE THREAD

**Issue by MaximiliumM** [yamashi/CyberEngineTweaks#570]
Hey,

I need to be able to check if a specific archive is in mod folder or not. I don't need to be able to list mod folder content or anything like that. Just a function that returns true or false if I check for specific archive.

Reason:
I want to add expansions/addons to AMM, but I need to be able to check if user has archive installed or not to offer good user experience. Or else, user would remove archive and then AMM wouldn't know and then user experience is broken.

Thanks!

**Comment by WSSDude420** [comment]
I dont know if I understand you correctly now...
If you have something inside your mod folder, you can check easily for that (io exposed for your mod folder).

If you mean extra mods of sorts, you can use GetMod for this.
Functionality should be there for these.

Closing this as invalid for now, if you want something else, try to explain it a bit better cause I personally dont see anything to add/change atm.
