### ISSUE TITLE
Commands don't activate when i type them after 1.23 update.

### ISSUE THREAD

**Issue by almil53** [yamashi/CyberEngineTweaks#571]
I got the patch for the cyber engine tweaks mod but after I had it installed, I tried to type in a command to add money as a test to see if it was working ok (Command: Game.AddToInventory("Item.money",9000)), but the command didn't work, i tried other commands as well but none of those worked either. i don't know what went wrong

**Comment by WSSDude420** [comment]
It should have been Items not Item. I suppose you mistyped other commands as well. Noone is reporting issues with commands with latest version available.

Know this is older one that noone apparently replied to but worth mentioning.

`Game.AddToInventory("Items.money",1234) -- Gives 1234 eddies`
