### ISSUE TITLE
Game update cause menu to not open

### ISSUE THREAD

**Issue by MasterYaro27** [yamashi/CyberEngineTweaks#584]
Steam updated my game auto and now I cant open the mod menus, either its just not compatible or the update made it so the command key changed with me not knowing a way to change it myself.

**Comment by ThibaultVlacich** [comment]
This mod is always non-compatible with new updates. [It's hard-written](https://github.com/yamashi/CyberEngineTweaks/blob/master/src/Image.cpp#L73) to not embed itself on an unknown game version.

The mod will have to be updated to work.

**Comment by Pav-Osmolski** [comment]
@MasterYaro27 It is also stated in the README.md which version CyberEngineTweaks is compatible with.

Patience good Sir! 1.30 changes are incoming and there has already been a commit to take care of it.

Release page will update soon enough.
