### ISSUE TITLE
AMM issue: "Player in Menu - Tools only works in game" when in photo-mode

### ISSUE THREAD

**Issue by TheRealWitblitz** [yamashi/CyberEngineTweaks#586]
Perhaps jumping the gun a bit. The issue is more likely to be with AMM than CET, this is just a heads-up in case you know of a work-around.

![amm-issue](https://user-images.githubusercontent.com/25457067/130126195-a6128004-76a3-44ff-a910-bbae504234ec.jpg)

**Comment by yamashi** [comment]
Don't think this is CET related indeed
