### ISSUE TITLE
support for 1.3 patch

### ISSUE THREAD

**Issue by okolovmark** [yamashi/CyberEngineTweaks#588]
hi, when will work with the 1.3 patch?

**Comment by dgkepel** [comment]
There is a beta release for 1.30. See [here](https://github.com/yamashi/CyberEngineTweaks/releases/tag/v1.16.0)

**Comment by okolovmark** [comment]
@dgkepel thanks, i try use cheats but get error:
what do i incorrect?
![image](https://user-images.githubusercontent.com/11903241/130146074-ed0363b8-4ac5-4017-b81a-2a2679a53311.png)

**Comment by okolovmark** [comment]
Game.AddToInventory("Items.MantisBladesLegendary",1)
already found, thanks
