### ISSUE TITLE
CET menu won't pull up after a short time of game running

### ISSUE THREAD

**Issue by mechcentric** [yamashi/CyberEngineTweaks#590]
likewise, tap to (un)holser via advanced control ceases to function, frequently. getting it to work at all this quickly after a major patch with significant changes to core game files is impressive; keep being amazing!
EDIT: using toggle walk key makes it work again

**Comment by WSSDude420** [comment]
Noone seems to be reporting sth like this outside you so I would probably blame some mod you use. If you can repro this with clean CET (that is nuking mods folder inside cyber_engine_tweaks), feel free to reopen.
