### ISSUE TITLE
Chinese in a Lua script can not be displayed correctly in the front end

### ISSUE THREAD

**Issue by 2217936322** [yamashi/CyberEngineTweaks#591]
Chinese in a Lua script can not be displayed correctly in the front end

**Comment by 2217936322** [comment]
![QQ截图20210820100151](https://user-images.githubusercontent.com/19187989/130167565-af8edc36-3dbf-4f7a-bc98-b8f897968a47.png)
![2](https://user-images.githubusercontent.com/19187989/130167611-f43bfc68-994a-4bc1-91f4-6f68de99cccf.png)

**Comment by yamashi** [comment]
As far as I know you have to pass a font manually to CET to get chinese fonts to display

**Comment by WSSDude420** [comment]
Inside cyber_engine_tweaks.json, you have to manually set font which supports these characters + specify glyph range to "SimplifiedChinese" or something along those lines.
