### ISSUE TITLE
V1.16.0 with game patch 1.3 no longer reporting keypresses.

### ISSUE THREAD

**Issue by WhiteElf** [yamashi/CyberEngineTweaks#593]
The function:
    Observe("PlayerPuppet", "OnAction", function(self, action)
is no longer reporting any keypresses/game actions other than "IconicCyberware" which is usually associated with the 'E' key.

'action' is not returning anything at all other than for 'IconicCyberware'.

**Comment by WSSDude420** [comment]
Try with artifact from here
https://github.com/yamashi/CyberEngineTweaks/actions/runs/1149654349

**Comment by WSSDude420** [comment]
But there were some script changes so it is possible signature changed...
A foreword. A lot of things broke on top cause of them changing scripts.

**Comment by WhiteElf** [comment]
I gave that one a go.  The artifact didn't appear to make any difference though.  The only thing reported by action is still only 'IconicCyberware'.  Thanks for looking.

**Comment by yamashi** [comment]
You have to manually register input events now, they made changes to the events they attach in scripts.
```lua
Observe('PlayerPuppet', 'OnGameAttached', function(self)
    self:RegisterInputListener(self, 'Forward')
    self:RegisterInputListener(self, 'Back')
    self:RegisterInputListener(self, 'Right')
    self:RegisterInputListener(self, 'Left')
    self:RegisterInputListener(self, 'ToggleSprint')
    self:RegisterInputListener(self, 'Jump')
    self:RegisterInputListener(self, 'ChoiceScrollUp')
    self:RegisterInputListener(self, 'ChoiceScrollDown')
end)
```
