### ISSUE TITLE
The TPP mod for third person view causes camera view to malfunction

### ISSUE THREAD

**Issue by Futske** [yamashi/CyberEngineTweaks#595]
Whenever you try to activate the TPP mod for 3rd person view, V immediately crouches, forcing the camera view either to the ground or into the sky. The wrong view is persistent because it will stay like that even after you restart the game. To get the first person view back, you need to load another save that has V somewhere different than where you caused the camera view to go insane.

**Comment by yamashi** [comment]
This is a problem with TPP
