### ISSUE TITLE
Grephic Issue?

### ISSUE THREAD

**Issue by ADeadMoth** [yamashi/CyberEngineTweaks#596]
I put my game on high, msaa 16x, 1920 1080 ish, rtx on and stuffs, after installing the script via vortex, hardlink deployment, everything looks like it was at lower resolution, edge on everything, I use the codes on what i need and remove the script, everything back to normal, anyway to fix this or did i missed something?

**Comment by WSSDude420** [comment]
Check under CET options if you did not disable antialiasing. I suppose you did.

This seems to disable DLSS as well as TAA.
