### ISSUE TITLE
CET updated for 1.30 broke my mod with no errors.

### ISSUE THREAD

**Issue by MathiewMay** [yamashi/CyberEngineTweaks#607]
Hi, with the new CET update that support 1.30 a mod i made was broken with seemingly no reason or error in the log after doing some debugging concluded that everything in my mod's script is fine maybe its something about CET that changed which i am unaware of, [here is the main function of my mod](https://gist.github.com/MathiewMay/0958f9507ea59b6cbfd6f759c7fd41c5) you can get the full version on the mod page https://www.nexusmods.com/cyberpunk2077/mods/2894 if you look at the main function you will see that at the end it sends a request for a vendor menu which would usually just open the menu but for some reason it does not with no errors in the console or the log file.

**Comment by yamashi** [comment]
Do you use 1.16.2 or earlier?

**Comment by MathiewMay** [comment]
> Do you use 1.16.2 or earlier?

i tried using 1.16.2 but some other users said that 1.16.1 also had the issue.

**Comment by psiberx** [comment]
It's not caused by CET update but the game changes. You have to provide scenario name as a second param.
```lua
Game.GetUISystem():RequestVendorMenu(vendorDataPanel, 'MenuScenario_Vendor')
```

**Comment by MathiewMay** [comment]
> It's not caused by CET update but the game changes. You have to provide scenario name as a second param.
> 
> ```lua
> Game.GetUISystem():RequestVendorMenu(vendorDataPanel, 'MenuScenario_Vendor')
> ```

Hi, thanks for your help, i was unaware that changes made to the games function would affect cyber engine tweaks.
