### ISSUE TITLE
Dump Game Options returns partially wrong data

### ISSUE THREAD

**Issue by Azulath** [yamashi/CyberEngineTweaks#608]
For Cyberpunk 2077, I'm using this user.ini file:

```
[RayTracing]
GeometryUpdateBufferSizeMB = 8176
ScratchBufferSizeMB = 8176

[RayTracing/BottomLevelCache]
Budget = 2146435072

[Streaming]
EditorThrottledMaxNodesPerFrame = 3000
MaxNodesPerFrame = 1800
MinStreamingDistance = 50.000000
```

I wanted to verify that all those parameters are working and also find additional parameters I could edit. Thus, I've used the in game console to retrieve those values and the Dump Game Options functionality. According to the console, every stat I've changed should also be used by the game which is also reflected by my VRAM allocation.

However, according to the Dump Game Options functionality, the following values are being used:

```
[RayTracing]
GeometryUpdateBufferSizeMB = 64
ScratchBufferSizeMB = 32

[RayTracing/BottomLevelCache]
Budget = 2146435072

[Streaming]
EditorThrottledMaxNodesPerFrame = 500
MaxNodesPerFrame = 300
MinStreamingDistance = 1.000000
```

Thus, only RayTracing/BottomLevelCache is used while all other values stay at default settings. Any idea what's causing this?

**Comment by yamashi** [comment]
Likely related to bounds they set.
