### ISSUE TITLE
"disable async compute" with 1.31 doesn´t work

### ISSUE THREAD

**Issue by e2Kiwi** [yamashi/CyberEngineTweaks#614]
I started the 1.31 and with "disable async compute" "true" and the game exits itself on the loading screen where the intros would start.
I use a GTX 1070 and used "async off" the whole time.
Is this a bug from the v1.31 patch or an issue with cet 1.16.4 ???
Nice work, i´m a great fan of your awesome work !!!!

**Comment by Sybrite25** [comment]
I'm getting the same issue on a clean install. If I enable "disable async compute" the game crashes to desktop

**Comment by matteopompei** [comment]
Same issue here, if Async Compute is disabled the game (1.31) crash on startup.

**Comment by yamashi** [comment]
We are going to assume this is either fixed in 1.5 or not needed anymore, feel free to reopen if it's still an issue.
