### ISSUE TITLE
Interface not Working

### ISSUE THREAD

**Issue by DeathDiamond720** [yamashi/CyberEngineTweaks#615]
The mod itself is functioning, but the interface will not load. My log says that I have a 'Kiero error' and in bindings.json it just says 'null'. The mod functioned fine before 1.31 and I'm sure everything is up to date, I also have no overlays and I'm in windowed fullscreen. I am also on the GOG version of the game with Windows 10.
[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/7174625/cyber_engine_tweaks.log)

**Comment by yamashi** [comment]
Discord for support
