### ISSUE TITLE
Crashing on launch (Win7 issue?)

### ISSUE THREAD

**Issue by Silver-Nebula** [yamashi/CyberEngineTweaks#630]
I spent quite a bit of time trying to troubleshoot this and can't help but wonder if it's a Win7 issue. But from the changelog, it looks like CET is supposed to work for Win7 (v1.9.4 says "Fixed Windows 7 flatlining").

ISSUE: After installing CET with Vortex, my game will crash on launch (flatline error).

BACKGROUND:
- I am using hard links in Vortex.
- I am able to load the game with other mods but not CET.
- I am on the latest version of the game (1.31)
- I have the latest VS C++ Redist and Nvidia drivers
- On Win7 with latest updates

**Comment by yamashi** [comment]
Closing, re-open if troubleshooting and support didn't solve the issue. With crashdumps.
