### ISSUE TITLE
Crash on startup with any mod in bin directory on latest version of CET

### ISSUE THREAD

**Issue by grumpy247** [yamashi/CyberEngineTweaks#633]
Following problem with the steam version:

The game starts without CET/redscript.
The game starts with latest CET/redscript. (overlay opens up, no problems)
The game starts with latest CET/redscript and mods that use the archive or r6 directory.
The game crashes as soon as there is any mod under the bin directory. (I've tried a couple different mods, FGR, Edgerunner Bazaar, etc)
"Cyberpunk 2077\bin\x64\plugins\cyber_engine_tweaks\mods"
[Cyberpunk2077.exe-20211201-014919-7304-4208.txt](https://github.com/yamashi/CyberEngineTweaks/files/7629848/Cyberpunk2077.exe-20211201-014919-7304-4208.txt)

I joined the "Cyberpunk 2077 Modding Community Discord" and tried an older version that was posted by user "Apart" and the game started without any errors.

I hope you can make anything out of this and have a nice day!

**Comment by yamashi** [comment]
Not enough information to reproduce, re-open if this happens again with latest.
