### ISSUE TITLE
Game will not launch after install

### ISSUE THREAD

**Issue by undeadbydawn** [yamashi/CyberEngineTweaks#640]
I got a checksum error installing vcrun2019 so used --force to install anyway, now can't launch at all
Running Garuda (Arch) KDE with 5.15.11-tkg-cacule, Steam non-beta, Proton-GE 6.21-2, everything else bleeding edge

**Comment by yamashi** [comment]
Not enough information, also linux is a grey area, we don't officially support it.
I would say having a bad vcruntime likely has something to do with it
