### ISSUE TITLE
CET disables input whenever it is used or enabled

### ISSUE THREAD

**Issue by FuZe64** [yamashi/CyberEngineTweaks#644]
I installed CET on 1.31 to use mods. I thought a mod was causing it but CET was the culprit (disabled everything but CET).

**Comment by WSSDude420** [comment]
Definitely problem with some other overlay. Look through troubleshooting guide, there are listed some known ones to cause issues with workarounds for few.

If it doesnt help, we cant help you much...
Is something that is on your computer.

https://wiki.redmodding.org/cyber-engine-tweaks/getting-started/installing/troubleshooting
