### ISSUE TITLE
CET 1.19.0-rc - causing system mouse cursor to stay visible.

### ISSUE THREAD

**Issue by Bloodvixen** [yamashi/CyberEngineTweaks#648]

**Comment by Bloodvixen** [comment]
Situation:
> Update of CP2077 to patch 1.5
> Update of CET to 1.19.0-rc
- System mouse cursor stays on the screen all the time during gameplay.

> Removal of CET
- System mouse cursor is hidden during gameplay.

> Downgrade to CET 1.17.0
- System mouse cursor is hidden during gameplay.

Fingers cross, that CET 1.17.0 will work with update 1.5 and upgraded mods.

**Comment by ineedbettername** [comment]
> 

Workaround: Toggle the CET menu with End/Tilde whatever your hotkey is set to, then close it.

**Comment by FransBouma** [comment]
Might be helpful to add this. I use these in Cyberlit, a lighting mod that's part of my camera tools. When setting both ignoreInput and disableMouseConfine to 1/true, the mouse can be used using imgui (be sure to call ClipCursor(NULL)), and setting these to false/0 removes the mouse again if I hide it through imgui's usual bool:

```
   class InputSystem
    {
    public:
        PAD(0x154);                     // v1.5
        bool m_disableMouseConfine;     // 0x154    (patch 1.5)
        PAD(0x23);                      // 0x155
        bool m_ignoreInput;             // 0x178    (patch 1.5)
    };

    class CGameEngine
    {
    public:
        PAD(0xC0);
        InputSystem* m_inputSystem;
```

**Comment by Bloodvixen** [comment]
Thank you for the suggestions, everybody. Thank you for your hard work yamashi.
