### ISSUE TITLE
Crashed after 1-5-10 mins

### ISSUE THREAD

**Issue by map788** [yamashi/CyberEngineTweaks#649]
Problem after playing game. using i7-7700k, gtx 1080
crashing after 1-5-10 min

x64 win, r.c for 1.5
[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/8079465/cyber_engine_tweaks.log)

**Comment by yamashi** [comment]
Note: potential d3d12 memory leak caused by resizing the viewport too many times

**Comment by IffyChan** [comment]
@yamashi I think that's how it is. I enabled UseD3D8to9 in global.ini and the crashes stops

**Comment by yamashi** [comment]
Wow that's weird, have no idea how this could cause issues but thanks a lot for reporting this, I will try to understand what's going on

**Comment by yamashi** [comment]
Likely fixed by newer hooking method
