### ISSUE TITLE
Game crashed at launch with CET 1.19.0 on Windows 7

### ISSUE THREAD

**Issue by NovaRain** [yamashi/CyberEngineTweaks#654]
After I updated my game to 1.5, I removed all CET script mods and installed CET 1.19.0, but the game just crashes at launch with empty cyber_engine_tweaks.log. I can start/play the game just fine if I remove CET.

Not sure if it's because I'm still playing the game on Windows 7 (yes, I know new game updates after June 15 will no longer support Win7, but at least for now it should still work). Does the current CET still support Win7?

**Comment by yamashi** [comment]
This doesn't really help and sadly I do not have a win7 box to debug this, unless someone with win7 with programming knowledge decides to take a look I doubt we will find a solution :/

**Comment by PunkPyro** [comment]
Mine has the same issue on win10. after the 1.5 update the game crashes on launch until i disable CET. i updated to 1.19 but it still wont launch.

**Comment by liquidLun** [comment]
So I had this issue to and first thought it was the sound driver bug, after ruling them out as well as my Graphics drivers I updated Windows. That all didn't solve the problem. I deactivated CET on Vortex and the game still crashed. I Uninstalled Vortex and reset the Bin folder, at that point the game was working again. That is with no mod. Now I installed CET manually by copying the files into Bin as instructed, game still crashes at launch. After that I browsed the CET wiki installed the windows pack C++ deactaved all overlays that I could think of and activated the ASLR stuff. Nothing. Still crashing. Additionally I like to add that I only get a Crash report from the game it self, while I can't find a crash report in the CET folder.

Crash Report:
[report.txt](https://github.com/yamashi/CyberEngineTweaks/files/8100524/report.txt)

**Comment by NovaRain** [comment]
> This doesn't really help and sadly I do not have a win7 box to debug this, unless someone with win7 with programming knowledge decides to take a look I doubt we will find a solution :/

That's unfortunate. I was hoping CET would support win7 in the same way as the main game (dropping the support after June 15). Maybe put a note that the current CET doesn't support win7 on the release page, so people like me won't try to run it and keep being puzzled why a fresh game just crashed?

**Comment by PunkPyro** [comment]
just downloaded the 10gb update and the 1.19.1 CET update but its still the same problem. the game wont launch until i disable CET.

**Comment by NovaRain** [comment]
@yamashi 
A silly question, is it possible for you to create a test build with some components (like mimalloc and sqlite3) downgraded while keeping the current 1.5 compatibility? Maybe it's because the updated components don't work on win7 or something.

**Comment by yamashi** [comment]
Yes it's possible, add the version you want in xmake.lua and then follow build procedure : https://github.com/yamashi/CyberEngineTweaks/blob/master/BUILD.md

**Comment by NovaRain** [comment]
Tried the latest build and it worked! Thank you!
