### ISSUE TITLE
Patch 1.5 Hotfix released

### ISSUE THREAD

**Issue by Menno5** [yamashi/CyberEngineTweaks#657]
Probably known already, but just in case: a Patch 1.5 hotfix is released and CET needs an update (again).
The hotfix is a surprise everywhere.

[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/8102105/cyber_engine_tweaks.log)

**Comment by jeroll3d** [comment]
RIP CET :(

**Comment by tryadelion** [comment]
yup - went to take a shower and t won't launch :(

**Comment by yamashi** [comment]
Update coming in a few minutes
