### ISSUE TITLE
Cyber engine tweaks fails to load on Linux when calling ImGui_ImplDX12_CreateDeviceObjects

### ISSUE THREAD

**Issue by shmerl** [yamashi/CyberEngineTweaks#660]
With latest update to patch 1.5 and CET for 1.5 (v2), it stopped working for me on Linux (wine-staging, vkd3d-proton).

version.dll override exists as before (native, builtin) and it all worked fine with 1.31.

I see this in `cyber_engine_tweaks.log`:

```
[error] [Initialize] D3D12::Initialize() - failed to initialize ImGui!
[error] [InitializeImGui] D3D12::InitializeImGui() - ImGui_ImplDX12_CreateDeviceObjects call failed!
```
Where is this function `ImGui_ImplDX12_CreateDeviceObjects` from? It doesn't seem to be a standard Windows one.

**Comment by freeshrugsxd** [comment]
Same here. The two lines are repeated over and over in the logs. 

scripting.log reports all mods are loading successfully but apparently ImGui cannot be initialized.

**Comment by njibhu** [comment]
As extra information for the bug, or a possible workaround:
It's working fine for me on wine7.1 + dxvk 1.9.4

**Comment by shmerl** [comment]
The game is using vkd3d-proton, not dxvk. I was testing it with very recent build of the master branch: https://github.com/HansKristian-Work/vkd3d-proton/commits/master

**Comment by yamashi** [comment]
Leaving this open if someone wants to help, but none of the devs working on this project run a Linux box and we don't officially support proton, so hopefully someone else can figure it out/provide a fix.

**Comment by shmerl** [comment]
@yamashi: Is there some way to increase the logging level, to get more info what exactly is failing?

**Comment by yamashi** [comment]
This is an error in imgui which is an external library, sadly we don't have a way to add logging to it easily

**Comment by shmerl** [comment]
Since it's about DX12, it could be  vkd3d-proton bug. I can try using some older tag for it.

**Comment by shmerl** [comment]
Yeah, found it: https://github.com/ocornut/imgui/blob/master/backends/imgui_impl_dx12.cpp#L439

**Comment by shmerl** [comment]
I see it's using d3d compiler. I remember Wine's implementation of it was incomplete. But strange thing that it was working fine with 1.31.

**Comment by shmerl** [comment]
Just a hunch, may be installing native d3dcompiler_47 might help.

**Comment by shmerl** [comment]
Yes, I just confirmed it! Installed ` d3dcompiler_47` with winetricks and plugin GUI is working now!

![image](https://user-images.githubusercontent.com/310927/154866342-4dd0fabd-59e9-4749-b0eb-1cacce194c5b.png)

**Comment by shmerl** [comment]
I'll close this, since it's the usual `d3dcompiler_47` not fully implemented kind of issue.

**Comment by shmerl** [comment]
You might want to add such kind of workaround to your wiki somewhere, to help other Linux gamers who use your plugin in case they'll have hard time finding this bug report.

**Comment by shmerl** [comment]
For those who want to dive into it, supposedly `D3DCompile` is marked as implemented:

https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/d3dcompiler_47/d3dcompiler_47.spec#l2

So it shouldn't be failing here? I'll file a Wine bug.

**Comment by shmerl** [comment]
Oh, I see it now:

```
     if (SUCCEEDED(hr))
     {
         FIXME("HLSL shader compilation is not yet implemented.\n");
         hr = E_NOTIMPL;
     }
```

https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/d3dcompiler_43/compiler.c#l765

That's unfortunate.

**Comment by alochmar** [comment]
Thanks for looking into this, been pulling my hair out over this exact issue.

**Comment by yamashi** [comment]
I added a note on the wiki regarding this, I do not know the proper way of doing this, if someone feels inspired and wishes to write a small explanation on how to install d3dcompiler_47, I would gladly add it to the wiki!

**Comment by shmerl** [comment]
I installed it with winetricks.

Assuming your wine binary is located $PATH1/wine, and your Wine prefix is $PATH2

```
WINEPREFIX="$PATH2" WINE="$PATH1/wine" winetricks d3dcompiler_47
```

Proton users would need to adjust it to use protontricks.

**Comment by alochmar** [comment]
Installing d3dcompiler_47 through protontricks did not work for me though (using whatever versions were used in Proton-7.2-GE-2, presumably 7.2 something). @shmerl, did you install any other libraries besides this one and version?

**Comment by shmerl** [comment]
No, just that one d3dcompiler_47. Without it you can also observe in wine log that error I pointed out above: `HLSL shader compilation is not yet implemented.`. Check if that still happens, may be your protontricks didn't work.

**Comment by alochmar** [comment]
Turns out I had gamemoderun in the Steam launch options, this apparently caused the library to not load properly for some reason. Removing it did the trick! Thanks @shmerl for the help and @yamashi & co for this wonderful mod!

**Comment by shmerl** [comment]
Looks like `D3DCompile` is now hooked into latest Wine code:

https://source.winehq.org/git/wine.git/blob/HEAD:/dlls/d3dcompiler_43/compiler.c#l940

I'll test if it works with Wine 7.5 without native override.

**Comment by shmerl** [comment]
Just confirmed - it works without the native override now with Wine 7.5!

**Comment by shmerl** [comment]
Just tested it - while the game isn't crashing anymore, you still need the override because the plugin UI isn't working either.

**Comment by SebiTimeWaster** [comment]
i got it to work with proton GE:

1. update wine, protontricks, winetricks
2. kill the directory `.../steamapps/compatdata/1091500`
3. install cyber engine tweaks from their documentation (remember to set the `version` verb, but do not install `vcrun2019`)
4. run `protontricks 1091500 --gui --force`
5. select `select the default wineprefix` then `install a windows dll or component`, select `d3dcompiler_47` and `ok`. exit out of protontricks (`cancel`, `cancel`)
6. install Glorious Eggroll proton. this is a bit tricky, only a handful of proton versions (no matter if GE or vanilla) work with cyberpunk for me, version `GE-Proton7-9` is the newest that works for me, try them all when in doubt.

that should be it, if you followed all instructions correctly it should *crossedfingers* work

**Comment by SebiTimeWaster** [comment]
@yamashi maybe it makes sense to update the documentation? or give me access to the linux section and i'll do it.

**Comment by shmerl** [comment]
Current Wine has major problems with stack size, so CP2077 is completely broken with it. But that's unrelated to Cyberengine tweaks. It still needs d3dcompiler_47 regardless.

**Comment by SebiTimeWaster** [comment]
> Current Wine has major problems with stack size, so CP2077 is completely broken with it. But that's unrelated to Cyberengine tweaks. It still needs d3dcompiler_47 regardless.

yeah, that would explain why such a weird small sub selection of protons work for me...

**Comment by shmerl** [comment]
I'd avoid putting such details as using GE and etc. in the wiki for cyberengine tweaks specifically. Just put in the detail that native `d3dcompiler_47` is still required.

**Comment by SebiTimeWaster** [comment]
> I'd avoid putting such details as using GE and etc. in the wiki for cyberengine tweaks specifically. Just put in the detail that native `d3dcompiler_47` is still required.

why? it may not be related to CET, but it will still keep people from having success and generate support tickets like this. at least saying that the user should try different versions can improve success greatly.

and yes, wine is in flux, which requires constant tinkering/updating.

**Comment by shmerl** [comment]
Because not everyone is using GE and there a bunch of variants of Wine. It's not really CET task to prescribe a specific wine version. Just to give guidance on what is needed (for any kind of wine) to work, which is basically `d3dcompiler_47`.

**Comment by WSSDude420** [comment]
If you want to add something to the wiki, feel free :)
We are not locking people from edits, invite is pinned in publically accessible relevant Discord channel.

Here is a copy:
https://app.gitbook.com/invite/-MP5ijqI11FeeX7c8-N8/H70HZBOeUulIpkQnBLK7

Just dont merge changes ideally without someone looking at it first. (would be good if you went to our Discord and pinged someone when you do changes in #wiki channel (direct invite to the channel: https://discord.gg/DHGB4PgY )

@shmerl @SebiTimeWaster

**Comment by SebiTimeWaster** [comment]
> Because not everyone is using GE and there are a bunch of variants of Wine. It's not really CET task to prescribe a specific wine version. Just to give guidance on what is needed (for any kind of wine) to work, which is basically `d3dcompiler_47`.

ok, forget please that i said a specific version, i'm sorry. but not mentioning something that can help people because they may not have used it before is... bad service.

**Comment by shmerl** [comment]
I'd say it's good enough to simply give notes on simply how to install `d3dcompiler_47` to a prefix. Either using winetricks or protontricks and etc.

Not everyone is using Steam setup either btw, for example with GOG version of the game.

**Comment by SebiTimeWaster** [comment]
> Not everyone is using Steam setup either btw, for example with GOG version of the game.

there is an extra section for the GoG version...

**Comment by freeshrugsxd** [comment]
@SebiTimeWaster Just tuning in to say that CET works fine for me even with the latest version of GE-Proton ([`GE-Proton7-14`](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-14)) as long as `d3dcompiler_47` is installed. Can't say I had any problems on previous versions, too.

**Comment by shmerl** [comment]
Just to follow up, since Wine started implementing d3dcompiler features.

As of Wine 7.16, you still need native `d3dcompiler_47` for cyberengine tweaks to work. Just tested it without it and it didn't start.

**Comment by shmerl** [comment]
I just tested Cyberpunk 2077 with CyberEngine Tweaks using built in d3dcompiler_47.dll (Wine 8.19) and it works fine! So there is clearly some progress to it and it doesn't need the native override anymore.
