### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by MOOOOs** [yamashi/CyberEngineTweaks#666]
Game crashed if i leave console open for 1 minute

**Comment by MOOOOs** [comment]
Still crashing with newest update

**Comment by MOOOOs** [comment]
and also to add it crashes when im not closing console and getting game minimised i think its only cause it crashing game

**Comment by yamashi** [comment]
Closing as this doesn't seem related to the mod, make sure you don't have other mods with issues.

**Comment by MOOOOs** [comment]
I have only this mod... only use console

**Comment by MOOOOs** [comment]
> Closing as this doesn't seem related to the mod, make sure you don't have other mods with issues.

I have only this mod only use console...

**Comment by MOOOOs** [comment]
To reproduce issue open console and minimise game and after 10 seconds or more it will crash

**Comment by yamashi** [comment]
We have tried to reproduce the bug and have never been able to...

**Comment by MOOOOs** [comment]
Ant way to find out why it's crashing any logs for it ?
