### ISSUE TITLE
[Suggestion] Add commands to get rid of bugs to wiki 

### ISSUE THREAD

**Issue by DarkReaper231** [yamashi/CyberEngineTweaks#671]
Sometimes stuff in the game gets bugged. Glitch visual effects getting stuck, UI elements getting stuck, combat music loops getting stuck and so on. But many of these bugs can be solved with engine tweaks commands. Is the netrunner glitch effect stuck? Just run command `Game.RemoveEffectPlayer("BaseStatusEffect.NetwatcherGeneral")`

This is example when I got rid of glitch effect on my screen using this command. But there are surely other commands for example to get rid of the relic malfunction notification if it gets stuck on the screen which happened to me a lot but I never figured out command to get rid of it.

I think it would be cool to have section on the wiki that would help people fixing audio or visual bugs. I often find myself restarting the whole game just to get rid of stuck UI element even tho it should be possible to get rid of it with engine tweaks commands.

For example, today I met audio glitch when the combat music was always looping even when combat ended and I'm sure there is command to stop music completely which would probably fix it up.

**Comment by DarkReaper231** [comment]
Btw I really need help. I need to stop that stupid combat mix. The only option is to rollback several missions back before the combat mix played.

**Comment by Hatsushira** [comment]
Did you try to visit a Joytoy? Triggering a new cutscene could solve the music issue. At least it did as I had similiar problems.

**Comment by yamashi** [comment]
This should be a standalone mod
