### ISSUE TITLE
[DEBUG] OnAppearanceChangeFinishEvent

### ISSUE THREAD

**Issue by iSiide** [yamashi/CyberEngineTweaks#674]
I have this bug into my CET scripting.log when i launch my game,  i try delete all mods and it does not work...

[DEBUG] Switch to TPP
[DEBUG] OnAppearanceChangeFinishEvent

Cyberpunk 2077 Ver 1.5 hotfix 2
Cyber Engine Tweaks 1.19.3

Thanks for your help

**Comment by yamashi** [comment]
Github is not for support, ask on discord.

**Comment by WSSDude420** [comment]
Also it is not our issue - it is some mod debug log and it does not even look likean error.
