### ISSUE TITLE
CET 1.19.5 - Game version 1.52.1 not working with GOG game version

### ISSUE THREAD

**Issue by Menno5** [yamashi/CyberEngineTweaks#680]
CET 1.19.5 - Game version 1.52.1 released today doesn't work with the GOG version of CP2077.
As I understand there was an update but for Steam only? There is no update on GOG Galaxy. Tried a forced update but there is none.
Tried CET 1.19.4 again and that is working fine.

[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/8418031/cyber_engine_tweaks.log)

**Comment by yamashi** [comment]
Known issue, I am reuploading 1.19.5 as soon as it finishes building :)
