### ISSUE TITLE
Crash on switching Scaling related Graphic Options

### ISSUE THREAD

**Issue by RP-FreakaZ** [yamashi/CyberEngineTweaks#682]
Crash Bug introduced with CET v1.18.3

Whenever i toggle SRS/DLSS/FSR via CET the game crashes after a period of freezing. This started with CET 1.18.3 on Patch 1.31 and still consists with CET 1.19.5 on Patch 1.52. It works fine with CET 1.18.2 on Patch 1.31.

To reproduce the issue (asuming DLSS is OFF):
`
Game.GetSettingsSystem():GetVar('/graphics/dynamicresolution','DLSS'):SetIndex(2)
GetSingleton("inkMenuScenario"):GetSystemRequestsHandler():RequestSaveUserSettings()
`

This will switch to DLSS Quality and on saving the User Settings, the game freezes for some seconds until it crashes completly. It doesn't matter if its SRS/DLSS on Patch 1.31 or FSR/DLSS on Patch 1.52. Always the same behaviour.

Hoping for a fix. ;-)

**Comment by yamashi** [comment]
Sadly this is game related, we only expose what the game provides :(

**Comment by RP-FreakaZ** [comment]
Hey Yamashi,

i don't wanna bug you, but as i pointed out, it happens since CET 1.18.3 on
Patch 1.31.

The Changelog says, you modified the D3D12 Hook to fix crashes with
Reshade. It has nothing to do with the Patches of CP.

I tested down to CET 1.16.4 (first 1.31 support), up to 1.18.2 (second last
1.31) to find the Version that introduced that behaviour. It ist 1.18.3 and
it is still present.

Even bootet up my CP 1.23 copy with CET 1.15.0, works fine there also.

Sincerely

**Comment by lKobi** [comment]
Also crashes when changing to fullscreen, and crashes on exit.

None of this happens when not using this MOD, so is hard to believe is game related.

I also noticed this mostly affects AMD builds.

**Comment by yamashi** [comment]
This doesn't seem related to the issue here.

**Comment by lKobi** [comment]
Is entirely related as changing resolution is part of the graphics settings, not only that but SRS, DLSS and FSR are dynamic resolution scalers (which change resolution).

Which is where the game is crashing as OP stated.

As for the problem of the game crashing on exit, this was reported 6 months ago and never fixed, people been simply ignoring it.

**Comment by yamashi** [comment]
The op is talking about using hidden config options via scripting, are you talking about that?

Crashing on exit is a very low priority "issue" as it doesn't alter the experience. AMD's drivers are crap, nothing we can do about this.

**Comment by lKobi** [comment]
I'm saying this problem can be easily replicated by using the game UI on graphics settings, all you have to do is change scale, resolution or enable SRS, DLSR or FSR.

The options OP is using are not hidden and are available in the UI, he simply going through CET, the end result is the same.

AMD drivers are perfectly fine and the game doesn't crash whasoever without this MOD, shifting blame over to others, is why this problem hasn't been fixed in over 6 months.

**Comment by yamashi** [comment]
It's opensource, feel free to solve the issues, I am not buying an AMD card to debug something that has been reported twice in 6 months.
