### ISSUE TITLE
Problem with MSI Afterburner, IGCSClient and CyberLit

### ISSUE THREAD

**Issue by unk0wn-u53r** [yamashi/CyberEngineTweaks#687]
Hey, is it possible that IGCSC doesn't work fully with the CET. 
IGCSClient and CyberLit only work properly when MSI Afterburner is closed. 
Without CET, however, IGCSC and Cyberlit already work with MSI Afterburner.
It would be excellent you can proof that.

**Comment by yamashi** [comment]
Running multiple hooks is always going to get messy, we do not support this kind of usage as it would require us to test pretty much everything.
