### ISSUE TITLE
Delayed loading of mods

### ISSUE THREAD

**Issue by Halliphax** [yamashi/CyberEngineTweaks#692]
Enhancement request to add an option to global.ini which will trigger the "Reload All Mods" code 'x' seconds after the game boots up.

This would give CET and Mod Organiser 2 compatibility with each other with minimal amount of work. At the moment, CET plugins aren't detected if they are loaded with MO2 until the "Reload All Mods" button is pressed.

**Comment by WSSDude420** [comment]
global.ini is for ASI loader, it is not directly CET file.

But delay could be added as additional CET option so will leave this open as enhancement, it should not be that hard to do.

Dont know how this could affect mods working with TweakDB as Im pretty sure there was some time during which edits to it were OK, but I may be wrong...

Anyway, leaving open for now as mentioned, will need to be looked at how feasable it is.
Could be it is just wrong for general context and we could break mods with it.

**Comment by WSSDude420** [comment]
Wont fix in the end, mods rely on specific timings of things, mainly for early hooks. Cant be done in general way.
