### ISSUE TITLE
binding popup issuse

### ISSUE THREAD

**Issue by sam65290** [yamashi/CyberEngineTweaks#694]
I installed the CyberEngineTweaks and i am not getting the popup to set binding key there is no app using on screen overlay can any one plzz help me

**Comment by dragonzkiller** [comment]
This is not an issue. Just delete your `bindings.json` file located in the `bin\x64\cyber_engine_tweaks` subdirectory of your Cyberpunk 2077 install directory and restart the game. If all is good, you'll see a popup to rebind the key when the game is loaded.
