### ISSUE TITLE
d3dcompiler_47 Instructions

### ISSUE THREAD

**Issue by har-nick** [yamashi/CyberEngineTweaks#695]
The "Setting up the mod with ProtonTricks" section has an appeal for instructions to install d3dcompiler via WINE so I thought I'd post two ways on how to do it.

<details>
<summary>
Through the GUI
</summary>

1. Launch winetricks in your game's prefix. Since I'm using GOG via Lutris, I didn't use the Steam directory.

`env WINEPREFIX="/games/gog/cyberpunk-2077/" winetricks`

2. Select "Select the default wineprefix"

3. Select "Install a Windows DLL or component"

4. Scroll down a little until you see d3dcompiler_XX.

5. Check the "right" version, and exit winetricks.

In my case, I checked d3dcompiler_47. I can assume this'll be updated again at some point.
</details>

<details>
<summary>
Through the console
</summary>

1. Grab a list of all DLL versions using this command:

`winetricks list-all | grep d3dcompiler`

2. Just run this command, again replacing the prefix with your own:

`env WINEPREFIX="/games/gog/cyberpunk-2077/" winetricks d3dcompiler_47`

</details>

Regardless of which way you do it, it seems as through you cannot uninstall these DLL files once installed, even by unchecking them in the GUI. You'd have to completely delete your prefix and reinstall.

I'd submit a Pull Request to change the documentation page, but I've no idea how to do it and I'd rather leave it to the people who do.

**Comment by shmerl** [comment]
You can simply delete the DLL manually and replace with stock DLL stub file. And yeah, there is no way to uninstall it using winetricks itself,

**Comment by shmerl** [comment]
I guess the main thread for that is  in #660.

Just to follow up, since Wine started implementing d3dcompiler features.

As of Wine 7.16, you still need native `d3dcompiler_47` for cyberengine tweaks to work. Just tested it without it and it didn't start.

**Comment by WSSDude420** [comment]
We do not officialy support linux, guides were made by the community. Feel free to update the wiki with more up-to-date info, best place to discuss this would probably be our Discord server.

Closing this as it is not really an issue (we never intended or officially supported linux as mentioned and we won't for various reasons)

**Comment by shmerl** [comment]
I just tested Cyberpunk 2077 with CyberEngine Tweaks using built in d3dcompiler_47.dll (Wine 8.19) and it works fine! So there is clearly some progress to it and it doesn't need the native override anymore.
