### ISSUE TITLE
GameVersion 1.6 "My Rewards" & "Cloud Save" Compatibility Issues

### ISSUE THREAD

**Issue by Ivinedra** [yamashi/CyberEngineTweaks#702]
Game version 1.6
CET Version 1.20.0
No other mods installed.

The "My Rewards" option on the title screen states that you need to log into the REDlauncher via your account prior to the start of the game when you have CET installed.... regardless if you launch the game from the RED Launcher while logged in.

Additionally, it appears that CET prevents connecting to the cloud storage, as you get a menu prompt that states "There was a problem connecting with cloud storage. You can continue with a local save or try again."

This only happens if you have the "Skip Start Menu" option enabled.

**Comment by yamashi** [comment]
This is an intended behaviour of the game, it doesn't enable online services when skipping the start menu.
