### ISSUE TITLE
CET Fails to Load with Non-ASCII Characters in Install Path

### ISSUE THREAD

**Issue by dragonzkiller** [yamashi/CyberEngineTweaks#705]
CET will not load properly if the game's installation folder has non-ASCII characters in the path. See the modding Discord for more information and a user testing the issue: https://discord.com/channels/717692382849663036/795037292955172895/1023653216400973905

**Comment by WSSDude420** [comment]
Fixed by https://github.com/yamashi/CyberEngineTweaks/commit/22017dd6717b9edb11f32fde2e0e82d2588728a4
