### ISSUE TITLE
CET mods failing to load when user has lua installed locally

### ISSUE THREAD

**Issue by Therosin** [yamashi/CyberEngineTweaks#709]
after spending a few days trying to debug why all my mods suddenly stopped working i realized that CET is listening to windows environment variables for lua.
im not sure how many people this would realistically effect but i use lua a lot so i have lua installed on all my systems.

`autoexec.lua` didnt seem to be running at all (not printing the started message) after commenting out the line to require json it would load just fine.

further inspection showed that the `package.path` in CET was set to my local users LUA_PATH
```
[2022-09-28 17:32:01 UTC+01:00] [info] [] Package Path C:\Users\Theros\AppData\Roaming\LuaRocks\share\lua\5.1\?.lua;C:\Users\Theros\AppData\Roaming\LuaRocks\share\lua\5.1\?\init.lua
[2022-09-28 17:32:15 UTC+01:00] [info] [] LuaVM: initialization finished!
```
by adding a line at the top of `autoexec.lua` to correct the package path to point to path to CET scripts folder, everything now loads as expected.
```
package.path = "./?.lua;./?/init.lua;../mods/?.lua;../?/init.lua;" .. package.path
```
im not certain the mods folder needs to be included but was added just incase, it does seem to work fine ONLY adding
`./?.lua` though if future module are added that use `./moduleName/init.lua` then that's covered by the second entry `./?/init.lua`

im still unsure as to why this issue has only just cropped up, ive had lua installed and didn't have this issue on in previous versions, i had the same rxi lib installed locally in the past so that's probably why it never showed up, recently cleared out a lot of my luarocks libs. so it kinda makes sense realy.

**Comment by WSSDude420** [comment]
We definitely do not do that directly. I suspect either sol2 or openestry-luajit doing this. Someone should have a look at what exactly causes the issue and if it can be fixed easily.

If it is just some feature of one of the two which we cannot disable or something, I dont think we can do anything about it and creating an issue about this in appropriate lib should be the next step.

**Comment by Therosin** [comment]
Well this will effect any lib. the `package.path` is the searchpath for lua libs. if its set to what my LUA_PATH contains. then it will never find any libs other than what i have installed via luarocks.
the given fix above works. and is all that is realy needed. it overrides the `package.path` appending the right dirs forcing lua to look in CET dirs "first"
i dont know sol but you should be able to set the `package.path` there from CETs code before even handing over to lua. that way you could avoid the need to have the line in autoexec

**Comment by WSSDude420** [comment]
Yep, sounds like that should be easy fix then.

Tbh, I just skimmed over it as Im in work currently, wanted to have a look when I come home.

Still would like to have a look at all the env vars that one can set like this, as it kinda defeata purpose of the sandbox when you can easily override it like this :)

**Comment by WSSDude420** [comment]
Meant like you can just set environment variable before launching CP77 with CET and basically bypass whole sandbox, not that us overriding it is bad.

**Comment by Therosin** [comment]
well you have LUA_PATH for standard lua libs (.lua)
and you also have LUA_CPATH for when loading dll's ive not seen use of clibs yet in mods but haven't gone looking for them either.
(do you still support dlopen/loadlib) but lets say someone packages a mod with luamysql or something. you could in theory set the lua_clib path forcing it to load "your own luamysql" instead and that could potentially be anything

**Comment by WSSDude420** [comment]
Fixed by https://github.com/yamashi/CyberEngineTweaks/commit/9eeffec7a13552856333ba8c1a7eb2ec652ccc43
