### ISSUE TITLE
Reduce number of D3D12 context resets

### ISSUE THREAD

**Issue by WSSDude420** [yamashi/CyberEngineTweaks#725]
As title says, reduce somehow how much we reset state as we do it a lot of the times unnecessarily.

We also reset context 4 times on shutdown currently, as we don't know exactly when our swapchain is freed (just cca time)

**Comment by yamashi** [comment]
Where are the changes?

**Comment by WSSDude420** [comment]
https://github.com/yamashi/CyberEngineTweaks/commit/79d5e1a11ca297ac852143e64026bdaf007b974d
https://github.com/yamashi/CyberEngineTweaks/commit/244ad82880b19e1a1184a8caa9501cd84d389e7b

Probably some bits and pieces in other...
We were referencing wrongly some COM objects before, should be hopefully better now.

ImGui impl manages this on its own, I didnt touch that (presuming it was not modified in a way that should break sth)
I will be updating these anyway to latest 1.88-docking versions so we have full access to docking etc.

**Comment by yamashi** [comment]
The changes you made are not fixing anything https://learn.microsoft.com/en-us/cpp/cppcx/wrl/comptr-class?view=msvc-170#operator-ampersand 
They actually introduce a memory leak as the pointer isn't

**Comment by WSSDude420** [comment]
Im unsure now what exactly you mean.
You mean the usage of GetAddressOf() vs. addressof operator?

Could be, will check and fix after work. I see one is doing release as you say and other not...
There were problematic uses of & before, I was replacing them with the Get() and GetAddressOf() to distinguish intention better. 

It was asserting in debug before that as addressof expected internal data to be nullptr. And it was used in context of pointer array, which was wrong. Usages of ExecuteCommandLists think was the one.

**Comment by WSSDude420** [comment]
Also, we were leaking before too as mentioned. QueryInterface functions should operate on ComPtrs or have resources released manually after use, which we did not do in multiple places. They AddRef to pointers.

Think overall, if this issue you mentioned gets resolved, I think we should have better resource handling with less leakage.

**Comment by yamashi** [comment]
GetAddressOf will just return the address, it will not call Release on the ptr itself so we would just overwrite the pointer but not release the previous value if it was not nullptr, the equivalent of operator& is ReleaseAndGetAddressOf but I don't understand why being verbose here is an improvement

**Comment by WSSDude420** [comment]
I guess there is no need for extra verbosity then.

I was doing this mainly to fix the issue of wrong usage of that operator before as mentioned, will change it back then for GetAddressOf usecases with & 👍 

It does not help anything now I guess, helped me personally before x)

**Comment by WSSDude420** [comment]
Thanks btw for spoting this 🙇

**Comment by yamashi** [comment]
I may not write much code, but I keep an eye on things haha

**Comment by WSSDude420** [comment]
Some extra issues/concerns I noticed in current master
- There is possibly invalid use of CommandQueue in downlevel (Win7)
- There also is an issue with a lot of unnecessary context resets (all, look into Resize)
- I dont know how safe it is that we use single command queue when we create multiple, should be checked (either we unnecessarily create resources or dont correctly work with them)

**Comment by WSSDude420** [comment]
changed the title of this, as there was only one thing left here to do

**Comment by WSSDude420** [comment]
issues with shutdown resource and script handling moved to #728

**Comment by WSSDude420** [comment]
Fixed in #757 (among others)
