### ISSUE TITLE
Font display and settings

### ISSUE THREAD

**Issue by Senfee-Cheng** [yamashi/CyberEngineTweaks#736]
There are multiple fonts in the "x64  plugins  cyber_engine_tweaks  fonts" folder, 

but the Fonts of the Dear ImGui Style Editor only read one of the "NotoSans-Regular. ttf" fonts. 

There is no place to set the font size here. 

You can only manually change config.json, and the font range can only be set in the configuration. 

I hope there can be a drop-down list for selection.
![图片](https://user-images.githubusercontent.com/20067002/200800124-6fad8255-3f8e-4de7-9db2-6de379af0bb2.png)

**Comment by WSSDude420** [comment]
Fonts are getting merged, they are not loaded all at once (would eat up all of the memory...)

If you have japanesse system, it should load in JP fonts also by default and merge them into default font. Same when yoi override glyph ranges in config.

In regards to that widget as a whole, that is not meant for normal users. It is just for debugging, it has no connection to CET settings etc.

Is just another helper/tool for modders.

Proper font settings are not yet implemented, reason there is still open task somewhere at the bottom of opened issues.

Closing this as invalid.
