### ISSUE TITLE
Upgrade Menu

### ISSUE THREAD

**Issue by SeoChoi56** [yamashi/CyberEngineTweaks#737]
Maybe it is just me but going into the Upgrade menu has crashed my game consistently.

**Comment by WSSDude420** [comment]
Did you try to do this with just CET and no other mods?
Not meaning just CET mods - redmods, redscript and its mods, red4ext and its mods.

If you can replicate this with just the game and CET, write some more detailed steps of what you mean. Upgrade menu is kinda vague.

**Comment by WSSDude420** [comment]
Closing this as there is no answer and it sounds like some other mod problem.

**Comment by SeoChoi56** [comment]
Im so sorry, real life caught up with me, but it was not CET it ended up
being a mod issue.  Sorry about that!
