### ISSUE TITLE
Simplified Linux/Proton setup

### ISSUE THREAD

**Issue by rkfg** [yamashi/CyberEngineTweaks#760]
I know you don't support Linux officially. However, there are instructions in the wiki, and they didn't work for me. I used `PROTON_LOG=1` to get a detailed log (it's stored in the home directory), turned out the mod needs `MSVCP140_ATOMIC_WAIT.dll` which is present in `vcrun2019` package. But if that package is installed in the game prefix, the game no longer starts. So here's a simpler setup that doesn't involve `protontricks` and doesn't break the game prefix:
1. Instead of overriding the `version` library with `protontricks` use `WINEDLLOVERRIDES="version=n,b" %command%` (I personally use more options to enable RTX and DLSS and skip the start screen: `WINEDLLOVERRIDES="version=n,b" VKD3D_CONFIG=dxr11 PROTON_ENABLE_NVAPI=1 VKD3D_FEATURE_LEVEL=12_1 %command% --launcher-skip -skipStartScreen`)
2. Create a temporary prefix directory: `mkdir /tmp/test`
3. Run `winetricks` in that prefix: `WINEPREFIX=/tmp/test winetricks vcrun2019`
4. Copy the required DLL to Cyberpunk directly: `cp /tmp/test/drive_c/windows/system32/msvcp140_atomic_wait.dll /path/to/Cyberpunk2077/bin/x64`
5. It is safe to delete the prefix now: `rm -rf /tmp/test`
6. The mod should work and show a prompt to set the hotkey, right in the main menu.

Hope it helps! Tested with GOG version 1.61, launched from Steam with Proton Experimental.

**Comment by WSSDude420** [comment]
Proton is kinda supported now I would say (as I use device with Linux + Proton now)

There are newer instructions on Discord, guide was not yet updated.

**Try these steps and test running the game after each one**

**Step 1:**
Renaming bink2w64.dll to bink2w64Hooked.dll and version.dll from CET to bink2w64.dll (note the case of letters, this is case sensitive!) is something that helps tons of users without any additional tricks.

**Step 2:**
If that alone does not work, switching to Proton GE should fix the rest.

**Step 3:**
In case of Error 126 (or when none of the above functions for Linux) can be solved by downloading latest version of VS2022 runtime from Microsoft site
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022 (direct download link: https://aka.ms/vs/17/release/vc_redist.x64.exe)
And install this with correct prefix in Proton's case. 
We do not use VC++ 2019 anymore, we switched to 2022 few versions back so using DLLs from 2019 won't fix things probably, something else probably helped for some reason there.

**Step 4:**
If it still does not work, would try different launcher (in case of non-steam version, seems like Heroic has some weird defaults while Lutris for example works on same machine)

**Comment by WSSDude420** [comment]
Pinning this as ticket of these sorts gets opened like 2 times a month and it is cumbersome...

**Comment by rkfg** [comment]
Thank you, this bit is interesting:
> We do not use VC++ 2019 anymore, we switched to 2022 few versions back so using DLLs from 2019 won't fix things probably, something else probably helped for some reason there.

With `PROTON_LOG=1` I get this message in the log: `102154.398:012c:0130:err:module:import_dll Library MSVCP140_ATOMIC_WAIT.dll (which is needed by L"Z:\\opt\\games\\Cyberpunk 2077\\bin\\x64\\plugins\\cyber_engine_tweaks.asi") not found`. I suppose the functions you use from that DLL are present in the 2019 version too. Either way that DLL has to be provided manually, at least for the build from Nexus that I use.

**Comment by WSSDude420** [comment]
Could be actually tbh, 2015-2022 are ABI compatible. That is you should be able to mix-and-match different DLLs/EXEs from these together, but it only works forwards.

So 2015 DLL on 2022 EXE works, not the other way around though.
Or at least it shouldn't, could lead to something unexpected if nothing else definitely as it is not DLL meant to be used by target binary.

**Comment by rkfg** [comment]
As I said, the main binary depends on one of the VC runtime libraries. I didn't try a 2022 version. If it's not a problem in your case then this library must be available elsewhere. Also, the builtin `d3dcompiler_47` works just fine, it shouldn't need overriding.

**Comment by shmerl** [comment]
I suppose Wine already implemented that vc runtime library enough for it to work, since I don't have any related overrides.

And with `d3dcompiler_47` set to builtin, the plugin doesn't load, so I assume Wine didn't implement enough of it yet despite some initial code. I just tested it with Wine 7.22.

**Comment by rkfg** [comment]
That could be the main difference because I tested with Proton Experimental which runs Wine 7.0. On one hand it lags behind the upstream Wine, on the other hand it might contain game-related fixes like that compiler.

**Comment by shmerl** [comment]
Actually, may be I do have vcruntime libs installed (possibly GOG installer added them?). But I don't see them as overrides in winecfg.

**Comment by rkfg** [comment]
There are no overrides because there's nothing to override lol. Those libs aren't a part of wine (yet?).

**Comment by shmerl** [comment]
Checking it within `system32` directory, I see the current ones:

```
rg --follow --glob '*.dll' --binary --files-without-match 'Wine builtin DLL'

wineopenxr.dll
vrclient_x64.dll
lsteamclient.dll
vccorlib120.dll
vccorlib140.dll
vccorlib110.dll
vcamp120.dll
vcamp140.dll
dxgi.dll
d3dcompiler_47.dll
xactengine2_8.dll
xactengine2_6.dll
xactengine2_5.dll
xactengine2_3.dll
xactengine2_2.dll
xactengine2_10.dll
xactengine2_1.dll
openal32.dll
nvencodeapi64.dll
nvcuvid.dll
nvcuda.dll
d3d12.dll
d3d10core.dll
vcruntime140.dll
vcomp120.dll
vcomp140.dll
d3d9.dll
d3d11.dll
msvcr110.dll
msvcr120.dll
msvcp140.dll
msvcp120.dll
msvcp110.dll
concrt140.dll
atl110.dll
```

So yeah, may be vc runtime libs are needed after all.

**Comment by shmerl** [comment]
But, I think Wine does try to implement these libraries in general.

Example: https://gitlab.winehq.org/wine/wine/-/tree/master/dlls/msvcp140

**Comment by rkfg** [comment]
There's no code in those directories, only a spec and a few tests. Looks more like a stub to me.

**Comment by shmerl** [comment]
Some are stubs, some are not, so I suppose it's just incomplete. But I'm still curious if Wine picks up the native files without overrides being specified. It's not what I'd expect. I can look into it.

**Comment by shmerl** [comment]
OK, so I did some experimenting, and removed all these from system32 in the game prefix:

```
vccorlib120.dll
vccorlib140.dll
vccorlib110.dll
vcamp120.dll
vcamp140.dll
vcruntime140.dll
vcomp120.dll
vcomp140.dll
msvcr120.dll
msvcr110.dll
msvcp140.dll
msvcp120.dll
msvcp110.dll
concrt140.dll
atl110.dll
```

Then I run `wineboot --update` for it to replace them all with built in DLLs when appropriate.

Launched the game... and it worked fine! With cyberengine tweaks loading and all. So I think we can conclude that installing vc runtime libs is not necessary, at least with Wine 7.22 that is.

**Comment by shmerl** [comment]
You can try it yourself - you can back up the files first in case you need to restore them.
