### ISSUE TITLE
Stuttering after installing CET (no additional mods)

### ISSUE THREAD

**Issue by Ikthel** [yamashi/CyberEngineTweaks#763]
Cyberpunk version: 1.61 (3.0.66.28510)
CET version: 1.21.1
OS: Windows 11

Description: After installing CET the game stutters. Removing CET the stutter is gone.

Note: No additional mods installed, manual install of CET, default CET values unmodified. Same result with or without amd_smt checked. Verified game files. Steam installation on C: - Steam library E: - (both m.2 drives.)

[config.txt](https://github.com/yamashi/CyberEngineTweaks/files/10109221/config.txt)
[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/10109223/cyber_engine_tweaks.log)
[gamelog.log](https://github.com/yamashi/CyberEngineTweaks/files/10109224/gamelog.log)

**Comment by WSSDude420** [comment]
Could you check against staging branch?

CI artifact corresponding to it: 
https://github.com/yamashi/CyberEngineTweaks/actions/runs/3523309388

Zip there has same structure as normal CET release so apply it the same way.

**Comment by Ikthel** [comment]
Sweet, thanks so much.

This has resolved the issue. Awesome work and thanks again Dude!
