### ISSUE TITLE
Remove POI Mapping

### ISSUE THREAD

**Issue by hugorlima** [yamashi/CyberEngineTweaks#778]
Hi guys, I'm wondering about having a way to remove/disable/unset these functions below:

Game.GetJournalManager():DebugShowAllPoiMappins()
Game.GetMappinSystem():DebugDiscoverAllPoiMappins()

It's been quite annoying to have some duplicates of POI on my map and the quests that I've finished also.

Do we have some way to fix that?

Thanks

**Comment by WSSDude** [comment]
This is more of a scripting question that you should ask about on Discord (link in readme).

There is #cet_lua_scripting channel you can visit, you may get more luck there. This is for tracking issues with CET itself, not scripting.
