### ISSUE TITLE
Cyberpunk 2077 | Easy Patcher 2.0

### ISSUE THREAD

**Issue by LittleZen** [yamashi/CyberEngineTweaks#78]
i'm sorry for bothering you another time! 

I've worked hard, and i was able to upload the new version (2.0) in 16h! I'm not really skilled with GitHub, so if someone can help me, i could merge my work with this repository, otherwise, we could just let the 2 repository separate, but if you wish, just simple add link in the readme to my easyinstaller, many people could find my tool usefull (you can now easy manage the settings through the tool, and it will automatically detect the location of config files, without ask you all time the path and allow you to not search all time for json files, it is automatically detected!)

waiting for news <3

![image](https://user-images.githubusercontent.com/35767830/102331772-8936b500-3f8b-11eb-97cd-e55fea1b9c8f.png)

[REPOSITORY](https://github.com/LittleZen/Cyberpunk2077-Patch-Easy-Installer)

**Comment by yamashi** [comment]
You need to pick a real license before anyone can use this, I believe it is indeed better to keep repos separate. I will probably build an auto installer soon enough

**Comment by LittleZen** [comment]
I will select the license soon! And yes, imo is better leave it separate. If you wish create the patcher by your own it's ok, but i already did part of the work, feel free to re-use it !

**Comment by yamashi** [comment]
Made a PR, please address the issues mentioned and then we can make it "official" ;)

**Comment by LittleZen** [comment]
Oh ... awesome! I've added the license, but i'm not really skilled with GitHub, i don't know how to correctly create a PR for merge 2 repository in 1! 

Reach me on discord (Zenek#2802) if you wish, i believe we could fix it in 5 minutes and many people can be reach and helped thanks to your amazing work (and with a simple wizard installer that we just made)

**Comment by Saibamen** [comment]
Please check docs: https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by ArturVRSampaio** [comment]
works on linux?

**Comment by LittleZen** [comment]
Nope, only windows x64 :(

**Comment by elogicuk** [comment]
> works on linux?

I also use linux, just copy and paste the files into the dir so easy

**Comment by StKob** [comment]
It would be great if program offered patch updates.

**Comment by LittleZen** [comment]
> It would be great if program offered patch updates.

Yes, i'm currently developing it + uninstall system + log view and other stuff!

**Comment by XCanG** [comment]
If you really want to make crossplatform installer, you may consider to write it on Python instead. You may use internal Tkinter module to make windowed app if you wish.

It have all widgets you are using:
Label, Button, LabelFrame ("Settings:" section), Checkbutton, Frame (grid layout)

**Comment by LittleZen** [comment]
@StKob released as requested

@XCanG  if you are talking to me, my idea is to reach the windows-community. I'm not really skilled on linux, and i guess if you can actually play the game on linux-distro, is not that hard for you install the main patch from yamashi. Mine is just an easy installer, it doesn't replace the real amazing work of yamashi!

**Comment by StKob** [comment]
@LittleZen Great job, works like a charm. Only question why winrar was in Italian?

**Comment by LittleZen** [comment]
Hem .... i'm italian ahahahahah sorry i will change it in the next release 2.4 (less then 24h to release)
