### ISSUE TITLE
No ability to exit a vehicle when outside of map limits

### ISSUE THREAD

**Issue by shmerl** [yamashi/CyberEngineTweaks#781]
I tried driving out of the map area in the nomad prologue near the radio tower and noticed that when leaving the border (with restriction disabled in the CET), it's impossible to exit the car (no such option even in the UI in that area).

Is it a bug or some general restriction or something specific to prologue?

**Comment by Masamune3210** [comment]
If 2077 is anything like most other games, either it prohibits you from exiting a vehicle on things it doesn't consider solid land or it prohibits leaving vehicles outside of a designated range

**Comment by shmerl** [comment]
May be it would be useful to relax such restriction or add another option like "exit the vehicle outside the borders"?

**Comment by yamashi** [comment]
This kind of feature is outside the scope of this project
