### ISSUE TITLE
Unable to load cyber_engine_tweaks.asi. Error：126

### ISSUE THREAD

**Issue by LAGQWQ** [yamashi/CyberEngineTweaks#783]
安装CyberEngineTweaks后，打开游戏就会弹窗提示。我的游戏版本是1.61，cet版本是1.21。我从未遇到过这样的错误，网上也搜不到，希望各位可以解答一下，谢谢了！
I'm a Chinese and I don't know much English, so I use web translation. There may be some places where the expression is unclear, so sorry.
After installing CyberEngineTweaks, a pop-up prompt will pop up when you open the game. My game version is 1.61 and the CET version is 1.21. I have never encountered such an error, I can't find it on the Internet, I hope you can answer it, thank you!

![image](https://user-images.githubusercontent.com/112602213/211735964-3b5c8f4b-c720-4ab6-98f2-47958292bb28.png)

**Comment by Soulless-Desires** [comment]
That not bug they can fix. you need to Install latest (2022) ms Redistributable x64 (https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) to fix that error.

**Comment by LAGQWQ** [comment]
> That not bug they can fix. you need to Install latest (2022) ms Redistributable x64 (https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) to fix that error.

Thanks, successfully solved!
