### ISSUE TITLE
Unable to load cyber_engine_tweaks.asi error 126

### ISSUE THREAD

**Issue by KillerJoe23** [yamashi/CyberEngineTweaks#786]
I get this error after installing CET and Native Settings and Metro System:

![image](https://user-images.githubusercontent.com/123906911/215359058-a7967b2d-7d1a-4c02-900f-3deb6e570069.png)

This message appears twice, once after clicking on the Cyberpunk 2077 shortcut and again after I click OK

Afterwards, Cyberpunk 2077 works fine but none of the mods load.

I am using Cyberpunk 2077 (steam version) patched to 1.61.

The only mods I have installed are the following:

Game version 1.61 - fix 1-107-1-21-1-1668271994 - This is the CyberEngineTweaks version I downloaded
Native Settings UI 1.92-3518-1-92-1673118948
Metro System 1.8-3560-1-8-1673727377

**Comment by WSSDude** [comment]
You need to download newer VC runtime. You probably have outdated one.

You can install it from here https://aka.ms/vs/17/release/vc_redist.x64.exe
