### ISSUE TITLE
Getting Initialize Error when loading CET

### ISSUE THREAD

**Issue by dsevvv** [yamashi/CyberEngineTweaks#789]
CET Version: fix 1 for game version 1.61 (12th of nov release date)
Cyberpunk version: 1.61
OS: Windows 10

Description:

My game launches fine, however CET does not appear to be loading properly, you will see the error "42120" in the log file that I provide. Please note that this was done on a fresh install of CP2077 & Vortex. I installed the mod through nexus & vortex.

Config: There doesn't appear to be a config.json file in my "cyber_engine_tweaks" directory.
Log: [cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/10551445/cyber_engine_tweaks.log)

**Comment by dsevvv** [comment]
Just tried to launch again, here is the updated .log file:

[cyber_engine_tweaks.log](https://github.com/yamashi/CyberEngineTweaks/files/10551488/cyber_engine_tweaks.log)

**Comment by dsevvv** [comment]
After checking the discord, it appears that CET is not yet updated for the most recent patch. Closing this issue.

**Comment by SherlockChiang** [comment]
same question.
so how to reslove?
