### ISSUE TITLE
v1.61_DLSS3 SSE FIX?

### ISSUE THREAD

**Issue by saha1914** [yamashi/CyberEngineTweaks#796]
is it possible to make sse fix to?got rtx card with phenom 2 x1100t cpu really like to play the dlss3 version there might be some people like me that a sse fix means a lot to them.thanks!!!!

**Comment by WSSDude** [comment]
We won't be doing this. It would require a lot of additional patches to the exe and quite possibly to bunch of game dlls, it is questionable how well it would work in general and would be yet another big thing to maintain... Your CPU is simply too old, patching the game to use just up to SSE3 is just too much, sorry.
