### ISSUE TITLE
Instant game crash

### ISSUE THREAD

**Issue by downloadOnly0** [yamashi/CyberEngineTweaks#801]
Game crashes within a few seconds of opening. Most recent version of CET, game version 1.61 on Steam.

CET log has this:
[info] [Options] Cyber Engine Tweaks is starting...
[error] [Initialize] 5D
[error] [Initialize] 30
[error] [Initialize] A1
[error] [Initialize] 30
[error] [Initialize] F
[error] [Initialize] 7F
[error] [Initialize] 5E
[error] [Initialize] 4C
[error] [Initialize] A9
[error] [Initialize] BA
[error] [Initialize] D8
[error] [Initialize] 43
[error] [Initialize] D9
[error] [Initialize] AE
[error] [Initialize] 85
[error] [Initialize] 50

**Comment by yamashi** [comment]
No it does not, ask for support on discord.
