### ISSUE TITLE
Steam Controller API support

### ISSUE THREAD

**Issue by Reinachan** [yamashi/CyberEngineTweaks#85]
I don't see CDPR ever doing this on their own, so would be nice if the community did. Anyway, question is if you could add some support for the Steam Controller API beyond what's already done to enable Steam Controller support. Especially an option for automatically changing action set when you enter a vehicle. Not sure if this is even possible to do or if it's out of the scope of this.

**Comment by judy** [comment]
Fellow Steam Controller owner here. If not a candidate for addition to this engine directly, it would help if the engine exposed enough of an interface so someone else could script it via Lua.
