### ISSUE TITLE
Patching research idea - Developer Debug Mode?

### ISSUE THREAD

**Issue by DartPower** [yamashi/CyberEngineTweaks#94]
![image](https://user-images.githubusercontent.com/2005369/102410772-14529200-4002-11eb-81b6-988b4203f50b.png)
CyberConsole
![image](https://user-images.githubusercontent.com/2005369/102410824-26cccb80-4002-11eb-8c1f-7002595e17e6.png)
Save's Metadata

Can you find developer debug blocking code? It's like the DOOM Eternal, Spore and other game situations, where game have a checking for build type (Release or Debug, for example: DOOM Eternal 1000+ codes or Spore's DebugRelease (Hiding the console commands in Release version) and etc)

Theoretical, If this is found, then it will be possible to access to massive(?) blocked functions & commands. 
P.S. Game is very new, not all is researched. Game EXE have mentioning of multiplayer, debug and map editor functions.

**Comment by yamashi** [comment]
This is probably simple to find, will give it a shot tomorrow ;)

**Comment by lrhinehart0724** [comment]
Any news on this? Im looking for Veh.SpawnCar () It says random i was hoping reference id would work too not that once that works I would even know where to start to get the item ids for the cars.

**Comment by JulianVolodia** [comment]
hey Guys, I don't have version from 16-17 of Dec '20, but was that 1.06?
Afaik they removed many things in futher releases.

hi @yamashi I've question about your tactics, shall we use CheatEngine to diff mem state while loading patched sav.dat or You wanted to analyze app executables in-place, and if second - which tool do you like to use? Cheers!

**Comment by Marchauff** [comment]
I don't think that the debug menu is working, anymore. I just updated to 1.11.4 and I can't the debug menu to appear. I was wondering if that was on purpose or something that needs to be worked on?

**Comment by WSSDude420** [comment]
@Marchauff known and fixed, #505

**Comment by WSSDude420** [comment]
btw, closing this cause i believe this was left open accidentally.

if it was not, feel free to reopen, but we have some debug options enabled with patch (till it broke with v1.11.1)
