### ISSUE TITLE
Way to reduce FPS drops when turning?

### ISSUE THREAD

**Issue by rk-exxec** [yamashi/CyberEngineTweaks#96]
I was wondering if you could make an option which makes the game keep the scenery behind the player in memory (or load it) so that the FPS doesn't drop when turning around quickly?
My RAM sits at 3GB even with the fix, so there is some room.

If that is how it works.

**Comment by yamashi** [comment]
You mean disable culling and streaming? I can take a look, afaik if you enable slow disk that's what it does

**Comment by rk-exxec** [comment]
Oh, I see. I'll try with the slow HDD mode.

**Comment by NielsGx** [comment]
Pretty sure it would hut performance a lot.

A distance slider for cars could be more useful. When going out of bounds, I realized a lot of cars are loaded in the distance. Like thousands of cars, and at least +500m in the distance

**Comment by Nigh7Stalk3r** [comment]
> Pretty sure it would hurt performance a lot.
> 
> A distance slider for cars could be more useful. When going out of bounds, I realized a lot of cars are loaded in the distance. Like thousands of cars, and at least +500m in the distance

Those "cars" you see in the distance are just 2D sprites, they don't' affect performance

**Comment by rworang** [comment]
Disable motion blur
