### ISSUE TITLE
[Enhancement] dedicated button to holster weapon

### ISSUE THREAD

**Issue by Jeddunk** [yamashi/CyberEngineTweaks#99]
While it is possible to edit the game's configuration file to disable the double tap dodge function and add a dedicated button for dodging, this is not possible with the "holster weapon" function (which is only possible by either double tapping ALT or by opening the weapon wheel). This may be possible to implement through the hook.

_Even if this won't be implemented, it's a good idea for a separate plugin._

**Comment by PhantomGamers** [comment]
I would love to see this but I imagine this, like the skipping the opening movies, would have to be done via the scripting system. Hopefully someone works out the decompilation/recompilation of the game scripts, or CDPR makes our lives easier by just releasing a REDKit for Cyberpunk

**Comment by snailzrus** [comment]
Other mods have already dealt with this. I don't know if the creator of this mod holds the same opinion, but this mod is more targeted at performance rather than quality of life features like button remapping.

**Comment by PhantomGamers** [comment]
> Other mods have already dealt with this.

The only 'solution' I'm aware of for this is to set "count" to 1 in the input xml file, but this doesn't actually work consistently.
